from __future__ import annotations
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parent;V=R/'reviews'/'Zeph';O=R/'book_chunks'/'Zeph'/'chunks.jsonl'
def L(n):return json.loads((V/n).read_text(encoding='utf-8'))
def rows(d):return d.get('chunks') or d.get('units') or d.get('proposed_chunks') or []
def pt(v):v=v.replace('Zeph.','').replace('.',':');a,b=v.split(':');return int(a),int(b)
def pair(v):p=v.split('-');return pt(p[0]),pt(p[-1])
def ov(a,b):a0,a1=pair(a);b0,b1=pair(b);return a0<=b1 and b0<=a1
def ren(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))
lit=L('blind_proposal_literary_v1.json');can=L('blind_proposal_canonical_premortem_v1.json');heb=L('blind_proposal_hebrew_textual_v1.json');lr,cr,hr=rows(lit),rows(can),rows(heb);g=lambda d:{k:v for k,v in d.items() if k not in {'chunks','units','proposed_chunks'}};out=[]
for i,s in enumerate(lr,1):
 sp=s['span'];did=f'M7_sol-Zeph-{i:03d}';cs=[x for x in cr if ov(sp,x['span'])];hs=[x for x in hr if ov(sp,x['span'])];comp=f"selected clean literary={ren(s)}; clean canonical overlaps={ren(cs)}; qualified Hebrew overlaps={ren(hs)}; literary globals={ren(g(lit))}; canonical globals={ren(g(can))}; Hebrew globals={ren(g(heb))}; Hebrew audit saw only known chapter-placeholder summaries and counts as zero clean blind votes";form=s['literary_form'];mark=s['deciding_marker'].rstrip('.');lang=f"{sp}: {ren(hs)}. Hebrew day formulas, taunt/woe/remnant/Zion language and MT/LXX/DSS/Syriac/Vulgate/Targum variants remain evidence only; Hebrew audit is qualified nonvoting because filename search exposed placeholders; no witness, identity, history, ethics, fulfillment or theology."
 out.append({'model_id':'M7_sol','book':'Zeph','span':sp,'chunk_index_in_book':i,'working_title':s['title'],'literature_type_guess':form,'literary_form':form,'boundary_evidence_refs':[f'direct_read:eng-web:{sp}','book_strategy/Zeph.md','reviews/Zeph/blind_proposal_hebrew_textual_v1.json','reviews/Zeph/blind_proposal_literary_v1.json','reviews/Zeph/blind_proposal_canonical_premortem_v1.json','reviews/Zeph/peer_crosscheck_v1.json','reviews/Zeph/boss_ruling_v1.json','reviews/Zeph/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['qualified_Hebrew_textual_audit_nonvoting','MT_LXX_DSS_versions_evidence_only','roots_are_not_meaning','strong_lemma_not_authority'],'wj_or_red_letter_considered':False,'frontier_flag_considered':True,'confidence':'low','decision_id':did,'deciding_marker_or_seam':mark+'.','boundary_rationale':f'Prefer complete larger {form} {sp}. {mark}. Preserve day oracle, indictment, battle poem, seek summons, nations cycle, Jerusalem woe, remnant promise and Zion song.','rejected_alternative':f'Preserved exact competing evidence for {sp}: {comp}.','defensible_basis':f'{did}: {mark}. Day formula, summons, accusation, poem, taunt, woe, purification/remnant or song closure—not chapters, identity, chronology, fulfillment or theology—supports this candidate.','review_revision':1,'review_status':'final_deferred_appeal','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[comp+'.'],'original_language_translation_holds':[lang],'cross_reference_holds':['Relations to Kings, prophets, Twelve and later reuse evidence only; no history, identity, chronology, fulfillment or theology.'],'red_team_premortem_holds':[f'{sp}: chapter fallback, day/nation list atomization, indictment/verdict or woe/contrast or remnant/song detachment, genealogy/date, day schedule, nation/place identity, violence ethics, pure-speech doctrine, Zion fulfillment/theology risks. Evidence: {comp}.'],'working_title_is_boundary_authority':False,'working_title_origin':'independent_zephaniah_two_clean_blind_plus_qualified_Hebrew_larger_unit_reconciliation_v1','candidate_only':True,'review_evidence_summary':mark+'. Candidate-only and non-authorizing.','red_team_questions':[f"Does seam after {sp.split('-')[1]} survive removal of chapters/headings/later reuse?",f'Would exact alternative preserve larger form better: {comp}?'],'hard_passage_forecast':[lang],'candidate_hold_state':'deferred_human_or_external_ai','candidate_hold_basis':'preserved_appeal'})
assert len(out)==10;O.parent.mkdir(parents=True,exist_ok=True);O.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n');print(json.dumps({'sha256':hashlib.sha256(O.read_bytes()).hexdigest(),'chunks':10,'clean_blind_primaries':2,'qualified_hebrew_nonvote':True}))