from __future__ import annotations
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parent;V=R/'reviews'/'Hab';O=R/'book_chunks'/'Hab'/'chunks.jsonl'
def L(n):return json.loads((V/n).read_text(encoding='utf-8'))
def rows(d):return d.get('chunks') or d.get('units') or d.get('proposed_chunks') or []
def pt(v):v=v.replace('Hab.','').replace('.',':');a,b=v.split(':');return int(a),int(b)
def pair(v):
 p=v.split('-');a=p[0];b=p[-1];return pt(a),pt(b)
def ov(a,b):a0,a1=pair(a);b0,b1=pair(b);return a0<=b1 and b0<=a1
def ren(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))
can=L('blind_proposal_canonical_premortem_v1.json');lit=L('blind_proposal_literary_v1.json');heb=L('blind_proposal_hebrew_textual_v1.json');cr,lr,hr=rows(can),rows(lit),rows(heb);g=lambda d:{k:v for k,v in d.items() if k not in {'chunks','units','proposed_chunks'}};out=[]
for i,s in enumerate(cr,1):
 sp=s['span'];did=f'M7_sol-Hab-{i:03d}';ls=[x for x in lr if ov(sp,x['span'])];hs=[x for x in hr if ov(sp,x['span'])];comp=f"selected canonical={ren(s)}; literary overlaps={ren(ls)}; Hebrew overlaps={ren(hs)}; canonical globals={ren(g(can))}; literary globals={ren(g(lit))}; Hebrew globals={ren(g(heb))}";form=s['form'];mark=s['marker'].rstrip('.');lang=f"{sp}: {ren(hs)}. Hebrew complaint/answer/watch/tablet/woe/prayer markers, 2:4 syntax, MT/LXX/DSS/1QpHab/Syriac/Vulgate/Targum, rare theophany and music terms remain evidence only; no witness, sectarian reading, identity, history, ethics, fulfillment or theology."
 out.append({'model_id':'M7_sol','book':'Hab','span':sp,'chunk_index_in_book':i,'working_title':form.capitalize(),'literature_type_guess':form,'literary_form':form,'boundary_evidence_refs':[f'direct_read:eng-web:{sp}','book_strategy/Hab.md','reviews/Hab/blind_proposal_hebrew_textual_v1.json','reviews/Hab/blind_proposal_literary_v1.json','reviews/Hab/blind_proposal_canonical_premortem_v1.json','reviews/Hab/peer_crosscheck_v1.json','reviews/Hab/boss_ruling_v1.json','reviews/Hab/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['direct_Hebrew_complaint_woe_prayer_form_considered','MT_LXX_DSS_1QpHab_versions_evidence_only','roots_are_not_meaning','strong_lemma_not_authority'],'wj_or_red_letter_considered':False,'frontier_flag_considered':True,'confidence':'low','decision_id':did,'deciding_marker_or_seam':mark+'.','boundary_rationale':f'Prefer complete larger {form} {sp}. {mark}. Preserve complaint-answer, watch/vision, woe-taunt and prayer-theophany-confidence as coherent forms.','rejected_alternative':f'Preserved exact competing evidence for {sp}: {comp}.','defensible_basis':f'{did}: {mark}. Complaint, answer, watch/tablet, appointed vision, woe cycle, temple hush, prayer metadata, theophany or confidence closure—not chapters, identity, later reuse, fulfillment or theology—supports this candidate.','review_revision':1,'review_status':'final_deferred_appeal','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[comp+'.'],'original_language_translation_holds':[lang],'cross_reference_holds':['Relations to Torah, Psalms, prophets, Romans/Galatians/Hebrews and later reuse are evidence only; no preferred 2:4 reading, identity, chronology, fulfillment or theology.'],'red_team_premortem_holds':[f'{sp}: chapter fallback, complaint/answer or vision/instruction or woe/taunt or trembling/confidence detachment, 2:4 proof-texting, witness/pesher preference, Chaldean/faithful/anointed identity, divine violence/justice, geography, fulfillment/theology risks. Evidence: {comp}.'],'working_title_is_boundary_authority':False,'working_title_origin':'independent_habakkuk_three_blind_primary_larger_unit_reconciliation_v1','candidate_only':True,'review_evidence_summary':mark+'. Candidate-only and non-authorizing.','red_team_questions':[f"Does the seam after {sp.split('-')[1]} survive removal of chapters/headings/later reuse?",f'Would exact alternative preserve dialogue/taunt/prayer better: {comp}?'],'hard_passage_forecast':[lang],'candidate_hold_state':'deferred_human_or_external_ai','candidate_hold_basis':'preserved_appeal'})
assert len(out)==9;O.parent.mkdir(parents=True,exist_ok=True);O.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n');print(json.dumps({'sha256':hashlib.sha256(O.read_bytes()).hexdigest(),'chunks':9,'low':9}))