import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parent; OUT=ROOT/'book_chunks'/'Ruth'/'chunks.jsonl'
ROWS=[
('1.1','1.5','Migration and bereavement prologue','migration_bereavement_prologue','Famine-era migration opens the narrative; husband death, sons marriages and deaths, and Naomi left bereaved form a completed nadir before fresh return action at 1:6','Rejected expansion through 1:22: 1:6 begins a new initiated return action because Naomi hears of bread, while 1:5 completes the bereavement prologue'),
('1.6','1.22','Return dialogue pledge and Bethlehem arrival','return_dialogue_and_arrival','Naomi arises to return at 1:6; repeated return language binds dismissal, Orpah departure, Ruth pledge, acceptance, arrival, Mara speech, and barley-harvest summary through 1:22','Preserve split Ruth.1.6-1.18 / 1.19-1.22 as road decision versus arrival/lament; retain the return inclusio and Bethlehem outcome in the larger LOW unit'),
('2.1','2.23','Gleaning encounter provision and home report','field_encounter_and_report','Boaz is introduced and Ruth initiates gleaning; encounter, protection, refuge blessing, meal, commands, yield, Naomi report, goel recognition, and harvest-duration summary close at 2:23','Preserve Ruth.2.1-2.16 / 2.17-2.23 as field encounter versus result/home report; retain the report because it interprets Boaz and closes the harvest interval'),
('3.1','3.18','Rest plan threshing-floor petition and report','plan_execution_petition_and_report','Naomi proposes rest; repeated do-all-you-say/did-all-commanded/reported-all-done links plan, execution, petition, promise, gift, return, and same-day forecast through 3:18','Preserve Ruth.3.1-3.5 / 3.6-3.15 / 3.16-3.18 as plan, execution, and report; retain the causal chain while euphemism, wing/skirt, and goel force remain unresolved'),
('4.1','4.17','Gate redemption marriage birth and narrative closure','legal_proceeding_and_narrative_outcome','Gate relocation convenes nearer redeemer and elders; offer, 4:5 condition, refusal, sandal, acquisition, witnesses, blessings, marriage, birth, women response, naming, and David notice close the prose plot at 4:17','Preserve Ruth.4.1-4.12 / 4.13-4.17 as gate procedure versus marriage/birth outcome; retain claim and narrated fulfillment together while 4:5 and legal/social custom remain unresolved'),
('4.18','4.22','Perez-to-David genealogy','genealogy_register','The generations-of-Perez formula changes form; repeated became-father-of sequence closes as a complete register at David','Rejected merger with Ruth.4.13-4.17: the relation is real, but 4:18 has an explicit genealogy incipit and register shift after prose naming closure')]
LOW={2,3,4,5}; out=[]
for i,(a,b,title,form,marker,alt) in enumerate(ROWS,1):
 span=f'Ruth.{a}-Ruth.{b}'; did=f'M7_sol-Ruth-{i:03d}'; low=i in LOW
 row={'model_id':'M7_sol','book':'Ruth','span':span,'chunk_index_in_book':i,'working_title':title,'literature_type_guess':form,'boundary_evidence_refs':[f'direct_read:eng-web:{span}',f'direct_read:oshb:Ruth.xml#{span}',f'direct_read:uxlc:Ruth.xml#{span}','book_strategy/Ruth.md','reviews/Ruth/primary_hebrew_v1.json','reviews/Ruth/primary_literary_v1.json','reviews/Ruth/canonical_premortem_v1.json','reviews/Ruth/peer_crosscheck_v1.json','reviews/Ruth/boss_ruling_v1.json','reviews/Ruth/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['direct_hebrew_wording_considered','source_metadata_corrob_only','roots_are_not_meaning','original_language_is_not_boundary_authority'],'wj_or_red_letter_considered':False,'frontier_flag_considered':True,'confidence':'low' if low else 'medium','decision_id':did,'literary_form':form,'deciding_marker_or_seam':marker+'.','boundary_rationale':f'Prefer the complete {form} unit {span}. {marker}.','rejected_alternative':alt+'.','defensible_basis':f'{did}: {marker}. This exact scene/form/register signal—not chapter numbering, roots, law reconstruction, or canonical parallels—supports the candidate boundary.','review_revision':1,'review_status':'final_deferred_appeal' if low else 'candidate_review_complete','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'] if low else ['external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[marker+'.'],'original_language_translation_holds':[alt+'. Hebrew wording, WEB/MT mapping, hesed/goel, euphemism, legal custom, and genealogy evidence do not authorize a preferred reading or theology.'],'cross_reference_holds':['Internal-Bible relations are separate evidence only and cannot harmonize or decide the local seam.'],'red_team_premortem_holds':[alt+'.'],'working_title_is_boundary_authority':False,'working_title_origin':'independent_ruth_mesh_reconciliation_v1','candidate_only':True,'review_evidence_summary':marker+'. No legal, sexual, ethnic, providential, genealogical, or theological conclusion is selected.','red_team_questions':[f'Does the seam after Ruth.{b} survive removal of headings and chapters?',f'Does this explicit alternative preserve the scene better: {alt}?'],'hard_passage_forecast':[alt+'.']}
 if low: row.update(candidate_hold_state='deferred_human_or_external_ai',candidate_hold_basis='preserved_appeal')
 out.append(row)
OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n')
print(hashlib.sha256(OUT.read_bytes()).hexdigest(),len(out),sum(x['confidence']=='low' for x in out))
