from __future__ import annotations
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parent; V=R/'reviews'/'Amos'; O=R/'book_chunks'/'Amos'/'chunks.jsonl'
def load(n): return json.loads((V/n).read_text(encoding='utf-8'))
def rows(d): return d.get('chunks') or d.get('units') or d.get('proposed_chunks') or []
def pt(v):
 v=v.replace('Amos.','').replace('.',':'); c,n=v.split(':'); return int(c),int(n)
def pair(v):
 a,b=v.split('-'); return pt(a),pt(b)
def ov(a,b):
 a0,a1=pair(a); b0,b1=pair(b); return a0<=b1 and b0<=a1
def ren(v): return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))
can=load('blind_proposal_canonical_premortem_v1.json'); lit=load('blind_proposal_literary_v1.json'); heb=load('blind_proposal_hebrew_textual_v1.json'); cr,lr,hr=rows(can),rows(lit),rows(heb); assert cr and lr and hr
g=lambda d:{k:v for k,v in d.items() if k not in {'chunks','units','proposed_chunks'}}; out=[]
for i,s in enumerate(cr,1):
 span=s['span']; did=f'M7_sol-Amos-{i:03d}'; ls=[x for x in lr if ov(span,x['span'])]; hs=[x for x in hr if ov(span,x['span'])]; assert ls and hs
 comp=f"selected canonical-premortem={ren(s)}; literary overlaps={ren(ls)}; Hebrew/textual overlaps={ren(hs)}; canonical globals={ren(g(can))}; literary globals={ren(g(lit))}; Hebrew globals={ren(g(heb))}"
 form=s['form']; marker=s['marker'].rstrip('.'); lang=f"{span}: {ren(hs)}. Hebrew numerical-oracle formula, qinah, oath, wordplay, rhetorical chains, vision questions, MT/LXX/DSS/Syriac/Vulgate/Targum differences, rare terms and place names remain evidence only; no preferred witness/emendation, earthquake chronology, history, nation/vision identity, ethics, fulfillment, canon, or theology."
 out.append({'model_id':'M7_sol','book':'Amos','span':span,'chunk_index_in_book':i,'working_title':form.capitalize(),'literature_type_guess':form,'literary_form':form,'boundary_evidence_refs':[f'direct_read:eng-web:{span}',f'direct_read:oshb:Amos.xml#{span}',f'direct_read:uxlc:Amos.xml#{span}','book_strategy/Amos.md','reviews/Amos/blind_proposal_hebrew_textual_v1.json','reviews/Amos/blind_proposal_literary_v1.json','reviews/Amos/blind_proposal_canonical_premortem_v1.json','reviews/Amos/peer_crosscheck_v1.json','reviews/Amos/boss_ruling_v1.json','reviews/Amos/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['direct_Biblical_Hebrew_prophetic_form_considered','MT_LXX_DSS_versions_wordplay_and_vision_terms_evidence_only','roots_are_not_meaning','source_metadata_corrob_only'],'wj_or_red_letter_considered':False,'frontier_flag_considered':True,'confidence':'low','decision_id':did,'deciding_marker_or_seam':marker+'.','boundary_rationale':f'Prefer the complete larger {form} movement {span}. {marker}. Preserve formula cycle, lawsuit-verdict, question chain, lament/woe, vision-dialogue, confrontation scene, judgment, or restoration as a coherent unit.','rejected_alternative':f'Preserved exact competing evidence for {span}: {comp}.','defensible_basis':f'{did}: {marker}. Formula, summons, refrain, oath, woe, lament, vision question-answer, narrative reset, hymn, judgment, or restoration closure—not chapters, source theory, identity, later reuse, fulfillment, or theology—supports this candidate.','review_revision':1,'review_status':'final_deferred_appeal','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[comp+'.'],'original_language_translation_holds':[lang],'cross_reference_holds':['Relations to Torah, historical books, Psalms, prophets, the Twelve, Acts, and later reuse are evidence only; they cannot force symmetry, harmonize history, identify nations/visions/booth, settle chronology/fulfillment, select readings, or authorize theology.'],'red_team_premortem_holds':[f'{span}: chapter fallback, nations-cycle atomization, accusation/verdict or vision/dialogue detachment, list/question splitting, proof-texting, witness preference, earthquake/day/vision/booth identity, social-program, ethics, chronology, fulfillment, or theology smuggling. Exact evidence: {comp}.'],'working_title_is_boundary_authority':False,'working_title_origin':'independent_amos_three_clean_blind_primary_larger_unit_reconciliation_v1','candidate_only':True,'review_evidence_summary':marker+'. Candidate-only and non-authorizing.','red_team_questions':[f"Does the seam after {span.split('-')[1]} survive removal of chapters/headings/later reuse?",f'Would an exact literary or Hebrew alternative preserve the larger form better: {comp}?'],'hard_passage_forecast':[lang],'candidate_hold_state':'deferred_human_or_external_ai','candidate_hold_basis':'preserved_appeal'})
assert len(out)==25 and [x['chunk_index_in_book'] for x in out]==list(range(1,26)); O.parent.mkdir(parents=True,exist_ok=True); O.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n'); print(json.dumps({'sha256':hashlib.sha256(O.read_bytes()).hexdigest(),'chunks':25,'low':25}))