from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
OUT=ROOT/'book_chunks'/'Judg'/'chunks.jsonl'
# start,end,title,form,deciding seam,preserved alternative (None means medium)
ROWS=[
('1.1','1.21','Judah-Simeon campaign through Benjamin notice','campaign_and_register','Post-Joshua inquiry opens Judah first; the Judah-Simeon/Caleb-Achsah sequence reaches a first tribal non-dispossession coda at 1:21','Preserve 1:1-7 / 1:8-21 and 1:1-21 alternatives; the larger unit retains inquiry, campaign, embedded grant scene, and Benjamin coda'),
('1.22','1.26','House of Joseph captures Bethel','spy_and_mercy_scene','A new tribal subject goes up against Bethel; spying, spared guide, capture, and new-Luz notice close at 1:26',None),
('1.27','1.36','Tribal non-dispossession register','tribal_failure_register','Manasseh opens an escalating repeated did-not-drive-out register; Dan/Amorite pressure and territorial notice close it at 1:36',None),
('2.1','2.5','Bochim covenant indictment and response','messenger_oracle_response','Messenger movement from Gilgal opens a covenant accusation; weeping, place naming, and sacrifice close at 2:5','Messenger/YHWH identity and speaker labels are unresolved; keep indictment and response whole without doctrinal ruling'),
('2.6','2.10','Joshua generation retrospective','retrospective_transition','Joshua dismissal resumes the inheritance setting; death, burial, elders, and replacement-generation notice close at 2:10',None),
('2.11','3.6','Judge-cycle program and nations-testing coda','programmatic_exposition_and_register','Narrator apostasy formula opens the judge-cycle theorem; nations-left/testing language continues across 2:23 into the named nations, intermarriage, and service coda at 3:6','Preserve 2:11-23 / 3:1-6 as a live split; repeated nations-left and testing purpose support the larger parent'),
('3.7','3.11','Othniel cycle','deliverer_cycle','Apostasy formula opens oppression, cry, raised deliverer, victory, rest, and death closure at 3:11',None),
('3.12','3.30','Ehud cycle','deliverer_cycle','Again-did-evil opens oppression and cry; tribute, covert killing, delayed discovery, escape, muster, battle, and rest close at 3:30','Preserve assassination/escape/battle child seams; difficult Hebrew at 3:15,19,22,24 does not justify detaching setup from victory'),
('3.31','3.31','Shamgar annal','minor_judge_annal','After-him formula introduces and completes a compact named deliverance notice',None),
('4.1','4.24','Deborah-Barak-Sisera-Jael prose cycle','deliverer_cycle_narrative','Renewed apostasy after Ehud opens oppression and Deborah-Barak commission; battle, Sisera flight, Jael reversal, and Jabin summary close at 4:24','Preserve 4:1-10 / 4:11-16 / 4:17-24 child scenes; retain the complete prose deliverance cycle'),
('5.1','5.31','Song of Deborah and Barak','archaic_victory_song','Explicit sang-on-that-day formula opens a framed poem; praise summons, theophany, muster, battle, Jael/Sisera panels, enemy/lover conclusion, and rest close at 5:31','Archaic Hebrew and disputed strophes at 5:5,11,18,23,27 remain appeals; do not promote speculative children or detach the rest notice'),
('6.1','6.10','Midian oppression cry and prophetic indictment','oppression_and_prophetic_oracle','Cycle formula opens Midianite devastation and cry; a newly sent prophet rehearses deliverance, accusation, and not-listened closure at 6:10','Preserve 6:1-6 / 6:7-10 as oppression versus oracle; the cry directly occasions the answer'),
('6.11','6.24','Gideon commission sign and altar','commission_and_sign_narrative','Messenger arrival under the Ophrah oak opens commission, objection, sign, fear, assurance, and altar/place notice through 6:24','Messenger/YHWH speaker shifts are unresolved; preserve possible 6:11-21 / 6:22-24 seam without identity ruling'),
('6.25','6.32','Baal altar destruction and Jerubbaal naming','commission_execution_confrontation','That-same-night command opens altar destruction; city accusation, Joash response, and Jerubbaal naming close at 6:32',None),
('6.33','6.40','Enemy muster Spirit summons and fleece signs','muster_and_sign_sequence','Enemy assembly opens Spirit-clothing and tribal summons; paired fleece tests close at 6:40','Preserve 6:33-35 / 6:36-40 as muster versus signs, but retain the linked pre-battle preparation'),
('7.1','7.8','Gideon force reduced to three hundred','army_selection_procedure','Jerubbaal and the people encamp; two reductions, water test, dismissal, and retained three hundred close at 7:8',None),
('7.9','7.15','Camp dream and Gideon strengthened','reconnaissance_and_sign_scene','That-night descent command opens overheard dream and interpretation; Gideon worships and returns with a deliverance summons at 7:15','Hebrew primary joined through 7:22; retain 7:9-15 / 7:16-25 as the literary alternative while recording the wider battle dependency'),
('7.16','7.25','Trumpet-torch rout and Oreb-Zeeb pursuit','battle_and_pursuit','Division into companies opens instructions and enacted trumpet-torch assault; rout, wider muster, pursuit, and Oreb/Zeeb trophies close at 7:25','Hebrew primary preferred 7:9-22 + 7:23-8:3; exact pursuit/Ephraim seam remains unresolved'),
('8.1','8.3','Ephraim complaint defused','dispute_dialogue','Ephraim direct complaint opens a compact rebuke-and-conciliation exchange whose anger abates at 8:3','Hebrew primary joins 7:23-8:3; retain that cross-chapter pursuit/dispute alternative'),
('8.4','8.21','Transjordan pursuit reprisals and kings execution','pursuit_and_reckoning_narrative','Jordan crossing by the exhausted three hundred opens requests, refusals, capture, return reprisals, kin inquiry, and kings execution at 8:21','Preserve 8:4-12 / 8:13-21 as pursuit-capture versus return-reckoning; larger unit retains threat and fulfillment'),
('8.22','8.28','Rule offer ephod snare and rest','rule_and_cult_aftermath','Israel offers hereditary rule; refusal, gold request, ephod/snare notice, subjugation, and rest close at 8:28','Rule vocabulary, ephod function, and narrator evaluation are held; no kingship or cult theology ruling'),
('8.29','9.6','Gideon household aftermath and Abimelech seizure','household_to_rule_transition','Jerubbaal returns home; household, seventy sons, Abimelech naming, death, relapse, and failed loyalty supply the actors and covenant setting immediately exploited by conspiracy, fratricide, and acclamation at 9:6','Preserve 8:29-35 / 9:1-6 as the death/apostasy versus conspiracy split; larger LOW unit keeps explicit causal setup'),
('9.7','9.21','Jotham tree fable application and curse','framed_fable_and_application','Jotham public summons opens the tree fable; direct application, conditional curse, and flight close at 9:21','Do not isolate 9:8-15; bramble wordplay and conditional speech require frame and application'),
('9.22','9.57','Outworking of Jotham curse','conflict_cycle_with_narrator_fulfillment','Three-year rule and narrator retribution program open factional conflict; Gaal, Shechem, tower, Thebez, Abimelech death, and explicit repayment/Jotham closure end at 9:57','Preserve child seams at 9:25/26, 9:41/42, and 9:49/50; retain the complete narrated fulfillment parent'),
('10.1','10.5','Tola and Jair annals','minor_judge_annals','After-Abimelech introduces Tola; paired tenure/death/burial notices close with Jair at 10:5',None),
('10.6','10.16','Many-gods apostasy confession and removal','apostasy_oppression_and_response','Again-did-evil opens widened service and oppression; cry, divine rebuttal, confession, removal of gods, and grief close at 10:16','The wording of divine response and grief remains evidence-only; no theology ruling'),
('10.17','11.11','Ammon crisis and Jephthah elevation','leadership_crisis_and_installation','Ammon and Israel assemble and ask who will lead; Jephthah origin, elders negotiation, witness, installation, and Mizpah speech answer that question at 11:11','Preserve 10:17-18 / 11:1-11; larger cross-chapter unit retains question and negotiated answer'),
('11.12','11.28','Jephthah-Ammon diplomatic exchange','diplomatic_historical_argument','Jephthah sends messengers; claim, counter-rehearsal, appeal, and refusal close at 11:28','Chemosh reference and historical argument are not theological or historical-harmonization authority'),
('11.29','11.40','Jephthah vow victory daughter and custom','vow_consequence_narrative','Spirit movement opens vow and campaign; victory, daughter arrival, lament, vow fulfillment, and annual custom close at 11:40','Preserve 11:29-33 / 11:34-40; vow syntax and daughter fate remain unresolved for qualified Hebrew/legal/ancient-context review'),
('12.1','12.7','Ephraim-Gilead conflict and Jephthah closure','intra_israel_conflict_and_death_notice','Ephraim assembles and accuses; dispute, battle, dialect test, casualty notice, tenure, death, and burial close at 12:7','Shibboleth phonology, casualty figure, and burial wording remain held'),
('12.8','12.15','Ibzan Elon and Abdon annals','minor_judge_annals','After-him formula introduces three paired tenure/death/burial notices ending with Abdon at 12:15',None),
('13.1','13.25','Samson annunciation birth and Spirit stirring','annunciation_and_birth_cycle','Cycle formula opens Philistine oppression; repeated messenger appearances, maternal/Nazirite charge, prayer, sign, recognition, birth, blessing, and Spirit stirring close at 13:25','Preserve 13:1-7 / 13:8-23 / 13:24-25; messenger identity and Nazirite terminology remain unresolved'),
('14.1','15.8','Timnah marriage riddle and retaliation chain','marriage_riddle_and_retaliation_cycle','Samson descends to Timnah; lion/honey, feast-riddle, coercion, answer, Ashkelon reprisal, wife transfer, crop burning, counter-burning, and further retaliation close at Etam in 15:8','Preserve 14:1-9 / 14:10-20 / 15:1-8; cross-chapter causal links support larger LOW parent and wordplay stays held'),
('15.9','15.20','Judah handover Lehi victory and prayer','conflict_victory_poem_and_prayer','Philistine encampment opens Judah negotiation and binding; Spirit-enabled victory, jawbone poem/place-name, thirst prayer, water answer, and judge notice close at 15:20','Jawbone/Lehi wordplay and embedded poem resist narrower lexical segmentation'),
('16.1','16.3','Gaza ambush and gate escape','escape_vignette','Gaza arrival and ambush plan open; midnight gate removal and Hebron-facing transport close at 16:3',None),
('16.4','16.22','Delilah tests disclosure and capture','betrayal_and_capture_sequence','Afterward love notice opens four escalating tests; disclosure, shaving, unrecognized departure, capture, and hair-regrowth reversal signal close at 16:22','Preserve false-test children and 16:18-22 climax; hair, Nazirite status, strength, and divine departure remain narrated evidence, not mechanism'),
('16.23','16.31','Dagon feast Samson death and burial','final_prayer_death_and_burial','Philistine lords gather for sacrifice; mockery, final prayer, temple collapse, death comparison, burial, and judge notice close at 16:31','No divine-war, morality, or Dagon theology is decided by this boundary'),
('17.1','17.13','Micah shrine and Levite hire','household_cult_and_priest_narrative','Micah introduction opens silver/image/shrine sequence; no-king refrain, Levite arrival, hire/consecration, and prosper expectation close at 17:13','Preserve 17:1-6 / 17:7-13; cult/priest vocabulary and narrator irony remain held'),
('18.1','18.10','Danite inheritance scouts and Laish report','migration_reconnaissance','No-king/inheritance problem opens scouts, Micah-priest encounter/oracle, Laish reconnaissance, and return exhortation at 18:10','Relation to Judg.1 Dan pressure and Joshua allotment is evidence only'),
('18.11','18.26','Danite migration cult theft and Micah pursuit','migration_and_seizure_narrative','Six-hundred migration force departs; shrine theft, priest transfer, Micah pursuit, protest, threat, and withdrawal close at 18:26','Preserve 18:11-20 / 18:21-26; ephod/teraphim/priest terms remain evidence-only'),
('18.27','18.31','Laish destroyed Dan founded and shrine installed','conquest_and_cult_epilogue','Taken cult and priest lead into Laish destruction; Dan naming, image/priestly line, captivity notice, and Shiloh contrast close at 18:31','Moses/Manasseh suspended-nun witness pressure and captivity chronology remain unresolved; no preferred reading'),
('19.1','19.30','Gibeah atrocity causal chain and summons','social_collapse_narrative','No-king frame opens concubine rupture and return; hospitality delay, refusal of Jebus, Gibeah lodging, assault, threshold, dismemberment, and national summons close at 19:30','Preserve 19:1-10 / 19:11-21 / 19:22-30; larger LOW unit retains accumulating cause and narrator perspective; 19:2 and death timing remain textual holds'),
('20.1','20.17','National assembly testimony refusal and musters','assembly_and_conflict_setup','All-Israel assembly answers the summons; testimony, collective decision, Benjamin demand/refusal, and opposing musters close at 20:17','Levite report must not replace narrator perspective; totals and legal-social claims remain held'),
('20.18','20.28','First two defeats and intensified inquiry','battle_inquiry_sequence','First inquiry echoes the book opening; two defeats, repeated seeking, lament, fast, offerings, ark/Phinehas notice, and third promise close at 20:28','Preserve each attempt as a child but retain progressive inquiry; chronology and Bethel/house-of-God wording remain unresolved'),
('20.29','20.48','Third battle Benjamin collapse and destruction','battle_and_aftermath','Ambush placement opens the third battle; feigned flight, reversal, casualty notices, six-hundred remnant, and city destruction close at 20:48','Battle totals and moral/providential conclusions remain deferred'),
('21.1','21.15','Oath crisis and Jabesh-Gilead first remedy','oath_crisis_and_failed_remedy','Mizpah oath opens lament and tribe-loss crisis; missing-assembly inquiry, Jabesh destruction, survivor provision, peace, and renewed insufficiency close at 21:15','Preserve 21:1-14 / 21:15-25; verse 15 is a bridge and the exact seam remains appealed'),
('21.16','21.25','Shiloh seizure second remedy and final refrain','oath_remedy_and_book_closure','Elders ask how to provide remaining wives; Shiloh plan, seizure, tribal return, and no-king/right-in-own-eyes refrain close at 21:25','Oath logic, executions, captive women, and refrain interpretation require moral-legal/canonical human review; description is not prescription')]
LOW={1,4,6,8,10,11,12,13,15,17,18,19,20,21,22,23,24,26,27,28,29,30,32,33,34,36,38,40,41,42,43,44,45,46,47}
out=[]
for i,(a,b,title,form,marker,hold) in enumerate(ROWS,1):
 span=f'Judg.{a}-Judg.{b}'; did=f'M7_sol-Judg-{i:03d}'; low=i in LOW
 rejected=(f'Preserved competing boundary/evidence alternative for {span}: {hold}.' if hold else f'Rejected expansion beyond Judg.{b} because the next unit opens with a concrete new speaker, scene, form, register, or formula; no chapter number is used as authority.')
 row={'model_id':'M7_sol','book':'Judg','span':span,'chunk_index_in_book':i,'working_title':title,'literature_type_guess':form,'boundary_evidence_refs':[f'direct_read:eng-web:{span}',f'direct_read:oshb:Judg.xml#{span}',f'direct_read:uxlc:Judg.xml#{span}','book_strategy/Judg.md','reviews/Judg/primary_hebrew_v1.json','reviews/Judg/primary_literary_v1.json','reviews/Judg/canonical_premortem_v1.json','reviews/Judg/peer_crosscheck_v1.json','reviews/Judg/boss_ruling_v1.json','reviews/Judg/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['direct_hebrew_wording_considered','source_metadata_corrob_only','roots_are_not_meaning','original_language_is_not_boundary_authority'],'wj_or_red_letter_considered':False,'frontier_flag_considered':True,'confidence':'low' if low else 'medium','decision_id':did,'literary_form':form,'deciding_marker_or_seam':marker+'.','boundary_rationale':f'Prefer the complete {form} unit {span}. {marker}.','rejected_alternative':rejected,'defensible_basis':f'{did}: {marker}. This exact scene/speech/form/register signal—not chapter numbering, a lexical root, or a canonical parallel—supports the candidate boundary.','review_revision':1,'review_status':'final_deferred_appeal' if low else 'candidate_review_complete','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'] if low else ['external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[marker+'.'],'original_language_translation_holds':[hold if hold else f'Hebrew wording and source metadata for {title} are corroborating discourse evidence only; no root inference, textual preference, chronology, or theological ruling is made.'],'cross_reference_holds':['Internal-Bible relations are recorded separately and do not authorize this local boundary or harmonize accounts.'],'red_team_premortem_holds':[hold if hold else f'Expansion would mix {title} with the next governing function; any narrower child requires role-specific evidence.'],'working_title_is_boundary_authority':False,'working_title_origin':'independent_judges_mesh_reconciliation_v1','candidate_only':True,'review_evidence_summary':marker+'. Evidence-only; no theology, historicity, canon, authorship, chronology, morality, or preferred reading is selected.','red_team_questions':[f'Does the seam after Judg.{b} survive removal of headings and chapter numbers?',f'Does the preserved alternative better retain the governing scene, form, or causal relation: {rejected}'],'hard_passage_forecast':[hold if hold else f'Check Judg.{b} against the next direct Hebrew/WEB opening; source metadata remains corroborating only.']}
 if low: row.update(candidate_hold_state='deferred_human_or_external_ai',candidate_hold_basis='preserved_appeal')
 out.append(row)
assert len(out)==47
OUT.parent.mkdir(parents=True,exist_ok=True)
OUT.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n')
print(json.dumps({'rows':len(out),'low':sum(x['confidence']=='low' for x in out)}))
