import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
OUT=ROOT/'book_chunks'/'Josh'/'chunks.jsonl'
# start,end,title,form,specific marker,optional preserved alternative/hold
ROWS=[
('1.1','1.9','Divine succession commission','commission_address','Post-Moses setting opens a divine speech to Joshua; repeated strong-and-courageous imperatives and the presence promise close at 1:9',None),
('1.10','1.18','Mobilization and eastern tribes pledge','mobilization_and_response','Joshua turns to the officers at 1:10, then reminds the eastern tribes; their explicit loyalty response and sanction close at 1:18','Preserve 1:10-11 / 1:12-18 as the officers-order and eastern-tribes-response split; retain the larger mobilization unit'),
('2.1','2.24','Spies and Rahab mission','espionage_oath_narrative','Secret sending opens the mission; concealment, confession, oath, sign, escape, and return report reach closure at 2:24','Preserve subscene seams at 2:8 and 2:22, but retain the complete mission as the larger narrative'),
('3.1','5.1','Jordan crossing memorial and nations reaction','crossing_memorial_cycle','Camp movement and ark instruction open the crossing; stopped waters, twelve stones, child-interpretation, Gilgal setting, and the kings reaction at 5:1 close the cycle','Competing seams at 3:6/7, 3:13/14, 4:14/15, and 4:24/5:1 remain live; retain the larger crossing-memorial-reaction cycle'),
('5.2','5.12','Circumcision Passover and manna cessation','covenant_preparation_ritual_sequence','The at-that-time circumcision command opens covenant preparation; healing, Gilgal naming, Passover, land produce, and manna cessation close at 5:12','Preserve 5:2-9 / 5:10-12 as circumcision versus Passover/produce, but retain the larger post-crossing preparation sequence'),
('5.13','6.5','Commander encounter and Jericho instruction','numinous_encounter_and_battle_instruction','A new perception and identity question open the commander encounter; holy-ground command, Jericho status parenthesis, and sevenfold conquest instruction close at 6:5','Preserve a seam at 5:15/6:1 or 6:1/2; the larger cross-chapter unit does not identify the commander with the 6:2 speaker and remains LOW'),
('6.6','6.27','Jericho procession fall rescue and closure','battle_ritual_episode','Joshua transmits the procession order at 6:6; execution, seventh-day climax, Rahab rescue, destruction, curse, and fame formula close at 6:27',None),
('7.1','7.26','Achan trespass defeat inquiry and judgment','trespass_restoration_narrative','The adversative trespass disclosure at 7:1 causally opens Ai defeat; lament, diagnosis, lot inquiry, confession, sanction, abated anger, and Achor place-name close at 7:26','Preserve splits at 7:5/6 and 7:15/16, but retain defeat, inquiry, and consequence as one causally dependent episode'),
('8.1','8.29','Renewed Ai campaign','battle_episode','Fresh divine commission reopens Ai; ambush, feigned flight, reversal, defeat, and the king burial/place notice close at 8:29',None),
('8.30','8.35','Ebal altar and covenant reading','ritual_assembly','Scene relocation to Ebal opens altar construction; inscription, blessing/curse placement, and complete Torah reading close at 8:35','Ebal/Gerizim witness pressure is held without choosing a reading; the ritual remains one unit'),
('9.1','9.27','Coalition contrast and Gibeonite treaty','diplomatic_treaty_narrative','Kings hearing and coalition contrast open at 9:1; Gibeonite disguise, inquiry, oath, discovery, complaint, ruling, and etiological disposition close at 9:27','Preserve 9:1-2 bridge and subscene seams at 9:13/14, but retain the whole contrasting-response and treaty episode'),
('10.1','10.15','Gibeon rescue with sun and moon poem','battle_report_with_embedded_poetry','Five-king threat and Gibeonite appeal open rescue; divine assurance, battle, quoted poem, Jashar notice, prose interpretation, and return formula close at 10:15','Do not isolate 10:12-14; poetic syntax, temporal language, and the Jashar notice remain translation/textual holds inside the larger battle report'),
('10.16','10.27','Five kings captured and executed','battle_aftermath_scene','The cave report opens pursuit and confinement; exposure, symbolic trampling, execution, and stone memorial close at 10:27',None),
('10.28','10.43','Southern campaign annal and return','campaign_register','Makkedah opens the repeated city-and-king conquest formula; territorial summary and return at 10:43 close the southern campaign',None),
('11.1','11.15','Northern coalition campaign','battle_episode','Jabin sends to the northern coalition at 11:1; Merom battle, Hazor climax, and obedience summary close at 11:15',None),
('11.16','11.23','Whole-campaign summary and land rest','conquest_summary','So-Joshua-took-all-that-land opens regional summary; Anakim notice, inheritance statement, and land-rest formula close at 11:23',None),
('12.1','12.6','Moses Transjordan kings register','victory_register','These-are-the-kings heading opens the east-Jordan register; territorial scope and Moses allocation close at 12:6',None),
('12.7','12.24','Joshua western kings register','victory_register','New west-Jordan scope opens at 12:7; repeated one-king formula and total thirty-one close at 12:24',None),
('13.1','13.7','Remaining-land commission','divine_commission_and_territory_inventory','Joshua age formula and divine speech open the remaining-land inventory; division mandate closes at 13:7',None),
('13.8','13.14','Transjordan overview and Levi exception','allocation_framework','The eastern tribes resumption opens at 13:8; remaining-peoples notices and Levi exception close at 13:14','Preserve inner notice seams at 13:13 and 13:14; retain the governing Transjordan overview'),
('13.15','13.23','Reuben allocation','tribal_boundary_city_register','Reuben tribal allotment heading opens its boundary and cities; inheritance closure ends at 13:23',None),
('13.24','13.28','Gad allocation','tribal_boundary_city_register','Gad tribal heading opens its boundary and cities; inheritance closure ends at 13:28',None),
('13.29','13.33','Half-Manasseh allocation and Transjordan closure','tribal_register_and_summary','Half-Manasseh heading opens family territories; Moab distribution summary and repeated Levi exception close at 13:33','Preserve 13:29-31 / 13:32-33 as tribal register versus Transjordan summary; retain the larger closure'),
('14.1','14.5','West-Jordan allotment procedure','administrative_introduction','These-are-the-inheritances heading names administrators and lot procedure; tribe/Levi clarification and compliance close at 14:5',None),
('14.6','14.15','Caleb petition and Hebron grant','petition_ruling_narrative','Judahites and Caleb approach at 14:6; retrospective claim, direct request, blessing, grant, and rest closure end at 14:15',None),
('15.1','15.12','Judah outer boundary','geographical_boundary_register','Judah lot heading opens south/east/north/west border progression; border summary closes at 15:12',None),
('15.13','15.19','Caleb Othniel and Achsah springs','embedded_allotment_narrative','Personal grant opens conquest and marriage-offer scene; Achsah petition and springs grant close at 15:19',None),
('15.20','15.63','Judah city register and Jerusalem coda','regional_city_register','Judah inheritance heading opens southern, lowland, hill, and wilderness town subregisters; Jerusalem non-dispossession closes at 15:63','Regional splits at 15:32, 15:47, and 15:60 remain appeals; retain the whole Judah city register rather than splitting by length'),
('16.1','16.4','Joseph common allotment frame','boundary_introduction','Joseph lot heading opens the common territorial route; Manasseh/Ephraim inheritance transition closes at 16:4',None),
('16.5','16.10','Ephraim inheritance','tribal_boundary_register','Ephraim heading opens border circuit; embedded towns and Gezer non-dispossession close at 16:10',None),
('17.1','17.13','Manasseh allotment Zelophehad ruling and cities','tribal_allotment_register','Manasseh heading opens clan allocation; daughters ruling, ten-part summary, border/cities, and non-dispossession coda close at 17:13','Preserve 17:1-6 / 17:7-13 as clan/legal allocation versus border register; retain the larger Manasseh allotment'),
('17.14','17.18','Joseph tribes petition and ruling','petition_ruling_dialogue','Joseph tribes direct complaint opens at 17:14; forest proposal, objection, and strengthened final ruling close at 17:18',None),
('18.1','18.10','Shiloh assembly survey and lots','administrative_procedure_narrative','Sanctuary relocation and seven-tribe problem open; survey instruction, execution, and lots before Yahweh close at 18:10',None),
('18.11','18.28','Benjamin boundary and cities','tribal_allotment_register','Benjamin lot heading opens border circuit; city subregister totals and inheritance closure end at 18:28','Preserve 18:11-20 / 18:21-28 as boundary versus city register; retain the larger tribal allotment'),
('19.1','19.9','Simeon allotment','tribal_city_register','Second-lot heading opens Simeon towns; subtotals and Judah-overlap explanation close at 19:9',None),
('19.10','19.16','Zebulun allotment','tribal_boundary_city_register','Third-lot heading opens the border circuit; town subtotal and inheritance closure end at 19:16',None),
('19.17','19.23','Issachar allotment','tribal_boundary_city_register','Fourth-lot heading opens town/border list; subtotal and inheritance closure end at 19:23',None),
('19.24','19.31','Asher allotment','tribal_boundary_city_register','Fifth-lot heading opens the border circuit; subtotal and inheritance closure end at 19:31',None),
('19.32','19.39','Naphtali allotment','tribal_boundary_city_register','Sixth-lot heading opens border and fortified-city list; subtotal and closure end at 19:39',None),
('19.40','19.48','Dan allotment and Leshem notice','tribal_register_with_conquest_notice','Seventh-lot heading opens city list; Danite expansion and renamed Leshem close the inheritance at 19:48',None),
('19.49','19.51','Joshua grant and allotment closure','administrative_epilogue','Finished-distributing formula opens Joshua personal grant; named administrators and Shiloh closure end at 19:51',None),
('20.1','20.9','Refuge-city procedure and designation','legal_administrative_procedure','Divine speech opens purpose, gate hearing, asylum, trial, and tenure rules; designated west/east cities and eligibility summary close at 20:9','Preserve 20:1-6 / 20:7-9 as instruction versus execution, but retain the complete administrative procedure'),
('21.1','21.8','Levitical petition and clan allocation overview','administrative_procedure','Levitical heads approach and cite the command; compliance, clan totals, and distribution overview close at 21:8',None),
('21.9','21.19','Aaronide cities','levitical_city_register','Aaron/Kohath allocation heading opens priestly city list; thirteen-city subtotal closes at 21:19',None),
('21.20','21.26','Remaining Kohathite cities','levitical_city_register','Remaining Kohathite heading opens tribal groups; ten-city subtotal closes at 21:26',None),
('21.27','21.33','Gershonite cities','levitical_city_register','Gershon heading opens tribal-source formulae; thirteen-city subtotal closes at 21:33',None),
('21.34','21.42','Merarite cities and total','levitical_city_register_closure','Merari heading opens tribal groups; twelve-city subtotal, forty-eight-city aggregate, and pasture formula close at 21:42','Preserve 21:34-40 / 21:41-42 as Merari list versus grand total; retain the larger register closure'),
('21.43','21.45','Land rest and fulfilled-word summary','narrative_macro_summary','Repeated Yahweh-gave statements open land/rest/victory summary; nothing-failed formula closes at 21:45',None),
('22.1','22.9','Eastern tribes released and return','dismissal_scene','Joshua summons the eastern tribes; commendation, exhortation, blessing, wealth instruction, and departure close at 22:9',None),
('22.10','22.34','Altar dispute accusation defense and reconciliation','dispute_dialogue_narrative','Altar construction and Israel war assembly open the dispute; embassy accusation, complete eastern defense, acceptance, report, abandoned war, and witness notice close at 22:34','Preserve speech seams at 22:20/21 and 22:29/30, but retain the dependency-bearing accusation-defense-reconciliation scene; altar-name wording remains held'),
('23.1','23.16','Joshua farewell address','farewell_address','Aged-rest setting and leader summons frame Joshua speech; retrospective, fidelity charge, apostasy warning, and land-loss peroration close at 23:16','Preserve rhetorical movements at 23:8/9 and 23:13/14, but retain the single framed farewell speech'),
('24.1','24.28','Shechem historical rehearsal choice and covenant','covenant_renewal_ceremony','Full assembly and prophetic messenger formula open divine historical rehearsal; choice dialogue, counterwarning, pledge, covenant/statute, writing, stone witness, and dismissal close at 24:28','Preserve seams at 24:13/14, 24:15/16, and 24:24/25; retain the whole ceremony under unresolved-to-larger'),
('24.29','24.33','Joshua Joseph and Eleazar burial epilogue','multi_notice_epilogue','After-these-things opens Joshua death/burial; service-generation, Joseph burial, and Eleazar burial close the book at 24:33','Three notice children remain possible, but retain the compact coordinated book epilogue')]
LOW={2,3,4,5,6,8,10,11,12,20,23,28,31,34,42,47,50,51,52,53}
def ref(v): return 'Josh.'+v
out=[]
for i,(a,b,title,form,marker,hold) in enumerate(ROWS,1):
 span=f'{ref(a)}-{ref(b)}'; low=i in LOW; did=f'M7_sol-Josh-{i:03d}'
 next_title=ROWS[i][2] if i<len(ROWS) else 'the canonical book end'
 rejected=(f'Preserved competing boundary/evidence alternative for {span}: {hold}.' if hold else f'Rejected expansion beyond {ref(b)} into “{next_title}” because the governing speaker, scene, register, ritual, or summary function changes there; the three blind proposals converge on this exact span.')
 row={'model_id':'M7_sol','book':'Josh','span':span,'chunk_index_in_book':i,'working_title':title,'literature_type_guess':form,'boundary_evidence_refs':['reviews/Josh/primary_hebrew_v1.json','reviews/Josh/primary_literary_v1.json','reviews/Josh/canonical_premortem_v1.json','reviews/Josh/peer_crosscheck_v1.json','reviews/Josh/boss_ruling_v1.json','reviews/Josh/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['evidence_only','roots_are_not_meaning','original_language_is_not_boundary_authority'],'wj_or_red_letter_considered':False,'frontier_flag_considered':True,'confidence':'low' if low else 'medium','decision_id':did,'literary_form':form,'deciding_marker_or_seam':marker+'.','boundary_rationale':f'Prefer the complete {form} unit {span}. {marker}.','rejected_alternative':rejected,'defensible_basis':f'{did}: {marker}. This exact scene/speech/register signal—not chapter numbering, a lexical root, or a canonical parallel—supports the candidate boundary.','review_revision':1,'review_status':'final_deferred_appeal' if low else 'candidate_review_complete','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'] if low else ['external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[marker+'.'],'original_language_translation_holds':[hold if hold else f'Hebrew wording and source metadata for “{title}” are corroborating discourse evidence only; no root inference, textual preference, chronology, or theological ruling is made.'],'cross_reference_holds':['Internal-Bible relations are recorded separately and do not authorize this local boundary or harmonize parallel accounts.'],'red_team_premortem_holds':[hold if hold else f'Expansion would mix “{title}” with the next governing function; any narrower child requires a role-specific marker and remains non-authorizing.'],'working_title_is_boundary_authority':False,'working_title_origin':'independent_joshua_mesh_reconciliation_v1','candidate_only':True,'review_evidence_summary':marker+'. Evidence-only; no theology, historicity, canon, authorship, chronology, or preferred reading is selected.'}
 if low: row.update(candidate_hold_state='deferred_human_or_external_ai',candidate_hold_basis='preserved_appeal')
 out.append(row)
assert len(out)==53
OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n')
print(json.dumps({'rows':len(out),'low':sum(x['confidence']=='low' for x in out)}))