from __future__ import annotations
import hashlib, json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "book_chunks" / "1Chr" / "chunks.jsonl"

# Larger-coherence synthesis of three blind exact-coverage primaries.
ROWS = [
("1.1","1.4","Primeval ancestry to Noah and sons","ancestry_spine","terse ancestry chain closes with Noah's three sons"),
("1.5","1.23","Nations from Japheth Ham and Shem","branched_ancestry_register","repeated sons-of heads govern three national branches"),
("1.24","1.27","Shem to Abram ancestry funnel","compressed_ancestry_chain","Shem restarts a narrowed chain that closes at Abram"),
("1.28","1.34","Abraham branches and Isaac Israel transition","branched_ancestry_register","Abraham head opens collateral lines and closes at Isaac's Esau-Israel pair"),
("1.35","1.42","Esau and Seir clan register","clan_register","Esau descendants lead into a complete Seir collateral register"),
("1.43","1.54","Edomite kings and chiefs","royal_and_chief_register","kingship succession changes to chief roster and closes Edom"),
("2.1","2.2","Sons of Israel tribal frame","tribal_index","Israel's twelve sons form the governing index"),
("2.3","2.17","Judah through Perez to David household","ancestry_funnel","Judah branches narrow through Ram to Jesse David and sibling closure"),
("2.18","2.24","Caleb Hezron and Machir branch","branched_genealogy","Caleb and Hezron family notices form one difficult linked branch"),
("2.25","2.41","Jerahmeel branch","genealogical_register","Jerahmeel head governs nested descent through Elishama"),
("2.42","2.55","Calebite clans settlements and scribal families","clan_settlement_register","Calebite heads shift into settlement and occupational-clan closure"),
("3.1","3.9","David sons in Hebron and Jerusalem","royal_household_register","David's children are organized by royal location"),
("3.10","3.16","Royal succession through exile","royal_descent_chain","repeated son succession reaches exile-era heirs"),
("3.17","3.24","Jeconiah post-captivity descendants","postexilic_descent_register","Jeconiah head governs the post-captivity line"),
("4.1","4.23","Judah clan household occupation and Jabez supplement","tribal_supplement_register","Judah supplement contains clan craft settlement and embedded prayer material"),
("4.24","4.33","Simeon ancestry and settlements","tribal_settlement_register","Simeon head governs ancestry and territorial list"),
("4.34","4.43","Simeonite leaders expansion and conquest","settlement_expansion_narrative","named leaders open two connected pasture and conquest movements"),
("5.1","5.10","Reuben ancestry territory and war","tribal_register_with_war_notice","Reuben frame carries birthright genealogy territory and Hagrite result"),
("5.11","5.17","Gad ancestry territory and enrollment","tribal_register","Gad head governs lineage territory and dated registration"),
("5.18","5.22","Joint eastern tribes battle","military_muster_and_outcome","collective muster proceeds through prayer battle spoil and settlement"),
("5.23","5.26","Half Manasseh and eastern exile closure","tribal_register_and_exile_notice","half-Manasseh reset leads into the eastern tribes' exile closure"),
("6.1","6.15","Levi Aaron priestly descent through exile","priestly_descent_chain","Levi-to-Aaron succession closes at exile under a WEB-MT offset"),
("6.16","6.30","Levitical descent by three houses","levitical_clan_register","Gershom Kohath and Merari form the three-house descent register"),
("6.31","6.48","Appointed singers and ancestry lines","cultic_service_register","Davidic appointment governs Heman Asaph Ethan lines and general service closure"),
("6.49","6.53","Aaronide sacrificial office and line","priestly_office_register","altar service marks a new Aaronide function and descent"),
("6.54","6.60","Aaronide settlements and cities","city_allocation_register","Aaronic dwelling allocation forms the first city panel"),
("6.61","6.81","Remaining Levitical cities by clan","city_allocation_register","remaining Kohath Gershom and Merari allotments share one distribution function"),
("7.1","7.5","Issachar genealogy and muster","military_genealogy","Issachar descent culminates in military totals"),
("7.6","7.12","Benjamin military genealogy","military_genealogy","Benjamin house heads and muster formula govern the register"),
("7.13","7.13","Naphtali compact tribal formula","compact_tribal_register","Naphtali receives a self-contained one-verse tribal formula"),
("7.14","7.19","Manasseh genealogy","dense_kinship_register","Manasseh head governs compressed gender and kinship formulas"),
("7.20","7.29","Ephraim genealogy calamity and settlements","genealogy_with_embedded_narrative","Ephraim descent contains mourning birth and territorial closure"),
("7.30","7.40","Asher genealogy chiefs and muster","military_genealogy","Asher descent closes with chiefs and military total"),
("8.1","8.28","Benjamin clans and settlements","tribal_settlement_register","Benjaminite households and locations form a tribe-wide register"),
("8.29","8.40","Gibeon to Saul household","royal_ancestry_register","Gibeon household narrows to Saul Jonathan and later descendants"),
("9.1","9.9","Exile frame and Jerusalem lay resettlement","resettlement_register","exile transition resets the list to Judah Benjamin and other lay residents"),
("9.10","9.13","Priestly residents","office_register","priestly office head governs named residents and capacity"),
("9.14","9.16","Levitical residents","office_register","Levite head governs non-gatekeeping residents"),
("9.17","9.27","Gatekeepers watches and duties","gatekeeping_office_register","gatekeeper ancestry historical frame rotations and deployment form one office unit"),
("9.28","9.34","Sanctuary supplies preparation and singers","cultic_service_register","vessel food spice and continuous-song duties share service administration"),
("9.35","9.44","Repeated Gibeon to Saul ancestry","royal_ancestry_bridge","repeated genealogy remains a local form and bridges toward Saul's narrative"),
("10.1","10.14","Saul final battle death burial and closure","terminal_battle_narrative","battle and deaths proceed through body recovery burial and narrated closure"),
("11.1","11.9","David accession and Jerusalem capture","accession_and_city_capture","all-Israel covenant and anointing lead through capture building and greatness"),
("11.10","11.25","Chief warriors and exploits","elite_warrior_exploit_register","chief-warrior frame governs the premier exploits"),
("11.26","11.47","Extended warrior roster","warrior_register","form shifts from narrated exploits to extended names"),
("12.1","12.22","Successive groups rally to David","supporter_arrival_register","repeated arrival weapon speech and acceptance panels accumulate toward David"),
("12.23","12.40","Hebron tribal muster and feast","military_muster_and_assembly_outcome","tribal enumeration culminates in unified intent feast provision and joy"),
("13.1","13.14","First ark transport crisis and outcome","transport_crisis_narrative","consultation and journey lead through Uzza crisis fear diversion and three-month outcome"),
("14.1","14.7","David house recognition and family","royal_establishment_summary","house recognition and household expansion form a domestic royal panel"),
("14.8","14.17","Paired Philistine battles","paired_battle_narrative","two inquiry-command-victory cycles close with fame"),
("15.1","16.6","Corrected ark transport installation and ministry","cross_chapter_transport_resolution","preparation personnel procession arrival offerings and ministers complete the successful movement"),
("16.7","16.36","Delivered thanksgiving and communal response","liturgical_composition","explicit delivery opens a sustained thanksgiving that closes with Amen and praise"),
("16.37","16.43","Continuing worship assignments and dismissal","cultic_administration_closure","ark and Gibeon assignments lead to dismissal and household return"),
("17.1","17.27","Nathan oracle and David prayer","oracle_response_unit","house proposal and delivered oracle receive David's answering prayer"),
("18.1","18.13","Conquests tribute and dedicated goods","campaign_result_complex","campaign notices share tribute dedication garrison and victory closures"),
("18.14","18.17","Royal administration roster","administrative_summary","justice statement introduces the royal officers"),
("19.1","19.5","Rejected kindness humiliation and response","diplomatic_insult_scene","succession and embassy lead through suspicion humiliation and recovery instruction"),
("19.6","19.19","Ammon Aram war and peace","two_stage_war_narrative","mobilization leads through two battles flight submission and peace"),
("20.1","20.3","Rabbah campaign and return","campaign_completion","seasonal siege closes with conquest crown plunder and return"),
("20.4","20.8","Philistine giant-war notices","repeated_combat_register","three combat reports close collectively"),
("21.1","21.7","Census command report and displeasure","census_initiation","instigation objection execution count and verdict form the initiating action"),
("21.8","21.17","Confession choices plague and intercession","judgment_and_intercession_scene","confession opens options plague angelic halt and intercession"),
("21.18","21.27","Altar purchase sacrifice and cessation","site_resolution_scene","altar command leads through purchase sacrifice fire answer and cessation"),
("21.28","22.1","Answered altar and temple-site declaration","cross_chapter_site_bridge","David's response to the answered altar culminates in explicit site identification"),
("22.2","22.5","Temple material and labor preparation","construction_preparation","labor and materials are motivated by Solomon's youth and project scale"),
("22.6","22.16","David charge to Solomon","commission_speech","direct address carries prohibition promise exhortation resources and workforce"),
("22.17","22.19","David charge to Israel leaders","commission_speech","audience reset opens a separate charge to assist Solomon"),
("23.1","23.5","Solomon transition Levite census and allocation","administrative_transition","succession triggers the Levite count and high-level functions"),
("23.6","23.23","Levitical clan divisions","levitical_clan_register","Gershon Kohath and Merari houses govern the roster"),
("23.24","23.32","Service age rationale and duties","cultic_duty_summary","age revision shifts from identity roster to post-rest duties"),
("24.1","24.19","Aaronide priestly divisions and lots","priestly_division_register","origin frame and impartial lots govern the full roster and closure"),
("24.20","24.31","Remaining Levite houses and lots","levitical_division_register","constituency resets to remaining Levites with parallel lot closure"),
("25.1","25.8","Musician families and service organization","music_service_register","appointments families total and lot principle form the roster frame"),
("25.9","25.31","Twenty-four musician lots","lot_register","repeated musical-service lots share one governing function"),
("26.1","26.19","Gatekeeper households and assignments","gatekeeper_register","families qualifications lots gates and deployment form one roster"),
("26.20","26.28","Treasuries and dedicated property","treasury_office_register","house and dedicated treasuries share property oversight"),
("26.29","26.32","External officers judges and regions","jurisdiction_register","administration shifts outside the sanctuary to regional jurisdictions"),
("27.1","27.15","Twelve monthly military courses","military_course_register","annual service frame governs twelve repeated monthly courses"),
("27.16","27.24","Tribal leaders and census caveat","tribal_leadership_register","tribal rulers are qualified by an explicit census limitation"),
("27.25","27.31","Royal property managers","economic_administration_register","asset and agricultural managers share royal property function"),
("27.32","27.34","Royal counselors and commanders","court_office_register","court counselors companions priests and commander close administration"),
("28.1","28.8","Assembly convocation and public charge","assembly_speech","assembled leaders hear David's royal-building account and public command"),
("28.9","28.21","Solomon commission pattern and workforce","commission_and_pattern_transfer","recipient reset governs charge written pattern specifications encouragement and personnel"),
("29.1","29.9","Contribution appeal offerings and joy","assembly_appeal_response","David's contribution and appeal receive leaders' gifts and communal joy"),
("29.10","29.19","David assembly prayer","assembly_prayer","blessing and ownership confession proceed through people and Solomon petitions"),
("29.20","29.25","Assembly worship sacrifices and Solomon accession","public_response_and_succession","worship sacrifice feast anointing enthronement and submission form the response"),
("29.26","29.30","David death succession and source closure","terminal_regnal_closure","regnal total death succession and source notice close the book"),
]

MEDIUM = {10,12,13,14,19,24,25,28,29,33,36,37,38,39,42,43,44,45,48,49,50,53,55,56,57,58,59,60,65,66,69,70,71,72,73,74,75,76,77,78,80,81,84,85,87}
SPECIAL_ALT = {
1:"canonical macro 1:1-27 versus literary 1:1-4; retain the compact primeval spine while preserving the wider ancestry funnel",
2:"literary 1:5-7 / 1:8-16 / 1:17-27 and canonical 1:1-27 versus current 1:5-23; 1:17-27 crosses D002-D003",
3:"literary 1:17-27 and canonical 1:1-27 versus current 1:24-27",
4:"1:28-31 / 1:32-33 / 1:34; larger Abraham branch transition preserves convergence on Isaac/Israel",
5:"literary 1:34-37 / 1:38-42 and canonical 1:35-54 versus current 1:35-42",
6:"1:43-50 / 1:51-54 and canonical 1:35-54",
7:"canonical 2:1-17 versus current 2:1-2 / 2:3-17",
8:"2:3-8 / 2:9-17 or canonical 2:1-17",
9:"2:18-20 / 2:21-24; Hebrew kinship attachment remains unresolved inside the larger branch",
11:"2:42-49 / 2:50-55; larger Calebite clan-settlement function retains both children",
15:"4:1-8 / 4:9-10 / 4:11-23; Jabez may be a freestanding prayer, but the larger Judah supplement avoids theological isolation",
16:"literary 4:24-38 / 4:39-43 versus current 4:24-33 / 4:34-43",
17:"literary 4:24-38 / 4:39-43, with finer 4:34-38 / 4:39-43 or 4:34-41 / 4:42-43",
18:"literary 5:1-9 / 5:10 versus current 5:1-10",
20:"canonical 5:18-26 versus current 5:18-22 / 5:23-26",
21:"exact 5:18-26 and 5:23-24 / 5:25-26 versus current 5:23-26; plural they in 5:25-26 may close half-Manasseh or all eastern tribes",
22:"WEB 6:1-15 equals MT 5:27-41; preserve this exact offset and do not use numbering as authority",
23:"WEB 6:16-30 equals MT 6:1-15; preserve the exact cross-system reset",
26:"literary 6:54-65 / 6:66-70 / 6:71-76 / 6:77-81 and canonical 6:54-81 versus current 6:54-60",
27:"literary 6:54-65 / 6:66-70 / 6:71-76 / 6:77-81 and canonical 6:54-81 versus current 6:61-81",
30:"exact 7:13-19 versus current 7:13 / 7:14-19",
31:"exact 7:13-19 versus current 7:13 / 7:14-19",
32:"7:20-24 / 7:25-29; larger Ephraim register keeps calamity and settlements within ancestry",
34:"8:1-7 / 8:8-28; larger tribe-wide register retains household and settlement children",
34:"literary 8:1-7 / 8:8-28 versus current 8:1-28",
35:"compare but do not harmonize exact duplicated spans 8:29-40 and 9:35-44",
40:"9:28-32 / 9:33-34; larger service unit keeps supply/preparation and singers under cultic administration",
40:"literary 9:28-32 / 9:33-34 versus current 9:28-34",
41:"exact duplicated registers 8:29-40 and 9:35-44, with alternative 9:35-44 / 10:1-14 as prologue",
46:"12:1-7 / 12:8-15 / 12:16-18 / 12:19-22; larger cumulative supporter-arrival parent preserves all child seams",
47:"12:23-37 / 12:38-40; larger muster-to-feast unit keeps assembly outcome with enumeration",
51:"literary 15:1-2 / 15:3-15 / 15:16-24 / 15:25-29 / 16:1-6 and canonical 15:1-15 / 15:16-24 / 15:25-29 / 16:1-7 versus current 15:1-16:6",
52:"literary 16:7-36 and canonical 16:8-22 / 16:23-33 / 16:34-36 versus current 16:7-36",
54:"17:1-15 / 17:16-27; larger oracle-response unit keeps David's prayer with the message",
61:"literary 21:1-27 / 21:28-22:1 and canonical 21:1-22:1, with finer 21:1-6 / 21:7 or 21:1-7 / 21:8-17",
62:"literary 21:1-27 / 21:28-22:1 and canonical 21:1-22:1, with finer 21:8-12 / 21:13-17",
63:"literary 21:1-27 / 21:28-22:1 and canonical 21:1-22:1, with finer 21:18-26 / 21:27",
64:"literary 21:1-27 / 21:28-22:1 and canonical 21:1-22:1, with finer 21:28-30 / 22:1",
67:"exact 22:17-23:1 / 23:2-5 versus current 22:17-19 / 23:1-5",
68:"exact 22:17-23:1 / 23:2-5, current 22:17-19 / 23:1-5, and primary 23:1-6",
79:"27:16-22 / 27:23-24; census coda remains with the tribal register it qualifies",
82:"exact primary 28:1-10 / 28:11-19 / 28:20-21, with finer 28:1-8 / 28:9-10 versus current 28:1-8 / 28:9-21",
83:"exact primary 28:1-10 / 28:11-19 / 28:20-21, with current 28:1-8 / 28:9-21 and literary 28:9-10 / 28:11-19 / 28:20-21",
86:"29:20-22 / 29:23-25, but the desired feast/accession seam also falls inside WEB 29:22; retain larger public response",
}
HAZ = {
22:"exact WEB 6:1-15 = MT 5:27-41 versification offset, priestly names and exile endpoint",
23:"exact WEB 6:16-30 = MT 6:1-15 offset, Gershom/Kohath/Merari names and ancestry syntax",
15:"Jabez name and wordplay, prayer and narrated response; etymology is not total meaning",
31:"gender and kinship syntax in Manasseh's compressed register",
35:"duplicated but nonidentical Benjamin/Saul lines; no identity or source harmonization",
21:"5:25-26 plural-they referent pressure; exact 5:23-24 / 5:25-26 versus 5:18-26",
41:"exact duplicated spans 8:29-40 and 9:35-44 plus bridge placement; no redaction or chronology ruling",
44:"warrior names ranks numbers and three/thirty framing",
51:"Perez/Uzza terms, ark offices, carrier rules, death/causation and parallel-account pressure",
52:"poetic address and refrain shifts plus Psalm parallels; no compositional preference",
54:"house seed rest covenant language and Samuel/Psalms relations; no theology ruling",
61:"satan/adversary translation, census agency, Joab report and divine displeasure",
62:"choice syntax, plague numbers, angelic agency, intercession and Samuel parallel",
63:"threshing-floor name and price, altar/fire/answer wording and plague cessation",
64:"Gibeon contrast, site identification and 2Chr 3:1 relation; no cultic-legitimacy ruling",
83:"pattern terminology, weights, offices and workforce; no Mosaic or temple-authority ruling",
86:"WEB verse-granularity limit at 29:22, anointing/enthronement wording and regnal chronology",
}

out = []
for i, (a,b,title,form,marker) in enumerate(ROWS, 1):
    span=f"1Chr.{a}-1Chr.{b}"; did=f"M7_sol-1Chr-{i:03d}"; low=i not in MEDIUM
    alt=SPECIAL_ALT.get(i, f"narrower paragraph or ancestry-head children inside {span} versus this complete {form}; retain the larger function while preserving child seams for external review")
    hot=HAZ.get(i, f"proper names, numerals, Hebrew ancestry or roster syntax, paragraph markers, translation and parallel-account pressure within {span}")
    row={
      "model_id":"M7_sol","book":"1Chr","span":span,"chunk_index_in_book":i,
      "working_title":title,"literature_type_guess":form,"literary_form":form,
      "boundary_evidence_refs":[f"direct_read:eng-web:{span}",f"direct_read:oshb:1Chr.xml#{span}",f"direct_read:uxlc:1Chr.xml#{span}","book_strategy/1Chr.md","reviews/1Chr/primary_hebrew_v1.json","reviews/1Chr/primary_literary_v1.json","reviews/1Chr/canonical_premortem_v1.json","reviews/1Chr/peer_crosscheck_v1.json","reviews/1Chr/boss_ruling_v1.json","reviews/1Chr/decision_relations.jsonl"],
      "strong_or_hebrew_tags_used":["direct_hebrew_wording_considered","source_metadata_corrob_only","roots_are_not_meaning","original_language_is_not_boundary_authority"],
      "wj_or_red_letter_considered":False,"frontier_flag_considered":True,
      "confidence":"low" if low else "medium","decision_id":did,
      "deciding_marker_or_seam":marker+".",
      "boundary_rationale":f"Prefer the complete {form} unit {span}. {marker}.",
      "rejected_alternative":f"Preserved competing boundary for {span}: {alt}.",
      "defensible_basis":f"{did}: {marker}. Local register/discourse/form, not headings, roots, genealogy reconstruction, chronology, harmonization, royal/cultic authority, or later reuse, supports this candidate.",
      "review_revision":1,"review_status":"final_deferred_appeal" if low else "candidate_review_complete",
      "review_holds":["deferred_human_or_external_ai","external_provider_review_at_convergence"] if low else ["external_provider_review_at_convergence"],
      "non_authorizing":True,"candidate_internal_seams":[alt+"."],
      "original_language_translation_holds":[f"{span}: {hot}. Exact competing span evidence: {alt}. Evidence only; no preferred reading, identity reconstruction, chronology, harmonization, cultic/royal legitimacy, providential, or theological ruling."],
      "cross_reference_holds":["Canonical relations are recorded separately and cannot harmonize Chronicles with Genesis, Samuel-Kings, Psalms, Ezra-Nehemiah, or later reuse, select witnesses, or authorize this seam."],
      "red_team_premortem_holds":[f"{span}: {hot}. Exact competing span evidence: {alt}."],
      "working_title_is_boundary_authority":False,
      "working_title_origin":"independent_1chronicles_three_primary_reconciliation_v1",
      "candidate_only":True,
      "review_evidence_summary":marker+". Candidate-only and non-authorizing.",
      "red_team_questions":[f"Does the seam after 1Chr.{b} survive removal of headings and chapter numbers?",f"Does this exact alternative better retain the governing function: {alt}?"],
      "hard_passage_forecast":[f"{span}: {hot}."]
    }
    if low:
        row.update(candidate_hold_state="deferred_human_or_external_ai",candidate_hold_basis="preserved_appeal")
    out.append(row)

assert len(out)==87
OUT.parent.mkdir(parents=True,exist_ok=True)
OUT.write_text("".join(json.dumps(x,ensure_ascii=False,separators=(",",":"))+"\n" for x in out),encoding="utf-8",newline="\n")
print(hashlib.sha256(OUT.read_bytes()).hexdigest(),len(out),sum(x["confidence"]=="low" for x in out))
