from __future__ import annotations
import hashlib,json,re
from pathlib import Path
R=Path(__file__).resolve().parent;V=R/'reviews'/'Mal';O=R/'book_chunks'/'Mal'/'chunks.jsonl'
ROUTE=[('Mal.1.1-Mal.1.5','Burden and love disputation','burden_heading_and_assertion_response_disputation','burden heading frames love assertion, how-question, Esau/Edom explanation, rebuilding counterclaim, and beyond-border acclaim'),('Mal.1.6-Mal.1.14','Priests, polluted table, and great-name close','priestly_disputation_with_offering_catalogue','new priestly address and paired how-questions sustain altar, governor, door, nations, weariness, defective offering, and great-King close'),('Mal.2.1-Mal.2.9','Priestly command, curse warning, and Levi contrast','direct_priestly_warning_and_covenant_contrast','now-to-you-priests command begins curse/body/covenant warning, Levi ideal, turned-aside accusation, and contempt close'),('Mal.2.10-Mal.2.16','Shared father, treachery, witness, and spirit warning','covenant_treachery_disputation','shared-father questions shift audience; treachery accusation, altar tears, why-response, witness explanation, one/spirit difficulty, and repeated guard-your-spirit close cohere'),('Mal.2.17-Mal.3.5','Wearied words answered by messenger, refining, and witness','cross_chapter_justice_disputation_and_oracle_answer','wearied-words assertion and how-question end with where-is-justice; behold messenger/coming, endurance, refining, restored offering, and swift-witness catalogue answer across chapter seam'),('Mal.3.6-Mal.3.12','Return, robbery question, dues, test, and blessing','return_and_dues_disputation','unchanging/return assertion prompts how-return; robbery question and answer lead through curse, whole dues, test, crop protection, and nations-delight close'),('Mal.3.13-Mal.4.3','Harsh words, remembrance, distinction, and burning-day answer','cross_chapter_disputation_remembrance_and_day_oracle','harsh-words assertion and what-question lead to complaint, fearing-speakers, remembrance, possession, and distinction; for-behold burning day and healing/reversal answer across English seam'),('Mal.4.4-Mal.4.6','Remember Moses and behold Elijah','commissioning_epilogue','remember imperative opens Torah commission; behold-sending formula and heart-turning purpose close the book without deciding identity or fulfillment')]
def L(n):return json.loads((V/n).read_text(encoding='utf-8-sig'))
def rows(d):return d.get('chunks') or d.get('units') or d.get('proposed_chunks') or d.get('proposed_units') or []
def pt(v):
 m=re.fullmatch(r'Mal\.(\d+)\.(\d+)',v);assert m,v;return int(m.group(1)),int(m.group(2))
def pair(v):p=v.split('-');return pt(p[0]),pt(p[-1])
def ov(a,b):a0,a1=pair(a);b0,b1=pair(b);return a0<=b1 and b0<=a1
def ren(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))
lit=L('blind_proposal_literary_v1.json');heb=L('blind_proposal_hebrew_textual_v1.json');can=L('blind_proposal_canonical_premortem_v1.json');P=(('literary',lit),('hebrew',heb),('canonical',can));G={n:{k:v for k,v in d.items() if k not in {'chunks','units','proposed_chunks','proposed_units'}} for n,d in P};out=[]
for i,(sp,title,form,mark) in enumerate(ROUTE,1):
 did=f'M7_sol-Mal-{i:03d}';OBy={n:[x for x in rows(d) if ov(sp,x['span'])] for n,d in P};comp='; '.join(f'{n} overlaps={ren(OBy[n])}; {n} globals={ren(G[n])}' for n,_ in P);lang=f'{sp}: {ren(OBy["hebrew"])}. Hebrew disputation, speaker, oracle, syntax, textual-witness, and Hebrew 3:19-24 versus English 4:1-6 versification pressure remain evidence only; no preferred reading, identity, doctrine, chronology, history, fulfillment, or theology.'
 out.append({'model_id':'M7_sol','book':'Mal','span':sp,'chunk_index_in_book':i,'working_title':title,'literature_type_guess':form,'literary_form':form,'boundary_evidence_refs':[f'direct_read:eng-web:{sp}','book_strategy/Mal.md','reviews/Mal/blind_proposal_hebrew_textual_v1.json','reviews/Mal/blind_proposal_literary_v1.json','reviews/Mal/blind_proposal_canonical_premortem_v1.json','reviews/Mal/peer_crosscheck_v1.json','reviews/Mal/boss_ruling_v1.json','reviews/Mal/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['direct_Hebrew_disputation_oracle_markers_considered','MT_LXX_DSS_versions_evidence_only','roots_are_not_meaning','strong_lemma_not_authority'],'wj_or_red_letter_considered':False,'frontier_flag_considered':True,'confidence':'low','decision_id':did,'deciding_marker_or_seam':mark+'.','boundary_rationale':f'Prefer complete larger {form} {sp}. {mark}.','rejected_alternative':f'All overlapping blind-primary evidence and alternatives preserved: {comp}.','defensible_basis':f'{did}: {mark}. Burden, assertion/response, audience, command, word-event, behold, day, remember, or closure—not chapter numbering or later reuse—supports this candidate.','review_revision':1,'review_status':'final_deferred_appeal','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[comp+'.'],'original_language_translation_holds':[lang],'cross_reference_holds':['Torah, Deuteronomy, priestly texts, Former Prophets, Haggai, Zechariah, Gospels, epistles, and reception relations are evidence only; no boundary symmetry, doctrine, identity, history, fulfillment, chronology, or theology.'],'red_team_premortem_holds':[f'{sp}: chapter fallback, question-answer detachment, catalogue fragmentation, speaker collapse, proof-texting, later-reuse control, witness selection, doctrine, identity, and timetable risks. Evidence:{comp}.'],'working_title_is_boundary_authority':False,'working_title_origin':'independent_malachi_three_blind_primary_larger_unit_reconciliation_v1','candidate_only':True,'review_evidence_summary':mark+'. Candidate-only and non-authorizing.','red_team_questions':[f'Does seam after {sp.split("-")[-1]} survive removal of chapters/headings/later reuse?',f'Would an exact preserved alternative better retain the full disputation/oracle parent:{comp}?'],'hard_passage_forecast':[lang],'candidate_hold_state':'deferred_human_or_external_ai','candidate_hold_basis':'preserved_appeal'})
assert len(out)==8;O.parent.mkdir(parents=True,exist_ok=True);O.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n');print(json.dumps({'sha256':hashlib.sha256(O.read_bytes()).hexdigest(),'chunks':len(out)}))
