from __future__ import annotations
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parent;V=R/'reviews'/'Mic';O=R/'book_chunks'/'Mic'/'chunks.jsonl'
def load(n):return json.loads((V/n).read_text(encoding='utf-8'))
def rows(d):return d.get('chunks') or d.get('units') or d.get('proposed_chunks') or []
def pt(v):v=v.replace('Mic.','').replace('.',':');c,n=v.split(':');return int(c),int(n)
def pair(v):a,b=v.split('-');return pt(a),pt(b)
def ov(a,b):a0,a1=pair(a);b0,b1=pair(b);return a0<=b1 and b0<=a1
def ren(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))
heb=load('blind_proposal_hebrew_textual_v1.json');lit=load('blind_proposal_literary_v1.json');can=load('blind_proposal_canonical_premortem_v1.json');hr,lr,cr=rows(heb),rows(lit),rows(can);g=lambda d:{k:v for k,v in d.items() if k not in {'chunks','units','proposed_chunks'}};out=[]
for i,s in enumerate(hr,1):
 sp=s['span'];did=f'M7_sol-Mic-{i:03d}';ls=[x for x in lr if ov(sp,x['span'])];cs=[x for x in cr if ov(sp,x['span'])];comp=f"selected Hebrew/textual={ren(s)}; literary overlaps={ren(ls)}; canonical overlaps={ren(cs)}; Hebrew globals={ren(g(heb))}; literary globals={ren(g(lit))}; canonical globals={ren(g(can))}";form=s['literary_form'];mark=s['deciding_marker'].rstrip('.');lang=f"{sp}: {ren(s)}. Hebrew hear/woe/qinah/place-name wordplay/daughter-Zion/remnant/lawsuit/hymn, speaker shifts, MT/LXX/DSS/Syriac/Vulgate/Targum and 4:14/5:1 numbering remain evidence only; no witness, emendation, identity, date, history, ethics, chronology, fulfillment or theology."
 out.append({'model_id':'M7_sol','book':'Mic','span':sp,'chunk_index_in_book':i,'working_title':s.get('title',form.capitalize()),'literature_type_guess':form,'literary_form':form,'boundary_evidence_refs':[f'direct_read:eng-web:{sp}','book_strategy/Mic.md','reviews/Mic/blind_proposal_hebrew_textual_v1.json','reviews/Mic/blind_proposal_literary_v1.json','reviews/Mic/blind_proposal_canonical_premortem_v1.json','reviews/Mic/peer_crosscheck_v1.json','reviews/Mic/boss_ruling_v1.json','reviews/Mic/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['direct_Biblical_Hebrew_prophetic_form_wordplay_considered','MT_LXX_DSS_versions_and_versification_evidence_only','roots_are_not_meaning','strong_lemma_not_authority'],'wj_or_red_letter_considered':False,'frontier_flag_considered':True,'confidence':'low','decision_id':did,'deciding_marker_or_seam':mark+'.','boundary_rationale':f'Prefer the complete larger {form} movement {sp}. {mark}. Preserve summons, lament, lawsuit-verdict, dispute, promise, disputation-response, communal confession, prayer and hymn as coherent forms.','rejected_alternative':f'Preserved exact competing evidence for {sp}: {comp}.','defensible_basis':f'{did}: {mark}. Formula, vocative, lament chain, speaker turn, promise reset, lawsuit, question escalation, confession, petition or hymn closure—not chapters, dependence, identity, later reuse, fulfillment or theology—supports this candidate.','review_revision':1,'review_status':'final_deferred_appeal','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[comp+'.'],'original_language_translation_holds':[lang],'cross_reference_holds':['Relations to Kings/Chronicles, Isaiah, Jeremiah, the Twelve, Gospels and later reuse are evidence only; no direction, harmonization, identity, chronology, fulfillment or theology.'],'red_team_premortem_holds':[f'{sp}: chapter fallback, place/list atomization, charge/verdict or indictment/promise or question/response detachment, source direction, Zion/nations/ruler/remnant identity, Bethlehem chronology, sacrifice/justice system, ethics, fulfillment and theology risks. Evidence: {comp}.'],'working_title_is_boundary_authority':False,'working_title_origin':'independent_micah_three_blind_primary_larger_unit_reconciliation_v1','candidate_only':True,'review_evidence_summary':mark+'. Candidate-only and non-authorizing.','red_team_questions':[f"Does the seam after {sp.split('-')[1]} survive removal of chapters/headings/later reuse?",f'Would an exact alternative preserve the larger form better: {comp}?'],'hard_passage_forecast':[lang],'candidate_hold_state':'deferred_human_or_external_ai','candidate_hold_basis':'preserved_appeal'})
assert len(out)==24;O.parent.mkdir(parents=True,exist_ok=True);O.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n');print(json.dumps({'sha256':hashlib.sha256(O.read_bytes()).hexdigest(),'chunks':24,'low':24}))