from __future__ import annotations
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parent;V=R/'reviews'/'Jonah';O=R/'book_chunks'/'Jonah'/'chunks.jsonl'
def load(n):return json.loads((V/n).read_text(encoding='utf-8'))
def rows(d):return d.get('chunks') or d.get('units') or d.get('proposed_chunks') or []
def pt(v):v=v.replace('Jonah.','').replace('.',':');c,n=v.split(':');return int(c),int(n)
def pair(v):a,b=v.split('-');return pt(a),pt(b)
def ov(a,b):a0,a1=pair(a);b0,b1=pair(b);return a0<=b1 and b0<=a1
def ren(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))
can=load('blind_proposal_canonical_premortem_v1.json');lit=load('blind_proposal_literary_v1.json');heb=load('blind_proposal_hebrew_textual_v1.json');cr,lr,hr=rows(can),rows(lit),rows(heb);g=lambda d:{k:v for k,v in d.items() if k not in {'chunks','units','proposed_chunks'}};out=[]
for i,s in enumerate(cr,1):
 sp=s['span'];did=f'M7_sol-Jonah-{i:03d}';ls=[x for x in lr if ov(sp,x['span'])];hs=[x for x in hr if ov(sp,x['span'])];comp=f"selected canonical={ren(s)}; literary overlaps={ren(ls)}; Hebrew overlaps={ren(hs)}; canonical globals={ren(g(can))}; literary globals={ren(g(lit))}; Hebrew globals={ren(g(heb))}";form=s['form'];mark=s['marker'].rstrip('.');lang=f"{sp}: {ren(hs)}. Hebrew descent/great/appointed/raah-shuv-nacham wordplay, prayer poetry, qiqayon, MT/LXX/DSS/Syriac/Vulgate/Targum, 1:17-2:1 numbering and forty/three wording remain evidence only; no witness, emendation, source, history, miracle, identity, ethics, fulfillment or theology."
 out.append({'model_id':'M7_sol','book':'Jonah','span':sp,'chunk_index_in_book':i,'working_title':form.capitalize(),'literature_type_guess':form,'literary_form':form,'boundary_evidence_refs':[f'direct_read:eng-web:{sp}','book_strategy/Jonah.md','reviews/Jonah/blind_proposal_hebrew_textual_v1.json','reviews/Jonah/blind_proposal_literary_v1.json','reviews/Jonah/blind_proposal_canonical_premortem_v1.json','reviews/Jonah/peer_crosscheck_v1.json','reviews/Jonah/boss_ruling_v1.json','reviews/Jonah/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['direct_Biblical_Hebrew_narrative_and_prayer_form_considered','MT_LXX_DSS_versions_wordplay_and_versification_evidence_only','roots_are_not_meaning'],'wj_or_red_letter_considered':False,'frontier_flag_considered':True,'confidence':'low','decision_id':did,'deciding_marker_or_seam':mark+'.','boundary_rationale':f'Prefer the complete larger {form} movement {sp}. {mark}. Preserve commission-response, storm-resolution, fish-prayer-deliverance, proclamation-response, anger dialogue, appointed-agent object lesson and final question.','rejected_alternative':f'Preserved exact competing evidence for {sp}: {comp}.','defensible_basis':f'{did}: {mark}. Word-event, scene reset, question chain, calm/response, prayer voice, recommission, decree, dialogue, appointed sequence or open closure—not chapters, history, miracle, identity, later reuse or theology—supports this candidate.','review_revision':1,'review_status':'final_deferred_appeal','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[comp+'.'],'original_language_translation_holds':[lang],'cross_reference_holds':['Relations to Kings, Psalms, prophets, Gospels and later reuse are evidence only; no source, harmonization, sign identity, chronology, fulfillment or theology.'],'red_team_premortem_holds':[f'{sp}: chapter fallback, scene/question atomization, storm/calm or prayer/deliverance or proclamation/response detachment, genre/historicity, miracle, sailor/Ninevite status, prayer source, divine relenting, ethics, sign/fulfillment and theology risks. Evidence: {comp}.'],'working_title_is_boundary_authority':False,'working_title_origin':'independent_jonah_three_blind_primary_larger_unit_reconciliation_v1','candidate_only':True,'review_evidence_summary':mark+'. Candidate-only and non-authorizing.','red_team_questions':[f"Does the seam after {sp.split('-')[1]} survive removal of chapters/headings/later reuse?",f'Would an exact alternative preserve the larger scene/prayer better: {comp}?'],'hard_passage_forecast':[lang],'candidate_hold_state':'deferred_human_or_external_ai','candidate_hold_basis':'preserved_appeal'})
assert len(out)==7;O.parent.mkdir(parents=True,exist_ok=True);O.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n');print(json.dumps({'sha256':hashlib.sha256(O.read_bytes()).hexdigest(),'chunks':7,'low':7}))