from __future__ import annotations
import hashlib,json,re
from pathlib import Path
R=Path(__file__).resolve().parent;V=R/'reviews'/'Zech';O=R/'book_chunks'/'Zech'/'chunks.jsonl'
ROUTE=[
('Zech.1.1-Zech.1.6','Opening return appeal','dated_prophetic_exhortation','date/word-event opens; ancestors-prophets questions and reported response close before the new date'),
('Zech.1.7-Zech.1.17','Horse patrol vision and comfort oracle','dated_night_vision_report_intercession_oracle','new date; seeing, patrol report, how-long intercession, answer, and commanded proclamation close before a new seeing formula'),
('Zech.1.18-Zech.1.21','Four horns and craftsmen','symbolic_vision_dialogue','lifted-eyes formula introduces horns, question, craftsmen, second question, and explanation'),
('Zech.2.1-Zech.2.13','Measuring line vision and Zion summons','symbolic_vision_with_embedded_oracle','lifted-eyes formula begins measuring; messenger speech expands through flee, sing, dwelling, nations, inheritance, and universal silence'),
('Zech.3.1-Zech.3.10','Joshua court, reclothing, and sign oracle','heavenly_court_vision_and_symbolic_oracle','new shown scene sustains accusation, rebuke, garment removal, commission, sign, stone, and vine-fig closure'),
('Zech.4.1-Zech.4.14','Lampstand and olive trees','symbolic_vision_with_repeated_interpretation_dialogue','messenger returns and awakens; seeing, two question cycles, embedded word, and final identification form one vision'),
('Zech.5.1-Zech.5.4','Flying scroll','symbolic_vision_and_curse_interpretation','renewed lifted-eyes formula introduces scroll, dimensions, and complete interpretation before another seeing command'),
('Zech.5.5-Zech.5.11','Ephah carried to Shinar','symbolic_vision_dialogue','go-out-and-see command introduces ephah, figure, lid, winged carriers, destination question, and answer'),
('Zech.6.1-Zech.6.8','Four chariots','symbolic_vision_with_mission_interpretation','renewed lifted-eyes formula begins catalogue, question, explanation, deployment, and north-country closure'),
('Zech.6.9-Zech.6.15','Crown sign-act and oracle','word_event_symbolic_action_with_oracle','new word-event commands collection and crowning; sign-act, oracle, memorial, and distant-builders close together'),
('Zech.7.1-Zech.7.7','Fasting inquiry and first answer','dated_inquiry_with_prophetic_disputation','new date, delegation, and fasting question lead to renewed word-event and rhetorical answer about fasting and former words'),
('Zech.7.8-Zech.7.14','Justice appeal and refusal retrospect','renewed_word_event_exhortation_and_retrospect','renewed word-event introduces commands, refusal, hardened hearing, reciprocal nonhearing, scattering, and desolation'),
('Zech.8.1-Zech.8.8','Return, dwelling, and restored city','restoration_oracle_chain','renewed word-event begins sayings about jealousy, return, city life, wonder, gathering, and mutual belonging'),
('Zech.8.9-Zech.8.17','Strong hands and truth-peace obligations','restoration_exhortation_with_before_now_contrast','fresh messenger saying addresses present hearers; before-now contrast, seed-of-peace promise, fear-not, and obligations form one movement'),
('Zech.8.18-Zech.8.23','Fasts transformed and nations seeking','renewed_word_event_with_paired_future_sayings','renewed word-event answers fasting and proceeds through city-to-city and nations-seeking sayings to garment-grasping close'),
('Zech.9.1-Zech.9.8','First burden: surrounding lands and guarded house','burden_oracle_geographic_catalogue','burden heading begins geographic progression and closes with guarded-house declaration'),
('Zech.9.9-Zech.9.17','Royal arrival, released prisoners, and defended flock','Zion_summons_and_salvation_oracle','rejoice summons shifts addressee/form; arrival, peace, release, battle, defense, and flock-jewel close remain one movement'),
('Zech.10.1-Zech.10.5','Rain appeal and shepherd indictment','imperative_oracle_indictment_and_battle_transformation','rain imperative contrasts false sources, moves to shepherd anger and visitation, and culminates in cornerstone, peg, bow, rulers, and battle'),
('Zech.10.6-Zech.10.12','Strengthening, gathering, return, and passage','first_person_restoration_oracle','first-person strengthening promise sustains gathering, sowing, return, passage, humbled powers, and walking-in-name closure'),
('Zech.11.1-Zech.11.3','Forest and shepherd lament','imperative_lament','open, wail, and voice formulas create compact forest-shepherd-lion lament before feed-the-flock commission'),
('Zech.11.4-Zech.11.14','Flock of slaughter and two staffs','prophetic_shepherd_sign_act_narrative','commission begins flock enactment; staffs, rejected shepherding, broken Favor, wages, silver, and broken Union complete action'),
('Zech.11.15-Zech.11.17','Foolish shepherd sign and woe','renewed_shepherd_sign_act_oracle','renewed command to take shepherd equipment introduces contrasting portrait and terminal woe'),
('Zech.12.1-Zech.12.9','Second burden: siege and deliverance','burden_oracle_with_repeated_day_formula','new burden introduces creator speech, siege images, repeated day formulas, Judah-Jerusalem interaction, and defense-destruction close'),
('Zech.12.10-Zech.13.1','Poured spirit, clan mourning, and opened fountain','mourning_oracle_litany_and_fountain_close','pouring declaration shifts siege to looking and mourning; clan-by-clan refrain leads through the cross-chapter day formula to the opened fountain close'),
('Zech.13.2-Zech.13.6','Removal of names and discredited prophecy','day_oracle_with_prophetic_disputation_scene','renewed it-shall-be-in-that-day oracle opens removal of names and prophets, followed by parental speech and disguised-prophet dialogue'),
('Zech.13.7-Zech.13.9','Struck shepherd, scattering, and refining','sword_summons_and_refining_oracle','apostrophe to sword marks new poetic movement; striking, scattering, hand-turning, fractions, refining, calling, and reciprocal declaration close together'),
('Zech.14.1-Zech.14.11','Day, battle, transformed land, and kingship','day_battle_and_transformation_oracle','behold-day opens battle, departure, mountain-waters transformation, kingship, land change, and secure habitation'),
('Zech.14.12-Zech.14.21','Plague, pilgrimage, and universal holiness','plague_catalogue_and_pilgrimage_holiness_climax','this-will-be-the-plague shifts consequences; plague and tumult lead to survivor pilgrimage, rain sanction, and repeated holiness close')]
def L(n):return json.loads((V/n).read_text(encoding='utf-8-sig'))
def rows(d):return d.get('chunks') or d.get('units') or d.get('proposed_chunks') or d.get('proposed_units') or []
def pt(v):
 m=re.fullmatch(r'Zech\.(\d+)\.(\d+)',v);assert m,v;return int(m.group(1)),int(m.group(2))
def pair(v):
 p=v.split('-');return pt(p[0]),pt(p[-1])
def ov(a,b):a0,a1=pair(a);b0,b1=pair(b);return a0<=b1 and b0<=a1
def ren(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))
lit=L('blind_proposal_literary_v1.json');heb=L('blind_proposal_hebrew_textual_v1.json');can=L('blind_proposal_canonical_premortem_v1.json');P=(('literary',lit),('hebrew',heb),('canonical',can));G={n:{k:v for k,v in d.items() if k not in {'chunks','units','proposed_chunks','proposed_units'}} for n,d in P};out=[]
for i,(sp,title,form,mark) in enumerate(ROUTE,1):
 did=f'M7_sol-Zech-{i:03d}';OBy={n:[x for x in rows(d) if ov(sp,x['span'])] for n,d in P};comp='; '.join(f'{n} overlaps={ren(OBy[n])}; {n} globals={ren(G[n])}' for n,_ in P);lang=f'{sp}: {ren(OBy["hebrew"])}. Hebrew discourse, vision, oracle, speaker, burden, day-formula, poetic, versification, and MT/LXX/DSS/Syriac/Vulgate/Targum pressure remain evidence only; no preferred reading, identity, chronology, history, fulfillment, or theology.'
 out.append({'model_id':'M7_sol','book':'Zech','span':sp,'chunk_index_in_book':i,'working_title':title,'literature_type_guess':form,'literary_form':form,'boundary_evidence_refs':[f'direct_read:eng-web:{sp}','book_strategy/Zech.md','reviews/Zech/blind_proposal_hebrew_textual_v1.json','reviews/Zech/blind_proposal_literary_v1.json','reviews/Zech/blind_proposal_canonical_premortem_v1.json','reviews/Zech/peer_crosscheck_v1.json','reviews/Zech/boss_ruling_v1.json','reviews/Zech/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['direct_Hebrew_discourse_vision_oracle_markers_considered','MT_LXX_DSS_versions_evidence_only','roots_are_not_meaning','strong_lemma_not_authority'],'wj_or_red_letter_considered':False,'frontier_flag_considered':True,'confidence':'low','decision_id':did,'deciding_marker_or_seam':mark+'.','boundary_rationale':f'Prefer complete larger {form} {sp}. {mark}.','rejected_alternative':f'All overlapping blind-primary evidence and alternatives preserved: {comp}.','defensible_basis':f'{did}: {mark}. Date/word-event, seeing/question/interpretation, speaker/form, burden, lament, sign-act, refrain, or closure—not chapter numbering or later reuse—supports this candidate.','review_revision':1,'review_status':'final_deferred_appeal','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[comp+'.'],'original_language_translation_holds':[lang],'cross_reference_holds':['Torah, Former Prophets, Isaiah, Jeremiah, Ezekiel, Haggai, Ezra, Gospels, epistles, Revelation, and reception relations are evidence only; no boundary symmetry, identity, history, fulfillment, eschatology, or theology.'],'red_team_premortem_holds':[f'{sp}: chapter fallback, vision/dialogue detachment, speaker collapse, sign-act fragmentation, proof-texting, later-reuse control, witness selection, and eschatological sequencing risks. Evidence:{comp}.'],'working_title_is_boundary_authority':False,'working_title_origin':'independent_zechariah_three_blind_primary_larger_unit_reconciliation_v1','candidate_only':True,'review_evidence_summary':mark+'. Candidate-only and non-authorizing.','red_team_questions':[f'Does seam after {sp.split("-")[-1]} survive removal of chapters/headings/later reuse?',f'Would an exact preserved alternative better retain the full parent:{comp}?'],'hard_passage_forecast':[lang],'candidate_hold_state':'deferred_human_or_external_ai','candidate_hold_basis':'preserved_appeal'})
assert len(out)==28;O.parent.mkdir(parents=True,exist_ok=True);O.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n');print(json.dumps({'sha256':hashlib.sha256(O.read_bytes()).hexdigest(),'chunks':len(out)}))
