"""M7_sol environment-bound adapter: reconcile three frozen blind 2Tim proposals into a candidate map."""
from __future__ import annotations
import hashlib,json,re
from pathlib import Path
R=Path(__file__).resolve().parent;B='Heb';V=R/'reviews'/B;O=R/'book_chunks'/B/'chunks.jsonl';SELECTED_ROLE='literary'
def L(n):return json.loads((V/n).read_text(encoding='utf-8-sig'))
def rows(d):return d.get('chunks') or d.get('units') or d.get('proposed_chunks') or d.get('proposed_units') or d.get('candidate_units') or []
def pt(v):
 m=re.fullmatch(r'Heb\.(\d+)\.(\d+)',v);assert m,v;return int(m.group(1)),int(m.group(2))
def pair(v):p=v.split('-');return pt(p[0]),pt(p[-1])
def ov(a,b):a0,a1=pair(a);b0,b1=pair(b);return a0<=b1 and b0<=a1
def ren(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))
lit=L('blind_proposal_literary_v1.json');grk=L('blind_proposal_greek_textual_v1.json');can=L('blind_proposal_canonical_premortem_v1.json');P=(('literary',lit),('greek',grk),('canonical',can));D=dict(P);selected=rows(D[SELECTED_ROLE]);G={n:{k:v for k,v in d.items() if k not in {'chunks','units','proposed_chunks','proposed_units','candidate_units'}} for n,d in P};out=[]
for i,s in enumerate(selected,1):
 sp=s['span'];did=f'M7_sol-{B}-{i:03d}';form=s.get('literary_form') or s.get('form') or s.get('form_function') or s.get('epistle_unit_form') or 'epistolary_discourse_unit';title=s.get('title') or s.get('working_title') or form.replace('_',' ');markers=s.get('deciding_markers') or s.get('markers') or s.get('span_specific_marker') or s.get('marker_and_seam') or [];markers=[markers] if isinstance(markers,str) else markers;mark='; '.join(markers).rstrip('.') or 'complete marked epistolary movement';rationale=s.get('literary_rationale') or s.get('rationale') or s.get('decision') or f'The marker sequence retains {sp} as one larger coherent {form}.';macro=s.get('macro_parent_id') or s.get('macro_parent') or s.get('larger_parent') or 'unassigned_macro_parent';alts=s.get('exact_alternatives') or s.get('smaller_routes') or s.get('exact_smaller_alternatives') or s.get('finer_routes') or s.get('route_table') or [];larger=s.get('larger_routes') or s.get('exact_larger_alternative') or macro;OBy={n:[x for x in rows(d) if ov(sp,x['span'])] for n,d in P};comp='; '.join(f'{n} overlaps={ren(OBy[n])}; {n} globals={ren(G[n])}' for n,_ in P);lang=f'{sp}: {ren(OBy["greek"])}. Koine syntax, discourse, textual-witness, translation, list-function, quotation, and addressee pressure remain evidence only; no preferred reading, authorship, history, witness selection, authorship, history, priesthood/covenant/sacrifice/apostasy/canon/supersession/fulfillment/doctrine or theology.'
 out.append({'model_id':'M7_sol','book':B,'span':sp,'chunk_index_in_book':i,'working_title':title,'literature_type_guess':form,'literary_form':form,'boundary_evidence_refs':[f'direct_read:eng-web:{sp}',f'book_strategy/{B}.md',f'reviews/{B}/blind_proposal_greek_textual_v1.json',f'reviews/{B}/blind_proposal_literary_v1.json',f'reviews/{B}/blind_proposal_canonical_premortem_v1.json',f'reviews/{B}/peer_crosscheck_v1.json',f'reviews/{B}/boss_ruling_v1.json',f'reviews/{B}/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['direct_Koine_Greek_discourse_markers_considered','Greek_witness_variants_evidence_only','roots_etymology_are_not_meaning','strong_lemma_morphology_not_authority'],'wj_or_red_letter_considered':True,'frontier_flag_considered':True,'confidence':'low','decision_id':did,'deciding_marker_or_seam':mark+'.','boundary_rationale':f'{rationale} Deciding markers: {mark}.','rejected_alternative':f'All overlapping blind-primary evidence and exact alternatives preserved: {comp}.','defensible_basis':f'{did}: {rationale} Marker sequence: {mark}. Macro parent: {ren(macro)}. Exact smaller alternatives: {ren(alts)}. Exact larger alternative: {ren(larger)}.','review_revision':1,'review_status':'final_deferred_appeal','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[f'exact_smaller_alternatives={ren(alts)}',f'exact_larger_alternative={ren(larger)}',comp+'.'],'original_language_translation_holds':[lang],'cross_reference_holds':['Torah, Prophets, Psalms/Wisdom, Gospel traditions, Acts, other epistles, Revelation, Second Temple sources, and later Jewish/patristic reception are evidence only; no harmonization, authorship, succession policy, boundary symmetry, doctrine, canon, history, chronology, or theology.'],'red_team_premortem_holds':[f'{sp}: chapter fallback, command-ground detachment, citation/exposition/warning/cultic/faith-catalogue atomization, proof-texting, supplied quotation control, textual-witness selection, policy smuggling, authorship, history, doctrine, canon, and theology risks. Evidence: {comp}.'],'working_title_is_boundary_authority':False,'working_title_origin':f'independent_hebrews_three_blind_primary_{SELECTED_ROLE}_larger_route_reconciliation_v1','candidate_only':True,'review_evidence_summary':f'{mark}. Candidate-only and non-authorizing.','red_team_questions':[f'Does the seam after {sp.split("-")[-1]} survive removal of chapters, headings, paragraphing, and supplied quotation marks?',f'Would an exact preserved smaller route better expose a form change without detaching command, ground, list function, confession, or larger parent? {ren(alts)}'], 'hard_passage_forecast':[lang],'candidate_hold_state':'deferred_human_or_external_ai','candidate_hold_basis':'preserved_appeal'})
assert out;O.parent.mkdir(parents=True,exist_ok=True);O.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n');print(json.dumps({'sha256':hashlib.sha256(O.read_bytes()).hexdigest(),'chunks':len(out),'selected_role':SELECTED_ROLE}))