from __future__ import annotations
import hashlib,json,re
from pathlib import Path
R=Path(__file__).resolve().parent;V=R/'reviews'/'Matt';O=R/'book_chunks'/'Matt'/'chunks.jsonl';SELECTED_ROLE='greek'
def L(n):return json.loads((V/n).read_text(encoding='utf-8-sig'))
def rows(d):return d.get('chunks') or d.get('units') or d.get('proposed_chunks') or d.get('proposed_units') or []
def pt(v):
 m=re.fullmatch(r'Matt\.(\d+)\.(\d+)',v);assert m,v;return int(m.group(1)),int(m.group(2))
def pair(v):p=v.split('-');return pt(p[0]),pt(p[-1])
def ov(a,b):a0,a1=pair(a);b0,b1=pair(b);return a0<=b1 and b0<=a1
def ren(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))
lit=L('blind_proposal_literary_v1.json');grk=L('blind_proposal_greek_textual_v1.json');can=L('blind_proposal_canonical_premortem_v1.json');P=(('literary',lit),('greek',grk),('canonical',can));D=dict(P);selected=rows(D[SELECTED_ROLE]);G={n:{k:v for k,v in d.items() if k not in {'chunks','units','proposed_chunks','proposed_units'}} for n,d in P};out=[]
for i,s in enumerate(selected,1):
 sp=s['span'];did=f'M7_sol-Matt-{i:03d}';title=s.get('title') or s.get('working_title') or f'Matthew literary unit {i}';form=s.get('literary_form') or s.get('form') or 'narrative_or_discourse_unit';mark=(s.get('deciding_marker') or s.get('deciding_marker_or_seam') or s.get('defensible_basis') or 'complete larger literary movement').rstrip('.');OBy={n:[x for x in rows(d) if ov(sp,x['span'])] for n,d in P};comp='; '.join(f'{n} overlaps={ren(OBy[n])}; {n} globals={ren(G[n])}' for n,_ in P);lang=f'{sp}: {ren(OBy["greek"])}. Koine discourse, syntax, speaker, textual-witness, translation, paragraph, and variant pressure remain evidence only; no preferred reading, source, identity, history, harmonization, fulfillment, doctrine, or theology.'
 out.append({'model_id':'M7_sol','book':'Matt','span':sp,'chunk_index_in_book':i,'working_title':title,'literature_type_guess':form,'literary_form':form,'boundary_evidence_refs':[f'direct_read:eng-web:{sp}','book_strategy/Matt.md','reviews/Matt/blind_proposal_greek_textual_v1.json','reviews/Matt/blind_proposal_literary_v1.json','reviews/Matt/blind_proposal_canonical_premortem_v1.json','reviews/Matt/peer_crosscheck_v1.json','reviews/Matt/boss_ruling_v1.json','reviews/Matt/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['direct_Koine_Greek_discourse_narrative_markers_considered','Greek_witness_variants_evidence_only','roots_etymology_are_not_meaning','strong_lemma_morphology_not_authority'],'wj_or_red_letter_considered':True,'frontier_flag_considered':True,'confidence':'low','decision_id':did,'deciding_marker_or_seam':mark+'.','boundary_rationale':f'Prefer complete larger {form} {sp}. {mark}.','rejected_alternative':f'All overlapping blind-primary evidence and alternatives preserved: {comp}.','defensible_basis':f'{did}: {mark}. Scene, discourse, question-answer, parable, controversy, list function, passion transition, or closure—not chapter numbering, red letters, variants, Synoptic alignment, or later reuse—supports this candidate.','review_revision':1,'review_status':'final_deferred_appeal','review_holds':['deferred_human_or_external_ai','external_provider_review_at_convergence'],'non_authorizing':True,'candidate_internal_seams':[comp+'.'],'original_language_translation_holds':[lang],'cross_reference_holds':['Torah, Prophets, Psalms, Mark, Luke, John, Acts, epistles, Revelation, Second Temple sources, and later rabbinic/patristic reception are evidence only; no harmonization, source priority, boundary symmetry, doctrine, identity, history, fulfillment, chronology, or theology.'],'red_team_premortem_holds':[f'{sp}: chapter fallback, scene or discourse fragmentation, question-answer detachment, list atomization, proof-texting, red-letter/heading control, Synoptic harmonization, source-priority smuggling, variant selection, later-reuse control, doctrine, identity, and timetable risks. Evidence:{comp}.'],'working_title_is_boundary_authority':False,'working_title_origin':f'independent_matthew_three_blind_primary_{SELECTED_ROLE}_route_reconciliation_v1','candidate_only':True,'review_evidence_summary':mark+'. Candidate-only and non-authorizing.','red_team_questions':[f'Does seam after {sp.split("-")[-1]} survive removal of chapters, headings, red letters, Synoptic alignment, and later reuse?',f'Would an exact preserved alternative better retain the full scene/discourse/parable/controversy parent:{comp}?'],'hard_passage_forecast':[lang],'candidate_hold_state':'deferred_human_or_external_ai','candidate_hold_basis':'preserved_appeal'})
assert out;O.parent.mkdir(parents=True,exist_ok=True);O.write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in out),encoding='utf-8',newline='\n');print(json.dumps({'sha256':hashlib.sha256(O.read_bytes()).hexdigest(),'chunks':len(out),'selected_role':SELECTED_ROLE}))
