#!/usr/bin/env python3
"""Deterministic, candidate-only T561 Malachi corrective rereview materializer."""
from __future__ import annotations
import argparse,hashlib,json,re
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[6];MODEL=ROOT/'.ai'/'scratch'/'multi_model_bible_chunking'/'M7_sol';REV=MODEL/'reviews'/'Mal';CHUNKS=MODEL/'book_chunks'/'Mal'/'chunks.jsonl';ROUTE=REV/'adjudicated_route_draft_v2.json';POST=REV/'post_ruling_appeal_opportunities_v2.json';BOSS=REV/'fresh_boss_adjudication_v2.json';WEB=ROOT/'data'/'canonical'/'translations'/'eng-web'/'translation_witnesses.jsonl';STRATEGY=MODEL/'book_strategy'/'Mal.md';CONTRACT=MODEL/'review_contract.yaml';USFM=ROOT/'data'/'processed'/'bible'/'eng-web'/'usfm'/'extracted'/'40-MALeng-web.usfm';OSHB=ROOT/'data'/'candidate'/'original_language_evidence'/'canonical_source_views'/'openscriptures_oshb'/'files'/'Mal.xml';UXLC=ROOT/'data'/'candidate'/'original_language_evidence'/'canonical_source_views'/'tanach_us_uxlc'/'files'/'Mal.xml'
PREFIX_BYTES=393_507;PREFIX_SHA='f3109b7d3dcff581470c0c2c137dc9e87dbe1307589ef4a39bf4f9b8789caf51';APPEAL_IDS={'T561-Mal-Hebrew-A01','T561-CAN-APPEAL-MAL-3-18-4-1-PRESENTATION'}
FROZEN={'strategy':'a457c7b0ca40129b978cadb400c3c44d3fe15093c7154bac7a61e5006253dd4f','contract':'a32f4fa9d83039b97d96fa9ffc2c795f60272e6424a3ae053bd8cfe5a70011e0','blind_proposal_hebrew_textual_v2.json':'c00fe97248a7708773fff864ad333f19b17adf41d4d7f1160b7af08709b775c8','blind_proposal_literary_v2.json':'64bc18106afb05d4bfcada73e2300e24df4caf9a729caeb15fee0b894ca10e2f','blind_proposal_canonical_premortem_v2.json':'9184e3dd2592148df9d5ec21915d551df9e698e1d5b981bea0be788304662280','fresh_boss_adjudication_v2.json':'cc70f4336ceddca7fbe14bb27e7ffbba8db5fc30686e36f7d13a2b986f6f43f7','fresh_boss_encoding_repair_receipt_v2.json':'b7a0e735e20240b4e8a1a52b605a5161d767f86863312c71a584c09ecb1ed01d','fresh_boss_encoding_repair_receipt_correction_v2.json':'abaf1f5462ad7c3712a2d04aec8fc28247c4b45b74d8ff10c539ead433b0de88','post_ruling_response_hebrew_v2.json':'5646fc4fa61ad86e655e560e83124acd8facf181209a48553e8bfe329e876086','post_ruling_response_literary_v2.json':'e57019f002b8065da9c207016543f9cc38ac5e0f3d260186e13ba70367a6d08c','post_ruling_response_canonical_v2.json':'0904b6b7b42fe5f1b5559b890f0d22915af093dbf7fcb54ea30ab1d513f7e0b1','post_ruling_appeal_opportunities_v2.json':'8a7b23fd757fdc5811dcfb1dc80da3c1aca45d0befd733925aa023c1e2e6ac99','adjudicated_route_draft_v2.json':'5a09631e9f351ae2398313da53ed7d52bd8be157e254f805e8d6c1b91090938f','adjudicated_route_encoding_repair_receipt_v2.json':'f30a1ac4e74c40209974b3a72f7b9c0718489e53de0dc50b14e54f88d918dbd9','independent_frozen_route_literary_redteam_v2.json':'c8f9f4f6e3f9fae460e5e575f226ae6e8ce52c4fbed9c5f9dea428381c589679','independent_frozen_route_source_redteam_v2.json':'732cd697d08ea67eb22301a058fd2c61027a8c5e6ae94f32ae4710db62f7b422','usfm':'fa50d3b312bb8664ed81c3b0292fef455115aebd580d6583a5de2e6e148c0bff','oshb':'1583e6a701406dce7b8c2bf85e3522ec31383756de130685fc7c2eb6df8964b2','uxlc':'1c698374965c4ad294c4acee79811c88d7a2b37982513567c56bb533f64f49c5'}
ROLES=(('hebrew','original_language_translation_specialist','blind_proposal_hebrew_textual_v2.json'),('literary','prophetic_disputation_literary_form_primary','blind_proposal_literary_v2.json'),('canonical','canonical_relations_retrieval_premortem_primary','blind_proposal_canonical_premortem_v2.json'));INDEP={'independent_from_sibling_model_maps':True,'primaries_blind_to_each_other_artifacts':True,'roles_separated':True,'shared_model_substrate':True,'counts_as_cross_model_independent_votes':False,'independent_model_or_human_evidence_required_at_convergence':True,'reviewer_count_is_not_authority':True,'correlated_mesh_weight_at_convergence':'one_model_voice'}
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def shab(b:bytes)->str:return hashlib.sha256(b).hexdigest()
def rj(p:Path)->dict[str,Any]:return json.loads(p.read_text(encoding='utf-8'))
def rjl(p:Path)->list[dict[str,Any]]:return [json.loads(x) for x in p.read_text(encoding='utf-8').splitlines() if x.strip()] if p.exists() else []
def jb(x:Any,pretty:bool=False)->bytes:return (json.dumps(x,ensure_ascii=False,indent=2) if pretty else json.dumps(x,ensure_ascii=False,separators=(',',':'))).encode()+b'\n'
def jlb(xs:list[dict[str,Any]])->bytes:return b''.join(jb(x) for x in xs)
def wj(p:Path,x:Any)->None:p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(jb(x,True))
def wjl(p:Path,x:list[dict[str,Any]])->None:p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(jlb(x))
def rowsha(x:dict[str,Any])->str:return shab(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode())
def norm(s:str)->str:
 a,b=s.split('-');return f'{a}-{b if b.startswith("Mal.") else "Mal."+b}'
def mt(r:str)->str:
 book,ch,v=r.split('.')
 if book!='Mal':raise ValueError(r)
 return f'Mal.3.{int(v)+18}' if ch=='4' else r
def srefs(span:str,did:str)->list[Any]:
 a,b=span.split('-');ms=f'{mt(a)}-{mt(b)}';status='validated_web_mt_malachi_web_chapter_4_to_mt_chapter_3_plus_18' if a!=mt(a) or b!=mt(b) else 'validated_web_mt_malachi_same_coordinates';out:[Any]=[f'direct_read:eng-web:{span}']
 for sid in ('oshb','uxlc'):out.append({'source_id':sid,'span':span,'web_span':span,'source_span':ms,'coordinate_system':'MT_WLC','crosswalk_status':status,'source_metadata_boundary_authority':False,'versification_crosswalk_is_evidence_only':True,'wlc_family_correlation_disclosed':True,'oshb_uxlc_are_independent_witnesses':False,'observation':f'{did}:{sid.upper()}_correlated_WLC_family_locator_{ms}'})
 return out
def verify()->None:
 paths={'strategy':STRATEGY,'contract':CONTRACT,'fresh_boss_adjudication_v2.json':BOSS,'post_ruling_appeal_opportunities_v2.json':POST,'adjudicated_route_draft_v2.json':ROUTE,'usfm':USFM,'oshb':OSHB,'uxlc':UXLC}
 for _c,_r,n in ROLES:paths[n]=REV/n
 for n in ('fresh_boss_encoding_repair_receipt_v2.json','fresh_boss_encoding_repair_receipt_correction_v2.json','post_ruling_response_hebrew_v2.json','post_ruling_response_literary_v2.json','post_ruling_response_canonical_v2.json','adjudicated_route_encoding_repair_receipt_v2.json','independent_frozen_route_literary_redteam_v2.json','independent_frozen_route_source_redteam_v2.json'):paths[n]=REV/n
 for n,p in paths.items():
  got=sha(p)
  if got!=FROZEN[n]:raise ValueError(f'frozen Mal input changed: {n} {got} != {FROZEN[n]}')
 overlay=rj(REV/'fresh_boss_encoding_repair_receipt_correction_v2.json');lit=rj(REV/'independent_frozen_route_literary_redteam_v2.json');src=rj(REV/'independent_frozen_route_source_redteam_v2.json')
 if overlay['validation']['suspicious_ascii_substitution_count'] or overlay['validation']['literal_double_question_count']:raise ValueError('repair overlay not clean')
 if lit.get('verdict')!='pass_with_holds' or src.get('verdict')!='pass_with_holds':raise ValueError('clean redteams not passing')
 if src['input_hashes']['correction_addendum']['sha256']!=FROZEN['fresh_boss_encoding_repair_receipt_correction_v2.json'] or src['input_hashes']['current_parallel_literary_redteam']['sha256']!=FROZEN['independent_frozen_route_literary_redteam_v2.json']:raise ValueError('clean redteam binding changed')
def inventory()->tuple[list[str],dict[str,str]]:
 rows=[x for x in rjl(WEB) if str(x.get('osis_ref','')).startswith('Mal.')];refs=[x['osis_ref'] for x in rows];texts={x['osis_ref']:x['text'] for x in rows}
 if len(refs)!=55 or refs[0]!='Mal.1.1' or refs[-1]!='Mal.4.6' or len(set(refs))!=55:raise ValueError('bad Mal WEB inventory')
 return refs,texts
def firstq(q:str)->str:
 a,m,_=q.partition('?')
 if not m or not a.strip():raise ValueError('hold question not interrogative')
 return a.strip()+'?'
def pspan(u:dict[str,Any])->str:
 p=u.get('mandatory_parents') or [];return ';'.join(p) if p else u['span']
def alttext(xs:list[Any])->str:
 return '; '.join(x if isinstance(x,str) else f"{x.get('span','alternative')}: {x.get('reason','')}" for x in xs)
def primary(code:str,u:dict[str,Any],props:dict[str,dict[str,Any]])->dict[str,Any]:
 span=u['span'];did=f"M7_sol-Mal-{u['chunk_index_in_book']:03d}";p=props[code];child=code=='hebrew' and span in {'Mal.2.1-Mal.2.4','Mal.2.5-Mal.2.9'};wanted='Mal.2.1-Mal.2.9' if child else span;rows=[x for x in p['route'] if norm(x['span'])==wanted]
 if len(rows)!=1:raise ValueError(f'{code} proposal lookup failed {span}')
 x=rows[0];challenge=False;claim='';remedy=''
 if code=='hebrew':challenge=child or x.get('disposition')=='hold';claim=f"The frozen Hebrew specialist surfaces {norm(x['span'])} rather than {span}: {x['rationale']}" if child else x.get('hold_question','');remedy=f"Retain {norm(x['span'])} as the surface, or require it automatically whenever {span} is retrieved." if child else alttext(x['rejected_alternatives'])
 elif code=='literary':challenge=span=='Mal.2.5-Mal.2.9';claim=f'The frozen literary specialist rates {span} high because its covenant comparison and verdict form a complete rhetorical panel.';remedy=f'Retain the {span} boundary at high rather than medium confidence.'
 else:challenge=x.get('disposition')=='hold';claim=x.get('hold_question','');remedy=alttext(x['rejected_alternatives'])
 pname={c:n for c,_r,n in ROLES}[code];refs=srefs(span,did)+[f"frozen_blind_proposal:reviews/Mal/{pname}:route:{x['id']}"]
 return {'verdict':'challenge' if challenge else 'supports','support':f"{x['deciding_marker_or_seam']} {x['rationale']}",'counterevidence':x['counterevidence'],'refs':refs,'position':{'proposal_decision_id':x['id'],'selected_span':norm(x['span']),'confidence':x['confidence'],'literary_form':x['literary_form'],'disposition':x['disposition']},'challenge':({'claim':claim,'proposed_remedy':remedy,'counterevidence':x['counterevidence']} if challenge else None)}
def hold_parts(u:dict[str,Any])->tuple[str|None,list[str]|None,str|None]:
 h=u.get('boss_hold_question')
 if not h:return None,None,None
 q=h['human_or_external_ai_question'];a=h['option_a']['treatment'];b=h['option_b']['treatment']
 if h['option_a'].get('requirements'):a+=f" Requirement: {h['option_a']['requirements']}"
 if h['option_b'].get('requirements'):b+=f" Requirement: {h['option_b']['requirements']}"
 return q,[a,b],h['requested_reviewer']
def make_appeal(u:dict[str,Any],active:dict[str,dict[str,Any]],byrole:dict[str,str],refs:list[Any])->dict[str,Any]|None:
 h=u.get('boss_hold_question')
 if not h:return None
 aid=h['appeal_id'];x=active[aid];q,opts,reviewer=hold_parts(u);assert q and opts and reviewer
 if aid=='T561-Mal-Hebrew-A01':role='original_language_translation_specialist';attempt='T561-Mal-Hebrew-Post-Ruling-v2';against=x['source_ruling_id'];reason=x['why_boss_reasoning_did_not_close_the_question'];unc=x['uncertainty'];parent=x['mandatory_parent']['span'];alts=[z['treatment'] for z in x['retrieval_options']];status=x['appeal_status']
 else:role='canonical_relations_retrieval_premortem_primary';attempt='T561-Mal-canonical-post-ruling-v2';against=x['boss_ruling_id'];reason=x['exact_retrieval_proof_text_risk'];unc=x['uncertainty'];parent=x['mandatory_parent'];alts=[x['option_a']['treatment'],x['option_b']['treatment']];status=x['status']
 if role not in byrole:raise ValueError(f'appeal lacks role challenge {aid}')
 return {'appeal_id':aid,'status':status,'question':q,'option_a':opts[0],'option_b':opts[1],'preserved_disagreement':reason,'appellant_attempt_id':attempt,'disagreement_with':against,'disputed_claim_id':byrole[role],'passage_context':parent,'evidence_refs':refs,'rationale':reason,'uncertainty':unc,'requested_next_reviewer':reviewer,'requested_alternative':alts,'mandatory_parent':parent,'forced_consensus':False}
def ledger_plan(packets:list[dict[str,Any]])->tuple[bytes,list[dict[str,Any]]]:
 p=REV/'appeal_ledger.jsonl';before=p.read_bytes();prefix=before[:PREFIX_BYTES]
 if len(before)<PREFIX_BYTES or shab(prefix)!=PREFIX_SHA or not prefix.endswith(b'\n') or not before.endswith(b'\n'):raise ValueError('Mal appeal-ledger prefix invariant failed')
 current={str(x.get('appeal_id','')) for x in rjl(p)};pairs=[(p,a) for p in packets for a in p['appeals']];ids={a['appeal_id'] for _p,a in pairs}
 if ids!=APPEAL_IDS:raise ValueError(f'wrong appeals {ids}')
 present=current&APPEAL_IDS
 if len(present) not in (0,2):raise ValueError('partial v2 appeal append')
 adds=[] if present else [{**a,'schema_version':'m7_mal_boundary_appeal.v2','book':'Mal','decision_id':p['decision_id'],'span':p['span'],'append_only':True,'candidate_only':True,'non_authorizing':True} for p,a in pairs]
 if len(adds) not in (0,2):raise ValueError('expected zero or two appeal additions')
 return before,adds

def build(post_path:Path|None)->tuple[dict[Path,tuple[str,Any]],dict[str,Any],bytes,list[dict[str,Any]]]:
 verify();route=rj(ROUTE);postmeta=rj(POST);boss=rj(BOSS);props={c:rj(REV/n) for c,_r,n in ROLES};responses={c:rj(REV/f'post_ruling_response_{c}_v2.json') for c in ('hebrew','literary','canonical')};units=route['route'];cnt=route['counts']
 if len(units)!=11 or cnt['accepted']!=9 or cnt['held']!=2 or cnt['confidence']!={'high':6,'medium':5} or cnt['mandatory_parent_relations']!=4 or cnt['dissent_relations']!=3:raise ValueError('route counts changed')
 if [u['chunk_index_in_book'] for u in units]!=list(range(1,12)):raise ValueError('route indices changed')
 if boss.get('adjudication_id')!='T561-Mal-fresh-boss-v2':raise ValueError('boss identity changed')
 if postmeta['summary']['opportunities_received']!=3 or postmeta.get('literary_zero_appeals',{}).get('confirmed') is not True or postmeta.get('literary_zero_appeals',{}).get('active_count')!=0:raise ValueError('appeal opportunity state changed')
 active={x['appeal_id']:x for x in postmeta['active_appeals']}
 if set(active)!=APPEAL_IDS or [len(responses[c].get('active_appeals',[])) for c in ('hebrew','literary','canonical')]!=[1,0,1]:raise ValueError('post-ruling appeal state changed')
 proc=route['procedural_source_hashes'];expect={'strategy':FROZEN['strategy'],'hebrew_proposal':FROZEN['blind_proposal_hebrew_textual_v2.json'],'literary_proposal':FROZEN['blind_proposal_literary_v2.json'],'canonical_proposal':FROZEN['blind_proposal_canonical_premortem_v2.json'],'fresh_boss':FROZEN['fresh_boss_adjudication_v2.json'],'hebrew_response':FROZEN['post_ruling_response_hebrew_v2.json'],'literary_response':FROZEN['post_ruling_response_literary_v2.json'],'canonical_response':FROZEN['post_ruling_response_canonical_v2.json'],'appeal_opportunities_file':FROZEN['post_ruling_appeal_opportunities_v2.json'],'boss_encoding_repair_receipt':FROZEN['fresh_boss_encoding_repair_receipt_v2.json']}
 for k,v in expect.items():
  if proc.get(k)!=v:raise ValueError(f'route binding changed {k}')
 report=rj(post_path) if post_path else None
 if report and report.get('verdict') not in ('pass','pass_with_holds'):raise ValueError('postcheck must use lowercase pass/pass_with_holds')
 allrefs,texts=inventory();pos={x:i for i,x in enumerate(allrefs)};coverage=[];chunks=[];stage=[]
 for n,u in enumerate(units,1):
  span=u['span'];a,b=span.split('-');cov=allrefs[pos[a]:pos[b]+1];coverage+=cov
  if len(cov)!=u['verse_count']:raise ValueError(f'verse count changed {span}')
  did=f'M7_sol-Mal-{n:03d}';held=u['boss_disposition']=='deferred_human_or_external_ai';q,opts,reviewer=hold_parts(u);parent=pspan(u);ms=f'{mt(a)}-{mt(b)}';obs=[{'ref':f'WEB:{cov[0]}','text':texts[cov[0]],'extent':'complete_verse','use':'opening_witness'}]
  if cov[-1]!=cov[0]:obs.append({'ref':f'WEB:{cov[-1]}','text':texts[cov[-1]],'extent':'complete_verse','use':'closing_witness'})
  align={'web_span':span,'oshb_span':ms,'uxlc_span':ms,'coordinate_system':'MT_WLC','crosswalk_status':'validated_web_mt_malachi_web_chapter_4_to_mt_chapter_3_plus_18' if a!=mt(a) or b!=mt(b) else 'validated_web_mt_malachi_same_coordinates','crosswalk_rules':{'WEB_Mal.4.1-Mal.4.6':'MT_Mal.3.19-Mal.3.24','other_WEB_coordinates':'same_as_MT'},'source_metadata_boundary_authority':False,'versification_crosswalk_is_evidence_only':True,'wlc_family_correlation_disclosed':True,'oshb_uxlc_are_independent_witnesses':False,'roots_or_etymology_are_not_meaning':True,'variants_select_preferred_reading':False,'authority':'translation_textual_order_and_form_evidence_only'}
  chunk={'model_id':'M7_sol','book':'Mal','span':span,'chunk_index_in_book':n,'working_title':u['title'],'literature_type_guess':u['literary_form'],'literary_form':u['literary_form'],'parent_literary_form':'context_hydrated_prophetic_disputation_parent' if u.get('mandatory_parents') else u['literary_form'],'parent_span':parent,'boundary_evidence_refs':[f'direct_read:eng-web:{span}',f'direct_read:oshb:{ms}',f'direct_read:uxlc:{ms}','book_strategy/Mal.md','reviews/Mal/decision_evidence_v2.jsonl','reviews/Mal/decision_relations.jsonl'],'strong_or_hebrew_tags_used':['direct_Biblical_Hebrew_prophetic_disputation_form_considered','WEB_Malachi_4_to_MT_Malachi_3_plus_18_crosswalk_evidence_only','roots_are_not_meaning','correlated_WLC_family_views_disclosed','later_canonical_reuse_is_not_boundary_authority'],'wj_or_red_letter_considered':False,'frontier_flag_considered':True,'confidence':u['confidence'],'decision_id':did,'deciding_marker_or_seam':u['deciding_marker_or_seam'],'boundary_rationale':u['rationale'],'rejected_alternative':u['rejected_alternative'],'counterevidence':u['counterevidence'],'defensible_basis':u['defensible_basis'],'confidence_basis':{'tier':u['confidence'],'marker_strength':'decision_specific_prophetic_disputation_paragraph_address_and_rhetorical_result_evidence','alternative_strength':'specialist_counterproposal_preserved','status_not_used_as_input':True},'review_revision':'m7-corrective-rereview-v2','review_status':'final_deferred_appeal' if held else 'candidate_review_complete','review_holds':[q] if held else [],'candidate_hold_state':'deferred_human_or_external_ai' if held else None,'candidate_hold_basis':({'kind':'retrieval_boundary_dispute','question':firstq(q),'options':opts,'mandatory_parent':parent} if held else None),'human_review_question':q if held else None,'human_review_route':reviewer if held else None,'candidate_internal_seams':u['internal_seams'],'non_authorizing':True,'candidate_only':True,'working_title_is_boundary_authority':False,'original_language_translation_holds':["Malachi's name/messenger relation, offering syntax, compressed Mal.2.15-16 language, messenger speaker shifts, day imagery, herem, paragraph markers, and WEB Mal.4 to MT Mal.3 versification remain translation and retrieval hot zones; roots, lemmas, and correlated WLC-family views are evidence only."],'cross_reference_holds':[u['proof_text_guard']],'red_team_premortem_holds':[u['counterevidence']],'convergence_defense':{'literary_form':u['literary_form'],'deciding_marker_or_seam':u['deciding_marker_or_seam'],'rejected_alternative':u['rejected_alternative'],'confidence':u['confidence'],'defensible_basis':u['defensible_basis'],'parent_span':parent,'source_observations':obs,'original_language_alignment':align}}
  chunks.append(chunk);stage.append((u,chunk,srefs(span,did)))
 if coverage!=allrefs or [x['chunk_index_in_book'] for x in chunks]!=list(range(1,12)):raise ValueError('exact coverage/index failure')
 if sum(x['candidate_hold_state'] is not None for x in chunks)!=2:raise ValueError('hold count changed')
 packets=[];evidence=[];roles={c:[] for c,_r,_n in ROLES};peers=[];bossrows=[];authorrows=[]
 for u,ch,refs in stage:
  n=ch['chunk_index_in_book'];did=ch['decision_id'];held=ch['candidate_hold_state'] is not None;reviews=[];cids=[];byrole={}
  for code,role,pname in ROLES:
   p=primary(code,u,props);chs=[]
   if p['challenge']:
    cid=f'{did}-{code.upper()}-CHALLENGE-01';cids.append(cid);byrole[role]=cid;chs=[{'challenge_id':cid,**p['challenge'],'source_refs':p['refs']}]
   rr={'reviewer_attempt_id':f'mal-v2-{code}-{n:03d}-specialist-high','reviewer_role':role,'role':role,'verdict':p['verdict'],'blind_to_other_primary_reviews':True,'evidence_only':True,'primary_evidence_provenance':'frozen_blind_proposal_only','frozen_blind_proposal':f'reviews/Mal/{pname}','frozen_blind_proposal_sha256':FROZEN[pname],'recorded_position':p['position'],'evidence_refs':p['refs'],'source_refs':p['refs'],'support':p['support'],'counterevidence':p['counterevidence'],'challenges':chs};reviews.append(rr);roles[code].append(rr)
  responses1=[{'challenge_id':cid,'disposition':'held_for_independent_resolution' if held else 'boss_overruled_with_dissent_preserved','rationale':u['rationale'],'rejected_alternative':u['rejected_alternative']} for cid in cids];appeal=make_appeal(u,active,byrole,refs);appeals=[appeal] if appeal else [];q,_o,reviewer=hold_parts(u)
  peer={'reviewer_attempt_id':f'mal-v2-peer-{n:03d}-crosscheck-high','reviewer_role':'adversarial_passage_crosscheck','status':'pass_with_hold' if held else 'pass','disputed_claim_ids':cids,'rationale':u['defensible_basis'],'counterevidence':u['counterevidence'],'source_refs':refs,'support_challenge_mix':{'support_count':sum(x['verdict']=='supports' for x in reviews),'challenge_count':sum(x['verdict']=='challenge' for x in reviews)}}
  resolution={'author_id':'M7_sol','author_attempt_id':f'mal-v2-boss-{n:03d}-sol-high','challenge_responses':responses1,'unresolved_claim_ids':cids if held else [],'rationale':u['rationale'],'counterevidence':u['counterevidence'],'rejected_alternative':u['rejected_alternative'],'outcome':'held_lower_confidence_for_independent_review' if held else 'accepted_candidate_after_role_specific_review','authority':'candidate_author_only'}
  cr=[{'challenge_id':x['challenge_id'],'ruling':x['disposition'],'rationale':x['rationale'],'rejected_alternative':x['rejected_alternative'],'forced_consensus':False} for x in responses1];br={'ruling_id':resolution['author_attempt_id'],'rationale':u['rationale'],'counterevidence':u['counterevidence'],'rejected_alternative':u['rejected_alternative'],'outcome':'hold_candidate' if held else 'accept_candidate','challenge_rulings':cr,'appeal_effect':'one_open_linked_appeal' if held else 'dissent_preserved_without_active_appeal','forced_consensus':False};h=rowsha(ch)
  packet={'schema_version':'m7_corrective_review_packet.v2','decision_id':did,'book':'Mal','span':ch['span'],'chunk_sha256':h,'chunk_content_sha256':h,'review_revision':'m7-corrective-rereview-v2','primary_reviews':reviews,'peer_crosscheck':peer,'sol_resolution':resolution,'appeals':appeals,'final_state':'held_lower_confidence' if held else 'accepted_candidate','human_review_question':q if held else None,'human_review_route':reviewer if held else None,'post_resolution_check':{'checker_attempt_id':f'mal-v2-post-{n:03d}-independent-checker','status':(('hold' if held else 'pass') if report else 'pending_independent_postcheck'),'evidence_refs':['reviews/Mal/post_resolution_check_v2.json'],'chunk_content_sha256':h},'independence_scope':INDEP,'non_authorizing':True,'boss_ruling':br}
  packets.append(packet);peers.append({'decision_id':did,**peer});bossrows.append({'decision_id':did,**br});authorrows.append({'decision_id':did,'author_attempt_id':resolution['author_attempt_id'],'challenge_responses':responses1,'all_challenges_answered_exactly_once':True,'candidate_only':True,'non_authorizing':True});evidence.append({'schema_version':'m7_mal_decision_evidence.v2','book':'Mal','decision_id':did,'span':ch['span'],'literary_form':u['literary_form'],'parent_literary_form':ch['parent_literary_form'],'parent_span':ch['parent_span'],'candidate_state':packet['final_state'],'confidence':u['confidence'],'confidence_basis':ch['confidence_basis'],'deciding_marker_or_seam':u['deciding_marker_or_seam'],'boundary_rationale':u['rationale'],'rejected_alternative':u['rejected_alternative'],'defensible_basis':u['defensible_basis'],'source_observations':ch['convergence_defense']['source_observations'],'original_language_alignment':ch['convergence_defense']['original_language_alignment'],'hold':appeal,'primary_reviews':reviews,'non_authorizing':True})
 allp=[r for p in packets for r in p['primary_reviews']];attempts={r['reviewer_attempt_id'] for r in allp};supports=sum(r['verdict']=='supports' for r in allp);challenges=sum(r['verdict']=='challenge' for r in allp);mix={c:{'supports':sum(x['verdict']=='supports' for x in roles[c]),'challenges':sum(x['verdict']=='challenge' for x in roles[c])} for c,_r,_n in ROLES};expected={'hebrew':{'supports':8,'challenges':3},'literary':{'supports':10,'challenges':1},'canonical':{'supports':10,'challenges':1}}
 if len(allp)!=33 or len(attempts)!=33 or supports!=28 or challenges!=5 or mix!=expected:raise ValueError(f'primary mix failure {mix}')
 claims=[c for r in allp for c in r['challenges']];answers=[x for p in packets for x in p['sol_resolution']['challenge_responses']];rulings=[x for p in packets for x in p['boss_ruling']['challenge_rulings']];ids=sorted(x['challenge_id'] for x in claims)
 if len(ids)!=5 or ids!=sorted(x['challenge_id'] for x in answers) or ids!=sorted(x['challenge_id'] for x in rulings):raise ValueError('challenge/response/ruling parity failed')
 blob=json.dumps(allp,ensure_ascii=False).lower()
 if any(x in blob for x in ('fresh_boss','fresh-boss','boss response','post-ruling','post_ruling','adjudicated_route','appeal_opportunities')):raise ValueError('later ruling material leaked into blind primary fields')
 for p in packets:
  if p['final_state']=='accepted_candidate' and not any(r['verdict']=='supports' for r in p['primary_reviews']):raise ValueError('accepted decision lacks support')
 byboss={u['decision_id']:f"M7_sol-Mal-{u['chunk_index_in_book']:03d}" for u in units};byspan={u['span']:f"M7_sol-Mal-{u['chunk_index_in_book']:03d}" for u in units};relations=[]
 for x in route['parent_relations']:relations.append({'schema_version':'m7_decision_relation.v2','note_id':x['relation_id'],'book':'Mal','relation_type':'mandatory_prophetic_context_hydration_parent','parent_span':x['parent_span'],'parent_literary_form':'linked_prophetic_disputation_parent','children':[byboss[y] for y in x['child_decision_ids']],'rationale':x['basis'],'hydration_rule':x['hydration_rule'],'mandatory_hydration':True,'boundary_authority':False,'non_authorizing':True})
 for x in route['dissent_relations']:
  raw=x.get('boss_decision_ids') or [x.get('boss_decision_id')];relations.append({'schema_version':'m7_decision_relation.v2','note_id':x['dissent_id'],'book':'Mal','relation_type':'preserved_specialist_dissent_without_forced_consensus','children':[byboss[y] for y in raw if y],'seam':x['seam'],'dissent_position':x['dissent_position'],'rationale':x['boss_response'],'counterevidence':x['counterevidence_preserved'],'appellant_role':x['source_role'],'appellant_status':x['appeal_status'],'boundary_authority':False,'forced_consensus':False,'non_authorizing':True})
 for aid,x in active.items():
  heb=aid=='T561-Mal-Hebrew-A01';children=[byspan['Mal.1.6-Mal.1.14']] if heb else [byspan['Mal.3.13-Mal.3.18'],byspan['Mal.4.1-Mal.4.3']];question=x['requested_question'] if heb else units[9]['boss_hold_question']['human_or_external_ai_question'];reason=x['why_boss_reasoning_did_not_close_the_question'] if heb else x['exact_retrieval_proof_text_risk'];status=x['appeal_status'] if heb else x['status'];relations.append({'schema_version':'m7_decision_relation.v2','note_id':aid,'book':'Mal','relation_type':'active_post_ruling_appeal_against_boss_treatment','children':children,'question':question,'rationale':reason,'status':status,'forced_consensus':False,'boundary_authority':False,'non_authorizing':True})
 if len(relations)!=9:raise ValueError('relation count failure')
 rolearts={}
 for code,role,pname in ROLES:
  aids=[a for a in APPEAL_IDS if (code=='hebrew' and 'Hebrew' in a) or (code=='canonical' and 'CAN-' in a)];rolearts[code]={'schema_version':'m7_mal_role_artifact.v2','book':'Mal','role':role,'decision_local_review_count':11,'reviews':roles[code],'blind_primary_artifact':f'reviews/Mal/{pname}','blind_primary_artifact_sha256':FROZEN[pname],'blind_primary_artifacts_remain_frozen':True,'post_ruling_active_appeals':len(aids),'active_appeal_ids':aids,'candidate_only':True,'non_authorizing':True}
 artifacts={CHUNKS:('jsonl',chunks),REV/'review_packets.jsonl':('jsonl',packets),REV/'decision_evidence_v2.jsonl':('jsonl',evidence),REV/'decision_relations.jsonl':('jsonl',relations),REV/'primary_hebrew_v2.json':('json',rolearts['hebrew']),REV/'corrective_specialist_hebrew_textual_v2.json':('json',rolearts['hebrew']),REV/'primary_literary_v2.json':('json',rolearts['literary']),REV/'corrective_specialist_literary_v2.json':('json',rolearts['literary']),REV/'canonical_premortem_v2.json':('json',rolearts['canonical']),REV/'corrective_specialist_canonical_premortem_v2.json':('json',rolearts['canonical']),REV/'peer_crosscheck_v2.json':('json',{'schema_version':'m7_mal_peer_crosscheck.v2','book':'Mal','reviews':peers,'candidate_only':True,'non_authorizing':True}),REV/'author_responses_v2.json':('json',{'schema_version':'m7_mal_author_responses.v2','book':'Mal','responses':authorrows,'challenge_count':5,'all_challenges_answered_exactly_once':True,'candidate_only':True,'non_authorizing':True}),REV/'boss_ruling_v2.json':('json',{'schema_version':'m7_mal_boss_ruling.v2','task_id':'T561','book':'Mal','route_count':11,'accepted':9,'held':2,'confidence':{'high':6,'medium':5},'boss_attempt_id':boss['adjudication_id'],'frozen_boss_adjudication_sha256':FROZEN['fresh_boss_adjudication_v2.json'],'rulings':bossrows,'challenge_ruling_count':5,'specialist_post_ruling_active_appeals':2,'forced_consensus':False,'candidate_only':True,'non_authorizing':True}),REV/'mesh_instruction_and_dissent_v2.json':('json',{'schema_version':'m7_mal_mesh_instruction_record.v2','task_id':'T561','roles':[x[1] for x in ROLES]+['boss_adjudicator','independent_post_resolution_checker'],'instructions':['blind read-only primaries','original-language and canonical relations are evidence only','larger coherent unit under tied evidence','boss answers every challenge without forcing consensus','post-ruling appeal opportunity for every specialist','true holds route to human or external AI'],'pre_materialization_redteam_bindings':{'mandatory_correction_overlay':FROZEN['fresh_boss_encoding_repair_receipt_correction_v2.json'],'clean_literary_redteam':FROZEN['independent_frozen_route_literary_redteam_v2.json'],'clean_source_redteam':FROZEN['independent_frozen_route_source_redteam_v2.json']},'active_appeal_ids':sorted(APPEAL_IDS),'candidate_only':True,'non_authorizing':True})}
 def data(p:Path)->bytes:
  kind,x=artifacts[p];return jlb(x) if kind=='jsonl' else jb(x,True)
 postart={'schema_version':'m7_post_resolution_check.v2','checker_attempt_id':report.get('checker_attempt_id') if report else 'pending-independent-malachi-postchecker','role':'fresh_read_only_post_resolution_checker','book':'Mal','status':report['verdict'] if report else 'pending_independent_postcheck','checked_decision_ids':[x['decision_id'] for x in chunks],'checker_attempt_ids':[f'mal-v2-post-{n:03d}-independent-checker' for n in range(1,12)],'checked_review_packets_sha256':shab(data(REV/'review_packets.jsonl')),'checked_chunks_sha256':shab(data(CHUNKS)),'checked_decision_relations_sha256':shab(data(REV/'decision_relations.jsonl')),'role_separated_checker_verdict_received':bool(report),'independent_model_verdict_received':False,'coverage':{'expected':55,'observed':len(coverage),'exact_ordered':coverage==allrefs},'accepted':9,'held':2,'postcheck_report_sha256':sha(post_path) if post_path else None,'postcheck_report':report,'candidate_only':True,'non_authorizing':True};artifacts[REV/'post_resolution_check_v2.json']=('json',postart)
 active_blob=b''.join((jlb(x) if k=='jsonl' else jb(x,True)) for k,x in artifacts.values()).decode('utf-8')
 if any(x in active_blob for x in ('\ufffd','Ã','â€','ðŸ','??')) or re.search(r'[A-Za-z]\?[A-Za-z]',active_blob):raise ValueError('encoding-loss pattern in planned active output')
 before,adds=ledger_plan(packets);summary={'book':'Mal','chunks':11,'coverage':55,'accepted':9,'held':2,'confidence':{'high':6,'medium':5},'primary_reviews':33,'supports':supports,'challenges':challenges,'role_verdict_mix':mix,'distinct_reviewer_attempt_ids':len(attempts),'author_responses':len(answers),'boss_challenge_rulings':len(rulings),'parent_relations':4,'dissent_relations':3,'appeal_relations':2,'active_appeals':2,'appeal_ledger_bytes_before':len(before),'appeal_ledger_rows_planned':len(adds),'postcheck':postart['status'],'in_memory_depth_checks':'pass','encoding_loss_patterns':0,'planned_hashes':{'chunks':shab(data(CHUNKS)),'packets':shab(data(REV/'review_packets.jsonl')),'evidence':shab(data(REV/'decision_evidence_v2.jsonl')),'relations':shab(data(REV/'decision_relations.jsonl')),'boss':shab(data(REV/'boss_ruling_v2.json'))}}
 return artifacts,summary,before,adds
def materialize(post:Path|None,dry:bool)->dict[str,Any]:
 arts,summary,before,adds=build(post)
 if dry:return {'dry_run':True,'writes':0,**summary}
 for p,(kind,x) in arts.items():wjl(p,x) if kind=='jsonl' else wj(p,x)
 if adds:
  with (REV/'appeal_ledger.jsonl').open('ab') as h:h.write(jlb(adds))
 after=(REV/'appeal_ledger.jsonl').read_bytes()
 if not after.startswith(before) or shab(after[:PREFIX_BYTES])!=PREFIX_SHA:raise ValueError('ledger append invariant failed')
 return {'dry_run':False,'writes':len(arts)+(1 if adds else 0),**summary,'appeal_ledger_rows_appended':len(adds),'hashes':{'chunks':sha(CHUNKS),'packets':sha(REV/'review_packets.jsonl'),'evidence':sha(REV/'decision_evidence_v2.jsonl'),'relations':sha(REV/'decision_relations.jsonl'),'boss':sha(REV/'boss_ruling_v2.json'),'post_resolution':sha(REV/'post_resolution_check_v2.json')}}
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument('--postcheck-report',type=Path);ap.add_argument('--dry-run',action='store_true');a=ap.parse_args();print(json.dumps(materialize(a.postcheck_report,a.dry_run),ensure_ascii=False,indent=2));return 0
if __name__=='__main__':raise SystemExit(main())