#!/usr/bin/env python3
"""Refresh the generated status block in docs/bible-chunking-campaign/README.md.

Run from anywhere:  python -B docs/bible-chunking-campaign/refresh_campaign_status.py

Reads (read-only):
  .ai/scratch/multi_model_bible_chunking/M8_fable/marathon_progress.yaml
  .ai/scratch/multi_model_bible_chunking/M8_fable/CURRENT_STATE.v1.json
  .ai/scratch/multi_model_bible_chunking/M8_fable/whole_bible_chunk_map.jsonl
  .ai/scratch/multi_model_bible_chunking/M8_fable/receipts/<Book>_completion.json
  .ai/scratch/multi_model_bible_chunking/M8_fable/low_confidence_register.jsonl
  .ai/scratch/multi_model_bible_chunking/M8_fable/ERROR_PATTERN_LEDGER.v1.md

Writes ONLY the region between the BOOK_STATUS_START / BOOK_STATUS_END markers in
README.md. Refuses (exit 2) if either marker is missing or out of order.
Standard library only. Nothing here is a review verdict; it only reports counts
that the campaign's own state files already record.
"""
import json
import os
import sys

sys.dont_write_bytecode = True

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
M8 = os.path.join(REPO, ".ai", "scratch", "multi_model_bible_chunking", "M8_fable")
README = os.path.join(HERE, "README.md")
START = "<!-- BOOK_STATUS_START -->"
END = "<!-- BOOK_STATUS_END -->"

# Canonical 66-book order and IDs, as used by the repo's own scripts
# (for example scripts/add_b01_challenge_appeal_ledgers.py: BOOKS).
BOOKS = [
    "Gen", "Exod", "Lev", "Num", "Deut", "Josh", "Judg", "Ruth", "1Sam", "2Sam",
    "1Kgs", "2Kgs", "1Chr", "2Chr", "Ezra", "Neh", "Esth", "Job", "Ps", "Prov",
    "Eccl", "Song", "Isa", "Jer", "Lam", "Ezek", "Dan", "Hos", "Joel", "Amos",
    "Obad", "Jonah", "Mic", "Nah", "Hab", "Zeph", "Hag", "Zech", "Mal", "Matt",
    "Mark", "Luke", "John", "Acts", "Rom", "1Cor", "2Cor", "Gal", "Eph", "Phil",
    "Col", "1Thess", "2Thess", "1Tim", "2Tim", "Titus", "Phlm", "Heb", "Jas",
    "1Pet", "2Pet", "1John", "2John", "3John", "Jude", "Rev",
]
NT_START = BOOKS.index("Matt")


def read_text(path):
    with open(path, "r", encoding="utf-8", newline="") as fh:
        return fh.read()


def parse_progress(path):
    """Minimal reader for marathon_progress.yaml (flat keys + book_completion map)."""
    out = {"complete": {}, "scalars": {}}
    in_bc = False
    current = None
    for raw in read_text(path).splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        line = raw.strip()
        if indent == 0:
            in_bc = line == "book_completion:"
            current = None
            if not in_bc and ":" in line:
                key, _, val = line.partition(":")
                out["scalars"][key.strip()] = val.strip()
        elif in_bc and indent == 2 and line.endswith(":"):
            current = line[:-1]
        elif in_bc and indent >= 4 and current and line.startswith("status:"):
            out["complete"][current] = line.split(":", 1)[1].strip()
    return out


def count_jsonl(path):
    n = 0
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            if line.strip():
                n += 1
    return n


def chunk_map_counts(path):
    counts = {}
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            book = json.loads(line).get("book")
            counts[book] = counts.get(book, 0) + 1
    return counts


def latest_ledger_entry(path):
    last = None
    for line in read_text(path).splitlines():
        if line.startswith("## E-"):
            token = line[3:].split()[0]
            if token[2:].isdigit():
                last = token
    return last


def build_block():
    prog = parse_progress(os.path.join(M8, "marathon_progress.yaml"))
    state = json.loads(read_text(os.path.join(M8, "CURRENT_STATE.v1.json")))
    cmap = chunk_map_counts(os.path.join(M8, "whole_bible_chunk_map.jsonl"))
    sc = prog["scalars"]
    total = int(sc["books_total"])
    declared = int(sc["books_completed"])
    current = sc.get("current_book", "")
    closed = [b for b in BOOKS if prog["complete"].get(b) == "complete"]
    warns = []
    if len(BOOKS) != total:
        warns.append("book list length %d != books_total %d" % (len(BOOKS), total))
    if len(closed) != declared:
        warns.append("books_completed %d != complete entries %d" % (declared, len(closed)))
    lcr = count_jsonl(os.path.join(M8, "low_confidence_register.jsonl"))
    ledger_last = latest_ledger_entry(os.path.join(M8, "ERROR_PATTERN_LEDGER.v1.md"))
    map_rows = sum(cmap.values())

    lines = []
    lines.append("_Generated by `refresh_campaign_status.py`; do not edit by hand. State file generated at "
                 "`%s`; phase marker `%s`._" % (state.get("generated_at", "unknown"), state.get("phase", "unknown")))
    lines.append("")
    lines.append("- **Books closed:** %d of %d (campaign status `%s`)" % (len(closed), total, sc.get("marathon_status", "unknown")))
    lines.append("- **Book in progress:** `%s` (not closed)" % current)
    lines.append("- **Candidate chunks in the whole-Bible map:** %d rows across %d books" % (map_rows, len(cmap)))
    lines.append("- **Low-confidence register rows:** %d" % lcr)
    lines.append("- **Latest error-pattern ledger entry:** %s" % ledger_last)
    lines.append("- Sources: `marathon_progress.yaml`, `CURRENT_STATE.v1.json`, `whole_bible_chunk_map.jsonl`, "
                 "`low_confidence_register.jsonl`, `ERROR_PATTERN_LEDGER.v1.md`, and `receipts/<Book>_completion.json` "
                 "(all under `.ai/scratch/multi_model_bible_chunking/M8_fable/`).")
    warn_at = len(lines)
    lines.append("")
    lines.append("| # | Book | Part | Status | Candidate chunks | Close receipt |")
    lines.append("|---|------|------|--------|------------------|---------------|")
    for i, b in enumerate(BOOKS, 1):
        part = "OT" if i - 1 < NT_START else "NT"
        rpath = os.path.join(M8, "receipts", "%s_completion.json" % b)
        has_receipt = os.path.isfile(rpath)
        if b in closed:
            status = "closed"
        elif b == current:
            status = "in progress"
        else:
            status = "not started"
        chunks = cmap.get(b)
        cell = str(chunks) if chunks else "-"
        if b in closed:
            rc = json.loads(read_text(rpath)).get("chunks") if has_receipt else None
            if rc is not None and chunks != rc:
                cell = "%s (receipt says %s)" % (cell, rc)
                warns.append("%s chunk-count mismatch" % b)
            if not has_receipt:
                warns.append("%s closed without receipt file" % b)
        receipt = "yes" if has_receipt else "-"
        lines.append("| %d | %s | %s | %s | %s | %s |" % (i, b, part, status, cell, receipt))
    if warns:
        lines.insert(warn_at, "- **Consistency warnings:** " + "; ".join(warns))
    summary = "refresh_campaign_status: %d/%d books closed, in progress %s, %d map rows, %d low-confidence rows, ledger %s, %d warnings" % (
        len(closed), total, current, map_rows, lcr, ledger_last, len(warns))
    return "\n".join(lines), summary


def main():
    text = read_text(README)
    s = text.find(START)
    e = text.find(END)
    if s < 0 or e < 0 or e < s:
        print("REFUSED: README.md must contain %s then %s" % (START, END))
        return 2
    block, summary = build_block()
    new_text = text[: s + len(START)] + "\n" + block + "\n" + text[e:]
    if new_text != text:
        with open(README, "w", encoding="utf-8", newline="") as fh:
            fh.write(new_text)
    print(summary)
    return 0


if __name__ == "__main__":
    sys.exit(main())
