#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
M=Path(__file__).resolve().parents[1]; B='Joel'; E='be30094141eeb56a1a5e9eed20e892076896cd04b1c024a11e3bfe6062942888'; S=('low_confidence_register.jsonl','frontier_escalation_queue.jsonl','atlas_candidate_feed.jsonl')
def jl(p): return [json.loads(x) for x in p.read_text(encoding='utf-8').splitlines() if x.strip()]
def req(c,m):
 if not c: raise SystemExit('FAIL: '+m)
cp=M/'book_chunks'/B/'chunks.jsonl'; r=M/'reviews'/B; ch=jl(cp); pk=jl(r/'review_packets.jsonl'); rel=jl(r/'decision_relations.jsonl'); sha=hashlib.sha256(cp.read_bytes()).hexdigest(); req(sha==E,'sha'); req(len(ch)==10 and [x['chunk_index_in_book'] for x in ch]==list(range(1,11)),'chunks/indices'); req(all(x['confidence']=='low' and x['candidate_hold_state']=='deferred_human_or_external_ai' and x['candidate_only'] and x['non_authorizing'] for x in ch),'holds/authority'); req(len(pk)==10,'packets')
cs=[c for p in pk for pr in p['primary_reviews'] for c in pr['challenges']]; ids=[x['challenge_id'] for x in cs]; peer=[x for p in pk for x in p['peer_crosscheck']['disputed_claim_ids']]; resp=[x for p in pk for x in p['sol_resolution']['challenge_responses']]; req(len(ids)==len(set(ids))==30,'challenges'); req(sorted(peer)==sorted(ids)==sorted(x['challenge_id'] for x in resp),'parity'); req(all(p['boss_ruling']['outcome']=='retain_larger_low' and not p['boss_ruling']['forced_consensus'] for p in pk),'boss'); aps=[x for p in pk for x in p['appeals']]; req(len(aps)==10 and all(x['status']=='unresolved_append_only' for x in aps),'appeals'); req(len(rel)==10 and all(x['non_authorizing'] and not x['boundary_authority'] for x in rel),'relations')
for n in S: req(len([x for x in jl(M/n) if x.get('book')==B])==10,n)
inc=json.loads((r/'independence_incident_v1.json').read_text(encoding='utf-8')); req(inc['clean_blind_primary_count']==2 and not inc['qualified_audit']['counts_as_uncontaminated_blind_vote'] and not inc['failed_fresh_rerun']['counts_as_evidence'],'role accounting')
pe=json.loads((r/'peer_crosscheck_evidence_v1.json').read_text(encoding='utf-8')); req(pe.get('frozen_chunks_sha256')==E or pe.get('frozen_candidate',{}).get('sha256')==E,'peer sha'); d=pe.get('decision_challenges') or pe.get('challenges') or []; req(len(d)==10,'peer challenges'); ra=pe.get('role_accounting',{}); req(ra.get('valid_blind_primary_count')==2,'peer clean count'); req(ra.get('qualified_nonvoting_hebrew_audit',{}).get('counts_as_uncontaminated_blind_vote') is False,'peer Hebrew nonvote'); req(ra.get('failed_fresh_hebrew_serialization',{}).get('counts_as_evidence') is False,'peer failed rerun'); req(pe.get('forced_consensus') is False or pe.get('consensus_policy',{}).get('forced_consensus') is False,'peer consensus')
by={x['decision_id']:x['span'] for x in ch}; hard={'M7_sol-Joel-003':'Joel.1.13-Joel.1.20','M7_sol-Joel-004':'Joel.2.1-Joel.2.11','M7_sol-Joel-005':'Joel.2.12-Joel.2.17','M7_sol-Joel-006':'Joel.2.18-Joel.2.27','M7_sol-Joel-007':'Joel.2.28-Joel.2.32','M7_sol-Joel-008':'Joel.3.1-Joel.3.8','M7_sol-Joel-009':'Joel.3.9-Joel.3.16','M7_sol-Joel-010':'Joel.3.17-Joel.3.21'}; req(all(by[k]==v for k,v in hard.items()),'hard spans')
print(json.dumps({'verdict':'PASS','chunks_sha256':sha,'chunks':10,'formal_challenges':30,'appeals':10,'relations':10,'clean_blind_primaries':2,'qualified_hebrew_nonvote':True,'failed_fresh_rerun_evidence':False,'hard_spans':hard,'forced_consensus':False,'non_authorizing':True},sort_keys=True))
