from __future__ import annotations
import json
from pathlib import Path
M=Path(__file__).resolve().parents[1];R=M/'reviews'/'Titus'
def load(n):return json.loads((R/n).read_text(encoding='utf-8-sig'))
def dump(n,o):(R/n).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def readj(n):return [json.loads(x) for x in (R/n).read_text(encoding='utf-8-sig').splitlines() if x.strip()]
def writej(n,rs):(R/n).write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in rs),encoding='utf-8',newline='\n')
def ids(a,b):return [f'M7_sol-Titus-{i:03d}' for i in range(a,b+1)]
specs=[
('F01',ids(1,3),'Prescript, qualification function, opponent register, quotation, rebuke, and confession/works close retain internal routes.',['1:1-3|1:4','1:5|1:6-9','1:5-6|1:7-9','1:10-11|1:12-14|1:15-16','1:10-11|1:12-16','1:10-14|1:15-16'],['1:1-9','1:5-16','1:1-16','1:10-2:10'],['presbyterous/episkopon','mias gynaikos aner','quotation attribution','clean/defiled conscience','no ethnic endorsement or office policy'],'RN-TITUS-001'),
('F02',ids(4,5),'Selected 2:1-10 is coherent, while two group-register units and multiple grace-ground routes remain coequal.',['2:1-2|2:3-5','2:1-5|2:6-10','2:6-8|2:9-10','2:1|2:2-5|2:6-8|2:9-10','2:11-14|2:15','2:11-12|2:13-14|2:15'],['1:10-2:10','2:1-10','2:1-15','2:11-3:8'],['group-list parallelism','2:5 pressure','household/status terms','tou megalou theou kai soteros','no gender/household/labor policy or doctrine'],'RN-TITUS-002'),
('F03',ids(6,6),'Selected 3:1-8 is coherent but has the strongest under-segmentation pressure.',['3:1-2|3:3-7|3:8','3:1-3|3:4-8','3:4-7|3:8','3:1-2|3:3|3:4-7|3:8'],['3:1-8','2:11-3:8','3:1-11','3:1-15'],['civic/reminder scope','former/now contrast','saving/regeneration/renewal chain','faithful-saying scope','no civic policy or salvation doctrine'],'RN-TITUS-003'),
('F04',ids(7,7),'Controversy types form one warning list, while the person-warning procedure has a changed-object seam.',['3:9|3:10-11'],['3:9-11','3:1-11','3:9-15','3:1-15'],['hairetikos anthropos','first/second warning','self-condemnation syntax','no later technical label or discipline policy'],'RN-TITUS-004'),
('F05',ids(8,9),'Selected 3:12-14|3:15 is marked, while 3:12-15 remains a coequal complete closing register.',['3:12|3:13|3:14|3:15','3:12-13|3:14|3:15','3:12|3:13-14|3:15','3:15a|3:15b|3:15c'],['3:12-14|3:15','3:12-15','3:9-15','3:1-15'],['Nicopolis/winter language','travel/person register','provisioning/needs purpose','plural grace','no biography/chronology/witness selection'],'RN-TITUS-005')]
f=[]
for code,dids,claim,fine,large,holds,rn in specs:f.append({'challenge_id':f'TITUS-PEER-{code}','decision_ids':dids,'claim':claim,'exact_finer_routes':fine,'exact_larger_routes':large,'unresolved_holds':holds,'evidence_refs':['book_chunks/Titus/chunks.jsonl','reviews/Titus/blind_proposal_greek_textual_v1.json','reviews/Titus/blind_proposal_literary_v1.json','reviews/Titus/blind_proposal_canonical_premortem_v1.json',f'decision_relations.jsonl#{rn}'],'proposed_remedy':'retain current unit(s) LOW and every route append-only for human or external-AI adjudication','verdict':'material_challenge','status':'deferred_human_or_external_ai','forced_consensus':False,'non_authorizing':True})
peer=load('peer_crosscheck_v1.json');peer.update(attempt_id='titus-peer-crosscheck-20260724-d',reviewer_role='independent_peer_red_team_sol_high',status='pass_with_material_holds',macro_material_challenge_families=f,current_boundary_verdict='all_nine_defensible_only_as_LOW_deferred_candidates',highest_undersegmentation_pressure=['M7_sol-Titus-004','M7_sol-Titus-006'],promotion_verdict='blocked_pending_external_or_human_cross_model_review',forced_consensus=False,shared_model_substrate=True,counts_as_cross_model_independent_vote=False,non_authorizing=True);peer['disputed_claim_ids']=list(dict.fromkeys(peer.get('disputed_claim_ids',[])+[x['challenge_id'] for x in f]));dump('peer_crosscheck_v1.json',peer)
boss=load('boss_ruling_v1.json')
for x in f:boss['challenge_responses'].append({'challenge_id':x['challenge_id'],'decision_ids':x['decision_ids'],'author_response':'Accept the challenge. Retain the current larger-coherence unit(s) LOW; preserve all routes and holds append-only; defer selection.','disposition':'hold_larger_unit_deferred_human_or_external_ai','appeal_preserved':True,'authority':'candidate_author_only'})
boss['unresolved_claim_ids']=list(dict.fromkeys(boss.get('unresolved_claim_ids',[])+[x['challenge_id'] for x in f]));boss.update(peer_ruling='all five macro challenges preserved; no ethnic endorsement, witness, authorship, chronology, policy, doctrine, canon, or theology selection',external_or_human_review_still_required=True,forced_consensus=False,non_authorizing=True);dump('boss_ruling_v1.json',boss)
by={d:x for x in f for d in x['decision_ids']};ps=readj('review_packets.jsonl')
for p in ps:
 x=by[p['decision_id']];p['span_specific_peer_challenge']={'challenge_id':x['challenge_id'],'claim':x['claim'],'exact_finer_routes':x['exact_finer_routes'],'exact_larger_routes':x['exact_larger_routes'],'unresolved_holds':x['unresolved_holds'],'status':'deferred_human_or_external_ai','non_authorizing':True}
writej('review_packets.jsonl',ps);print(json.dumps({'families':len(f),'boss_responses':len(boss['challenge_responses']),'packets':len(ps)}))