from __future__ import annotations
import json
from pathlib import Path
M=Path(__file__).resolve().parents[1];R=M/'reviews'/'1Tim'
def load(n):return json.loads((R/n).read_text(encoding='utf-8-sig'))
def dump(n,o):(R/n).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def readj(n):return [json.loads(x) for x in (R/n).read_text(encoding='utf-8-sig').splitlines() if x.strip()]
def writej(n,rs):(R/n).write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in rs),encoding='utf-8',newline='\n')
def ids(a,b):return [f'M7_sol-1Tim-{i:03d}' for i in range(a,b+1)]
specs=[
('F01',ids(1,3),'Prescript atomization, charge-purpose attachment, law-list closure, and 1:11 attachment remain unsettled.',['1:1|1:2','1:3-4|1:5-7','1:8|1:9-10|1:11','1:8|1:9-11'],['1:3-11','1:3-17','1:1-20'],['heterodidaskalein','command-love-conscience-faith linkage','vice-list grammar','entrusted-message syntax'],'RN-1TIM-001'),
('F02',ids(4,5),'Faithful-saying and doxology closure permit finer units while the renewed charge may remain in a 1:12-20 movement.',['1:12-14|1:15-16|1:17','1:12-16|1:17','1:18-19|1:20'],['1:12-20','1:8-17','1:1-20'],['mercy linkage','faithful saying','prophetic references','warfare and conscience imagery'],'RN-1TIM-002'),
('F03',ids(6,7),'The 2:8-15 conduct-ground chain is coherent but materially supports multiple addressee and ground routes.',['2:1-2|2:3-7','2:1-4|2:5-7','2:8|2:9-10|2:11-15','2:8-10|2:11-15','2:8|2:9-15'],['2:1-8','2:8-15','2:1-3:16'],['boulomai','addressee scope','hesychia','authentein','creation/deception grounds','childbearing/salvation wording'],'RN-1TIM-003'),
('F04',ids(8,10),'Qualification lists remain functional wholes while saying, class, 3:11, purpose, confession, and textual seams stay live.',['3:1|3:2-7','3:8-10|3:11|3:12-13','3:8-10|3:11-13','3:14-15|3:16'],['3:1-13','3:1-16','2:8-3:13','2:1-3:16'],['episkope','household analogies','diakonous','gynaikas','office identity/eligibility','confession lineation','hos/theos'],'RN-1TIM-004'),
('F05',ids(11,12),'Warning and creation response cohere; the instruction parent retains competing imperative, saying, gift, and perseverance seams.',['4:1-3|4:4-5','4:6-8|4:9-11','4:6-10|4:11-16','4:6-11|4:12-16','4:12-13|4:14-16'],['4:1-16'],['reported Spirit speech','agent/source ambiguity','faithful-saying scope','training metaphor','gift/prophecy/laying-on language'],'RN-1TIM-005'),
('F06',ids(13,13),'The 5:1-16 parent is plausible but conceals address-class, widow-category, enrollment, younger-widow, and allocation seams.',['5:1-2|5:3-16','5:3-8|5:9-16','5:3-10|5:11-16','5:3-8|5:9-10|5:11-15|5:16'],['5:1-16','5:1-6:2'],['widow category shifts','age and conduct criteria','household obligation','5:16 addressee and burden scope'],'RN-1TIM-006'),
('F07',ids(14,15),'Elder counsel retains citation, procedure, caution, health-aside, disclosure seams, and the 6:2b backward/forward hinge.',['5:17-18|5:19-22|5:23|5:24-25','5:17-21|5:22-25','5:17-22|5:23-25','6:1|6:2a|6:2b'],['5:17-25','5:17-6:2','5:1-6:2','6:2b-6:10'],['honor/pay citations','accusation/rebuke audience','laying-on/participation','health aside','visible/hidden deeds','master-address syntax'],'RN-1TIM-007'),
('F08',ids(16,19),'The close has real contrast, vocative, confession/doxology, rich-address, deposit, and grace seams.',['6:3-5|6:6-8|6:9-10','6:3-5|6:6-10','6:11-12|6:13-14|6:15-16','6:11-14|6:15-16','6:17|6:18-19','6:20|6:21'],['6:1-10','6:3-16','6:11-19','6:17-21','6:11-21','6:3-21','6:1-21'],['heterodidaskalei','6:5 textual pressure','gain/contentment syntax','money-love maxim','confession/appearing horizon','deposit and falsely named knowledge','plural grace'],'RN-1TIM-008')]
families=[]
for code,dids,claim,small,large,holds,rn in specs:
 families.append({'challenge_id':f'1TIM-PEER-{code}','decision_ids':dids,'claim':claim,'exact_finer_routes':small,'exact_larger_routes':large,'unresolved_holds':holds,'evidence_refs':['book_chunks/1Tim/chunks.jsonl','reviews/1Tim/blind_proposal_greek_textual_v1.json','reviews/1Tim/blind_proposal_literary_v1.json','reviews/1Tim/blind_proposal_canonical_premortem_v1.json',f'decision_relations.jsonl#{rn}'],'proposed_remedy':'retain current larger-coherence unit(s) at LOW, preserve all exact routes append-only, and defer selection to human or external AI','verdict':'material_challenge','status':'deferred_human_or_external_ai','forced_consensus':False,'non_authorizing':True})
peer=load('peer_crosscheck_v1.json');peer.update(attempt_id='1tim-peer-crosscheck-20260724-d',reviewer_role='independent_peer_red_team_sol_high',status='pass_with_holds',macro_material_challenge_families=families,current_boundary_verdict='all_19_defensible_only_as_LOW_deferred_candidates',highest_undersegmentation_pressure=['M7_sol-1Tim-007','M7_sol-1Tim-009','M7_sol-1Tim-012','M7_sol-1Tim-013','M7_sol-1Tim-014','M7_sol-1Tim-015','M7_sol-1Tim-019'],promotion_verdict='blocked_pending_external_or_human_cross_model_review',forced_consensus=False,shared_model_substrate=True,counts_as_cross_model_independent_vote=False,non_authorizing=True);peer['disputed_claim_ids']=list(dict.fromkeys(peer.get('disputed_claim_ids',[])+[f['challenge_id'] for f in families]));dump('peer_crosscheck_v1.json',peer)
boss=load('boss_ruling_v1.json')
for f in families:boss['challenge_responses'].append({'challenge_id':f['challenge_id'],'decision_ids':f['decision_ids'],'author_response':'Accept the material challenge. Retain the current larger-coherence unit(s) at LOW, preserve every finer and larger route and semantic/textual hold append-only, and defer any selection.','disposition':'hold_larger_unit_deferred_human_or_external_ai','appeal_preserved':True,'authority':'candidate_author_only'})
boss['unresolved_claim_ids']=list(dict.fromkeys(boss.get('unresolved_claim_ids',[])+[f['challenge_id'] for f in families]));boss.update(peer_ruling='all eight macro challenges preserved; no witness, reading, authorship, history, office, gender, household, discipline, economic, medical, doctrinal, canonical, or theological selection',external_or_human_review_still_required=True,forced_consensus=False,non_authorizing=True);dump('boss_ruling_v1.json',boss)
byid={did:f for f in families for did in f['decision_ids']};packets=readj('review_packets.jsonl')
for p in packets:
 f=byid[p['decision_id']];p['span_specific_peer_challenge']={'challenge_id':f['challenge_id'],'claim':f['claim'],'exact_finer_routes':f['exact_finer_routes'],'exact_larger_routes':f['exact_larger_routes'],'unresolved_holds':f['unresolved_holds'],'status':'deferred_human_or_external_ai','non_authorizing':True}
writej('review_packets.jsonl',packets);print(json.dumps({'families':len(families),'boss_responses':len(boss['challenge_responses']),'packets':len(packets)}))