import json
from pathlib import Path
root=Path(__file__).resolve().parents[1];rev=root/'reviews'/'1Thess';peer=json.loads((rev/'peer_crosscheck_v1.json').read_text(encoding='utf-8-sig'));boss=json.loads((rev/'boss_ruling_v1.json').read_text(encoding='utf-8-sig'));items=[]
for c in peer['macro_material_challenge_families']:items.append({'id':c['family_id'],'family':c['family_id'],'ids':c['decision_ids'],'passage':c['envelope'],'claim':c['material_challenge'],'alts':c['exact_alternatives']})
for key,cid,fam,dids,claim in [('four_route_2_14_16_test','1TH-PC-2-14-16','1 Thessalonians 2:14-16 four-route rhetorical pressure',['M7_sol-1Thess-005','M7_sol-1Thess-006'],'All four exact rhetoric/separation routes remain viable; collective identity, guilt and history decide no boundary.'),('three_route_4_13_5_11_test','1TH-PC-4-13-5-11','1 Thessalonians 4:13-5:11 three-route cross-chapter pressure',['M7_sol-1Thess-012','M7_sol-1Thess-013'],'All three consolation/vigilance routes remain viable; event sequence, chronology, timetable and theology decide no seam.'),('close_5_12_28_test','1TH-PC-5-12-28','1 Thessalonians 5:12-28 four-route close pressure',['M7_sol-1Thess-014','M7_sol-1Thess-015','M7_sol-1Thess-016'],'All four community-imperative and closing routes remain viable; office, ethics and text theories decide no seam.')]:
 p=peer[key];items.append({'id':cid,'family':fam,'ids':dids,'passage':p['span'],'claim':claim,'alts':p['exact_routes']})
g=peer['global_textual_translation_speaker_collective_identity_timetable_family'];items.append({'id':g['family_id'],'family':'global textual translation speaker collective-identity and timetable hot zones','ids':[f'M7_sol-1Thess-{i:03d}' for i in range(1,17)],'passage':'; '.join(g['spans']),'claim':'All witness, reading, rendering, punctuation, speaker, opponent, collective identity, history, chronology and timetable questions remain unresolved evidence; the frozen route selects none.','alts':['retain every frozen seam with all hot-zone flags deferred','retain each larger macro parent with all flags deferred']})
x=peer['cross_chapter_and_larger_unit_family'];items.append({'id':x['family_id'],'family':'cross-chapter mission consolation vigilance and close continuity','ids':[f'M7_sol-1Thess-{i:03d}' for i in range(5,17)],'passage':'; '.join(x['larger_parents']),'claim':'Cross-chapter mission and consolation/vigilance plus closing alternatives remain visible; chapter scaffolds and later use decide no seam.','alts':x['exact_alternatives']})
def route(a):
 if isinstance(a,str):return a
 return a.get('route_id','route')+': '+' + '.join(a.get('ordered_spans',[]))
responses=[];rulings=[]
for n,c in enumerate(items,1):
 alts=[route(a) for a in c['alts']];ids=c['ids']
 responses.append({'challenge_id':c['id'],'decision_id':ids[0],'affected_decision_ids':ids,'source':'peer_crosscheck_v1','family':c['family'],'passage':c['passage'],'challenge':c['claim'],'exact_alternatives':alts,'author_response':'Material challenge accepted for explicit preservation. Retain the frozen route LOW while every finer/larger route, textual/translation/speaker hot zone, collective-identity question, cross-chapter sequence, and historical/apocalyptic appeal remains append-only and deferred. No witness, reading, punctuation, speaker, opponent, collective guilt, persecution history, chronology, timetable, election, resurrection, wrath, ethics, office, charismatic practice, theology, or canon ruling is selected.','disposition':'hold_frozen_route_and_all_alternatives_deferred_human_or_external_ai','appeal_preserved_append_only':True,'confidence':'LOW','forced_consensus':False,'authority':'candidate_author_only'})
 rulings.append({'ruling_id':f'1TH-BOSS-SPEC-{n:03d}','challenge_id':c['id'],'family':c['family'],'decisions':ids,'passage':c['passage'],'disposition':'retain frozen route and preserve: '+' | '.join(alts),'basis':'Material challenge sustained: '+c['claim'],'confidence':'LOW','unresolved_route':'deferred_human_or_external_ai','forced_consensus':False})
boss['peer_challenge_responses']=responses;boss['specific_boss_rulings']=rulings;boss['peer_crosscheck_evidence']='peer_crosscheck_v1.json';boss['boss_post_peer_ruling_status']='pass_with_holds_all_peer_challenges_answered_and_appeals_preserved';boss['unresolved_claim_ids']=sorted(set((boss.get('unresolved_claim_ids') or [])+[i for c in items for i in c['ids']]));boss['accepted_decision_count']=0;boss['held_decision_count']=16;boss['forced_consensus']=False;boss['external_or_human_review_still_required']=True;boss['non_authorizing']=True
(rev/'boss_ruling_v1.json').write_text(json.dumps(boss,ensure_ascii=False,separators=(',',':')),encoding='utf-8');print(json.dumps({'peer_challenges':len(items),'responses':len(responses),'rulings':len(rulings),'held':16}))