from __future__ import annotations
import json
from pathlib import Path
M=Path(__file__).resolve().parents[1];R=M/'reviews'/'2Tim'
def load(n):return json.loads((R/n).read_text(encoding='utf-8-sig'))
def dump(n,o):(R/n).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def readj(n):return [json.loads(x) for x in (R/n).read_text(encoding='utf-8-sig').splitlines() if x.strip()]
def writej(n,rs):(R/n).write_text(''.join(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n' for x in rs),encoding='utf-8',newline='\n')
def ids(a,b):return [f'M7_sol-2Tim-{i:03d}' for i in range(a,b+1)]
specs=[
('F01',ids(1,4),'Thanksgiving/remembrance grounds, deposit language, and abandonment/household contrast retain substantial internal alternatives.',['1:1|1:2','1:3-5|1:6-7','1:3-4|1:5-7','1:8-10|1:11-12|1:13-14','1:8-12|1:13-14','1:15|1:16-18'],['1:1-7','1:3-14','1:8-18','1:1-18','1:15-2:7'],['gift/laying-on wording','calling/appearance clauses','speaker self-description','deposit referent/translation','abandonment scope'],'RN-2TIM-001'),
('F02',ids(5,6),'Entrusting, metaphor triad, remembrance/suffering, and faithful saying must not be atomized or converted into policy/proof texts.',['2:1-2|2:3-7','2:3-4|2:5|2:6|2:7','2:8-10|2:11-13','2:8-9|2:10|2:11-13'],['1:15-2:7','2:1-13','2:8-19','2:1-26'],['entrusting scope','metaphor syntax','chains/endurance rationale','saying lineation','pronouns and denial/remain-faithful clauses'],'RN-2TIM-002'),
('F03',ids(7,8),'Warning, worker contrast, error examples, foundation, vessels, and servant correction have finer seams and strong functional cohesion.',['2:14-15|2:16-18|2:19','2:14-16|2:17-19','2:14-18|2:19','2:20-21|2:22-26','2:20-21|2:22|2:23|2:24-26'],['2:8-19','2:14-26','2:1-26'],['logomachy','orthotomounta','inscription/citation form','vessel referents','youthful-desire scope','repentance/knowledge/snare syntax'],'RN-2TIM-003'),
('F04',ids(9,10),'The selected 3:10-17 parent is coherent, while the repeated but-you onset at 3:14 makes the 3:10-13|3:14-17 split first-class.',['3:1|3:2-5|3:6-9','3:1-5|3:6-7|3:8-9','3:10-12|3:13','3:10-13|3:14-17','3:14-15|3:16-17'],['3:10-17','3:1-17','3:14-4:5','3:10-4:5'],['vice-list grammar','named comparison/later reception','following/persecution catalogue','learned/from-whom clauses','pasa graphe theopneustos syntax/translation'],'RN-2TIM-004'),
('F05',ids(11,12),'The proclamation charge and departure testimony contain real charge/ground/contrast, offering, contest-triad, and crown seams.',['4:1|4:2|4:3-5','4:1-2|4:3-4|4:5','4:1-4|4:5','4:6|4:7|4:8','4:6|4:7-8','4:6-7|4:8'],['3:14-4:5','3:10-4:5','4:1-8','4:6-22','4:1-22'],['solemn-charge textual pressure','appearing/kingdom relation','teacher accumulation','spendomai','departure wording','crown/judge/appearing close'],'RN-2TIM-005'),
('F06',ids(13,15),'Names belong to request/travel, warning/defense, and greeting registers; rescue, doxology, and benediction require preserved closures.',['4:9-12|4:13','4:9-11|4:12-13','4:14-15|4:16-18','4:14-16|4:17-18','4:19|4:20-21|4:22','4:19-21|4:22'],['4:9-18','4:9-22','4:6-22','4:1-22'],['location textual pressure','requested-object scope','first-defense abandonment','rescue/proclamation purpose','illness/season notices','benediction number/textual forms'],'RN-2TIM-006')]
fams=[]
for code,dids,claim,fine,large,holds,rn in specs:fams.append({'challenge_id':f'2TIM-PEER-{code}','decision_ids':dids,'claim':claim,'exact_finer_routes':fine,'exact_larger_routes':large,'unresolved_holds':holds,'evidence_refs':['book_chunks/2Tim/chunks.jsonl','reviews/2Tim/blind_proposal_greek_textual_v1.json','reviews/2Tim/blind_proposal_literary_v1.json','reviews/2Tim/blind_proposal_canonical_premortem_v1.json',f'decision_relations.jsonl#{rn}'],'proposed_remedy':'retain current larger-coherence unit(s) at LOW and preserve every exact route append-only for human or external-AI adjudication','verdict':'material_challenge','status':'deferred_human_or_external_ai','forced_consensus':False,'non_authorizing':True})
peer=load('peer_crosscheck_v1.json');peer.update(attempt_id='2tim-peer-crosscheck-20260724-d',reviewer_role='independent_peer_red_team_sol_high',status='pass_with_material_holds',macro_material_challenge_families=fams,current_boundary_verdict='all_15_defensible_only_as_LOW_deferred_candidates',highest_undersegmentation_pressure=['M7_sol-2Tim-010'],promotion_verdict='blocked_pending_external_or_human_cross_model_review',forced_consensus=False,shared_model_substrate=True,counts_as_cross_model_independent_vote=False,non_authorizing=True);peer['disputed_claim_ids']=list(dict.fromkeys(peer.get('disputed_claim_ids',[])+[f['challenge_id'] for f in fams]));dump('peer_crosscheck_v1.json',peer)
boss=load('boss_ruling_v1.json')
for f in fams:boss['challenge_responses'].append({'challenge_id':f['challenge_id'],'decision_ids':f['decision_ids'],'author_response':'Accept the material challenge. Retain the larger-coherence unit(s) at LOW; preserve all finer/larger routes and textual/semantic holds append-only; defer selection.','disposition':'hold_larger_unit_deferred_human_or_external_ai','appeal_preserved':True,'authority':'candidate_author_only'})
boss['unresolved_claim_ids']=list(dict.fromkeys(boss.get('unresolved_claim_ids',[])+[f['challenge_id'] for f in fams]));boss.update(peer_ruling='all six macro challenges preserved; 3:10-13|3:14-17 remains coequal under the selected 3:10-17 parent; no witness, reading, identity, authorship, chronology, succession, canon, doctrine, history, or theology selection',external_or_human_review_still_required=True,forced_consensus=False,non_authorizing=True);dump('boss_ruling_v1.json',boss)
byid={d:f for f in fams for d in f['decision_ids']};packets=readj('review_packets.jsonl')
for p in packets:
 f=byid[p['decision_id']];p['span_specific_peer_challenge']={'challenge_id':f['challenge_id'],'claim':f['claim'],'exact_finer_routes':f['exact_finer_routes'],'exact_larger_routes':f['exact_larger_routes'],'unresolved_holds':f['unresolved_holds'],'status':'deferred_human_or_external_ai','non_authorizing':True}
writej('review_packets.jsonl',packets);print(json.dumps({'families':len(fams),'boss_responses':len(boss['challenge_responses']),'packets':len(packets)}))