#!/usr/bin/env python3
"""Find EVERY per-row author-wave order across the four rulings and the boss audit.

WHY THIS EXISTS. #e13's worklist_basis_per_class names a whole family of classes I had not built:

    "C1, C4, A2, A3 silent rows, A7, A9, A10, A16, D1, D7, D10": "as ruled in #e12 (MEASURED census) plus the
    per-row orders in this file"

Worklist v3 carries CONFIDENCE, WORDING, BOSS_RETURN, A6, A6_UNION, MARKS_3D, ARITHMETIC and A4_CITATION - and
none of that family. #e13's confidence_rulings alone carry 17 per-row `author_wave` orders (A9/A16 weighings, C1
and C4 rewrites, A7 and A10 disclosures, false-ground replacements), and my builder read only the confidence
VALUE from each of those same records. Step 2 of the ruling's own execution order is "C1/C4 rewrites and the
A9/A16 rival weighings", so the wave would have run its second step with an empty worklist.

THIS IS THE E-31 CLASS FOR THE THIRD TIME IN THIS BOOK, and the pattern is now unmistakable: I keep building an
artifact from PART of an order and reporting it as built from the order. E-31's cure was to generate the
completion report by iterating the order's clause list. The generalisation this makes unavoidable: **the WORKLIST
must be generated by iterating the order's own class list, not assembled from the classes I happened to think
of.** So this script walks every ruling exhaustively for order-bearing fields rather than looking where I expect
orders to be.

METHOD. Walk each ruling's whole JSON tree. Collect any string value under a key that names an order
(author_wave, work_order, order, orders, author_instruction, repair, remedy) whose sibling or ancestor identifies
a row. Report per source and per row, with the key path, so nothing is found by pattern-matching prose.
"""
import json
import re
from pathlib import Path

EZ = Path(r"C:\wt\logos-t423-m8-fable\.ai\scratch\multi_model_bible_chunking\M8_fable\sp_durable\Ezek")
HERE = Path(__file__).resolve().parent
ROWID = re.compile(r"^P\d{2}-\d{3}$")
# A row id also appears EMBEDDED IN A KEY NAME - "P02-003_routed_by_peer_02" - and my first version attributed
# that order to no row, so it read as corpus-wide and escaped the coverage test. A second pattern catches it.
ROWID_IN_KEY = re.compile(r"(?<!\w)(P\d{2}-\d{3})")  # no trailing \b:\n# a key like P02-003_routed_by_peer_02 has an underscore after the digits, which IS a word character, so a\n# trailing word-boundary assertion can never hold there. A leading negative lookbehind is the right anchor.
ORDER_KEYS = {"author_wave", "work_order", "author_instruction", "order", "orders", "repair", "remedy",
              "author_wave_order", "author_wave_wording_orders"}
SOURCES = ["ezek_controlling_agent_ruling_e12.v1.json", "ezek_controlling_agent_ruling_e13.v1.json",
           "ezek_controlling_agent_ruling_e14.v1.json", "ezek_boss_audit.v1.json"]

found = []


def row_of(node, key=None):
    """The row id a node identifies, if any - from a row field, or from its own KEY NAME."""
    if isinstance(key, str):
        m = ROWID_IN_KEY.search(key)
        if m:
            return m.group(1)
    if not isinstance(node, dict):
        return None
    for k in ("row", "row_id", "decision_id"):
        v = node.get(k)
        if isinstance(v, str) and ROWID.match(v.strip()):
            return v.strip()
    return None


def walk(o, path, src, inherited_row=None):
    if isinstance(o, dict):
        rid = row_of(o, path.rsplit("/", 1)[-1] if "/" in path else None) or inherited_row
        for k, v in o.items():
            if k in ORDER_KEYS and isinstance(v, str) and v.strip():
                found.append({"source": src, "row": rid, "key": k, "path": path + "/" + k,
                              "order": v.strip()})
            elif k in ORDER_KEYS and isinstance(v, list):
                for i, x in enumerate(v):
                    if isinstance(x, str) and x.strip():
                        found.append({"source": src, "row": rid, "key": k,
                                      "path": "%s/%s[%d]" % (path, k, i), "order": x.strip()})
            else:
                walk(v, path + "/" + str(k), src, row_of(v, str(k)) or rid)
    elif isinstance(o, list):
        for i, v in enumerate(o):
            walk(v, "%s[%d]" % (path, i), src, inherited_row)


for name in SOURCES:
    p = EZ / name
    walk(json.loads(p.read_text(encoding="utf-8")), "", name, None)

with_row = [f for f in found if f["row"]]
without_row = [f for f in found if not f["row"]]
by_row = {}
for f in with_row:
    by_row.setdefault(f["row"], []).append(f)

# what worklist v3 already covers, by row and class
w = json.loads((EZ / "author_wave_worklist.v3.json").read_text(encoding="utf-8"))
v3_rows = {}
for i in w["items"]:
    v3_rows.setdefault(i["row_id"], set()).add(i["cls"])

# an order is UNCOVERED when its row has no item of a class that could discharge it. CONFIDENCE cannot
# discharge a wording order and A4/A6 cannot either; only a GROUNDS-style item can, and there are none.
GROUNDS_CLASSES = {"GROUNDS", "WORDING", "BOSS_RETURN", "MARKS_3D"}
uncovered = []
for rid, orders in sorted(by_row.items()):
    have = v3_rows.get(rid, set())
    if not (have & GROUNDS_CLASSES):
        uncovered.append({"row": rid, "orders": [{"source": o["source"], "key": o["key"],
                                                  "order": o["order"]} for o in orders],
                          "v3_classes_on_this_row": sorted(have)})

out = {
    "schema": "ezek_per_row_orders.v1",
    "why": ("#e13's worklist_basis_per_class names the class family 'C1, C4, A2, A3 silent rows, A7, A9, A10, "
            "A16, D1, D7, D10' as 'as ruled in #e12 plus the per-row orders in this file'. Worklist v3 carried "
            "none of it, and step 2 of the ruling's execution order is exactly that work."),
    "method": ("walked each ruling's whole JSON tree for values under order-bearing keys (%s), attributing each "
               "to the row its node or nearest ancestor identifies. Exhaustive walk rather than looking where I "
               "expected orders to be - the third instance this book of my building an artifact from PART of an "
               "order." % ", ".join(sorted(ORDER_KEYS))),
    "sources": SOURCES,
    "totals": {"order_strings_found": len(found), "attributed_to_a_row": len(with_row),
               "not_attributed_to_a_row": len(without_row), "distinct_rows": len(by_row)},
    "by_source": {s: len([f for f in with_row if f["source"] == s]) for s in SOURCES},
    "rows_with_an_order_but_NO_grounds_item_in_v3": {"count": len(uncovered), "detail": uncovered},
    "corpus_wide_orders_not_attributed_to_a_row": [
        {"source": f["source"], "key": f["key"], "path": f["path"], "order": f["order"][:240]}
        for f in without_row],
    "tier": "MEASURED over the four pinned rulings",
}
(HERE / "per_row_orders.v1.json").write_text(json.dumps(out, ensure_ascii=False, indent=1),
                                             encoding="utf-8", newline="\n")
print(json.dumps({k: out[k] for k in ("totals", "by_source")}, indent=1))
print()
print("rows carrying an order with NO grounds-style item in worklist v3: %d" % len(uncovered))
for u in uncovered[:24]:
    print("  %-9s (v3 has: %s)" % (u["row"], ",".join(u["v3_classes_on_this_row"]) or "nothing"))
    for o in u["orders"]:
        print("       [%s %s] %s" % (o["source"][-12:-5], o["key"], o["order"][:96]))
print()
print("corpus-wide orders not tied to a row: %d" % len(without_row))
