#!/usr/bin/env python3
"""Re-execute precondition P2 at CITATION granularity per #e14 orders O1-O2, under guarded mutation.

WHY THIS SCRIPT EXISTS TWICE OVER. The first P2 reported four applied changes and applied three; the missing one
was "a range counts as one citation" (queue E13-59, ledger E-31). So this patch does the work AND carries the
structural cure for the way the first one failed:

  ORDER_CLAUSES is the ORDER'S OWN ENUMERATION, one entry per clause, each with a MEASURED predicate over the
  resulting artifact. A clause whose predicate is false FAILS THE BUILD. The completion report is generated by
  iterating that list, so "I implemented four things" can no longer stand in for "I implemented THESE four
  things". A count-checked edit proves what it DID; only this proves what it was TOLD to do.

TWO PREDICATES DESERVE NOTICE because they check absence rather than presence:
  * O1f asserts the COVERAGE side is byte-identical to the pinned preimage. The order says the coverage side is
    unchanged; the only honest evidence for "unchanged" is the bytes.
  * O2 predicates run the selftest and require the two named vectors to be PRESENT and PASSING. A fixture that
    exists but does not fire is what R10 calls a build failure.

AND ONE DESIGN CHOICE MADE INSTEAD OF A SILENT PICK. DEF-A4-ARGUED clause 3 says a range is mirrored when "a
boundary_evidence_refs ENTRY covers ... either endpoint or the whole range". Singular "entry" admits a strict
per-entry reading; the union of all entries admits a looser one. They differ only where two different entries
cover the two endpoints. Rather than choose, the member computes BOTH and reports every citation where they
disagree, so the reading is decided on measurement instead of on my preference.
"""
import hashlib
import json
import py_compile
import shutil
import subprocess
import sys
from pathlib import Path

TOOLS = Path(r"C:\wt\logos-t423-m8-fable\.ai\scratch\multi_model_bible_chunking\M8_fable"
             r"\sp_durable\Ezek\tools")
SRC = TOOLS / "check_refs_mirror.py"
PIN = "36d83da69ed3175784dfe3e669a3337814750aa520f98b86f0889d7f5d5eedfb"
SCRATCH = Path(__file__).resolve().parent

# ---------------------------------------------------------------- pin
pre = SRC.read_bytes()
got = hashlib.sha256(pre).hexdigest()
if got != PIN:
    raise SystemExit("REFUSED: preimage is %s, expected %s" % (got, PIN))
text = pre.decode("utf-8")
BACKUP = SCRATCH / "check_refs_mirror.preimage_36d83da6.py"
BACKUP.write_bytes(pre)

# the coverage side, pinned for the O1f "unchanged" predicate
COVERAGE_SIDE_START = 'ENTRY_SCAN = re.compile'
COVERAGE_SIDE_END = 'def seam_pairs(own_span'
_i, _j = text.index(COVERAGE_SIDE_START), text.index(COVERAGE_SIDE_END)
COVERAGE_PIN = hashlib.sha256(text[_i:_j].encode("utf-8")).hexdigest()

edits = []           # (clause_ids, description, old, new, expected_count)


def edit(clauses, desc, old, new, count=1):
    edits.append((clauses, desc, old, new, count))


# =============================================================== E1: one match -> one citation's verses
# colon_refs and mt_colon_refs held their per-match expansion INLINE. Citation extraction needs the same
# expansion per match, and a second copy of it would be free to drift from the first. So the logic moves into
# one helper each and both callers use it: the verse set and the citation set cannot diverge by construction,
# which is stronger than asserting afterwards that they agree (the member does that too).
edit(["O1a"], "colon per-match expansion extracted to _colon_match_pairs",
     """        c1, v1 = int(m.group(1)), int(m.group(2))
        if c1 not in LAST_VERSE or not (1 <= v1 <= LAST_VERSE[c1]):
            continue
        if m.group(3) is None:
            out.add((c1, v1))
            continue
        if m.group(4) is None:
            c2, v2 = c1, int(m.group(3))
        else:
            c2, v2 = int(m.group(3)), int(m.group(4))
        if c2 not in LAST_VERSE or not (1 <= v2 <= LAST_VERSE[c2]) or (c2, v2) < (c1, v1):
            out.add((c1, v1))
            continue
        for c in range(c1, c2 + 1):
            lo = v1 if c == c1 else 1
            hi = v2 if c == c2 else LAST_VERSE[c]
            out.update((c, v) for v in range(lo, hi + 1))
    return out""",
     """        out.update(_colon_match_pairs(m))
    return out


def _colon_match_pairs(m) -> set[tuple[int, int]]:
    \"\"\"The WEB verses ONE bare-cite match contributes. Extracted from colon_refs so the verse arm and the
    citation arm (string_citations) share one expansion and cannot drift apart.\"\"\"
    out: set[tuple[int, int]] = set()
    c1, v1 = int(m.group(1)), int(m.group(2))
    if c1 not in LAST_VERSE or not (1 <= v1 <= LAST_VERSE[c1]):
        return out
    if m.group(3) is None:
        out.add((c1, v1))
        return out
    if m.group(4) is None:
        c2, v2 = c1, int(m.group(3))
    else:
        c2, v2 = int(m.group(3)), int(m.group(4))
    if c2 not in LAST_VERSE or not (1 <= v2 <= LAST_VERSE[c2]) or (c2, v2) < (c1, v1):
        out.add((c1, v1))                      # malformed range end: read the start only
        return out
    for c in range(c1, c2 + 1):
        lo = v1 if c == c1 else 1
        hi = v2 if c == c2 else LAST_VERSE[c]
        out.update((c, v) for v in range(lo, hi + 1))
    return out""")

edit(["O1a"], "MT per-match expansion extracted to _mt_colon_match_pairs",
     """    out = set()
    for m in MT_COLON.finditer(s):
        c, v1 = int(m.group(1)), int(m.group(2))
        c2 = int(m.group(3)) if m.group(3) else c
        v2 = int(m.group(4)) if m.group(4) else v1
        if (c2, v2) < (c, v1):
            c2, v2 = c, v1                     # malformed end: read start only
        for ch in range(c, c2 + 1):
            lo = v1 if ch == c else 1
            hi = v2 if ch == c2 else MT_LAST_VERSE.get(ch, 0)
            for v in range(lo, hi + 1):
                if ch in MT_LAST_VERSE and 1 <= v <= MT_LAST_VERSE[ch]:
                    out.update(mt_to_web_all(ch, v))
    return out""",
     """    out = set()
    for m in MT_COLON.finditer(s):
        out.update(_mt_colon_match_pairs(m))
    return out


def _mt_colon_match_pairs(m) -> set[tuple[int, int]]:
    \"\"\"The WEB verses ONE 'MT n:m' qualifier contributes. Extracted for the same reason as
    _colon_match_pairs: one expansion, two arms.\"\"\"
    out: set[tuple[int, int]] = set()
    c, v1 = int(m.group(1)), int(m.group(2))
    c2 = int(m.group(3)) if m.group(3) else c
    v2 = int(m.group(4)) if m.group(4) else v1
    if (c2, v2) < (c, v1):
        c2, v2 = c, v1                         # malformed end: read start only
    for ch in range(c, c2 + 1):
        lo = v1 if ch == c else 1
        hi = v2 if ch == c2 else MT_LAST_VERSE.get(ch, 0)
        for v in range(lo, hi + 1):
            if ch in MT_LAST_VERSE and 1 <= v <= MT_LAST_VERSE[ch]:
                out.update(mt_to_web_all(ch, v))
    return out""")

# =============================================================== E2: list splitting
edit(["O1c"], "parse_verse_expr_groups: dash joins one group, comma/'and' starts a new one",
     "def verse_word_refs(s: str, span_chapters: set[int]) -> set[tuple[int, int]]:",
     '''def parse_verse_expr_groups(expr: str) -> list[tuple[frozenset, str]]:
    """The SAME state machine as parse_verse_expr, returning the expression's CITATION GROUPS instead of a flat
    verse set: a dash join extends the current group (a range), a comma or "and" join STARTS A NEW ONE
    (DEF-A4-ARGUED clause 2). 'vv. 1-3, 5' -> [({1,2,3}, "range"), ({5}, "single")].

    The invariant that makes this safe to introduce: the UNION of the groups equals parse_verse_expr(expr)
    exactly. Citation granularity regroups what is argued; it must never change WHICH verses are argued. The
    selftest asserts it on vectors and analyze_row asserts it on every row of every run.

    Every guard of the original is preserved and for the same measured reasons: a non-ascending continuation
    numeral is a count, not a verse, and a numeral followed by a count-unit noun is a size.
    """
    groups: list[list[int]] = []
    prev = None
    pending_range = False
    for m in VERSE_PART.finditer(expr):
        tok = m.group(0)
        if tok.isdigit():
            n = int(tok)
            if COUNT_UNIT.match(expr[m.end():]):
                pending_range = False
                continue
            if prev is None:
                groups.append([n])
            elif pending_range:
                if n > prev and groups:
                    groups[-1].extend(range(prev, n + 1))
                else:
                    pending_range = False
                    continue
            elif n > prev:
                groups.append([n])
            else:
                continue                        # descending = not a verse list
            pending_range = False
            prev = n
        elif tok in ("-", "\\u2013"):
            pending_range = True
        else:                                   # comma or "and" - LIST join, so a NEW citation
            pending_range = False
    return [(frozenset(g), "range" if len(set(g)) > 1 else "single") for g in groups]


def verse_word_refs(s: str, span_chapters: set[int]) -> set[tuple[int, int]]:''')

# =============================================================== E3: the citation layer
CITATIONS = '''# --------------------------------------------------- CITATION granularity (#e14 Q1, DEF-A4-ARGUED)
# #e14 OVERRULED the framing that produced this section's need - "444 verses or the peers' 47" - as a false
# dichotomy produced by an INCOMPLETE P2. #e13 R1(i) had already ordered that a range counts as one citation;
# the orchestrator reported that clause applied when it was never implemented (queue E13-59, ledger E-31), and
# about 300 of the 444 verses were interior verses of argued ranges. Nothing in the corpus had to be chosen
# between; a clause had to be executed.
#
# DEF-A4-ARGUED, written by the controlling agent in #e14, binding for Ezekiel and proposed to method section 17:
#   1. an argued citation is any verse anchor a prose field carries, together with the assertion it anchors
#   2. a dash-range is ONE citation; a comma / "and" list is one citation PER MEMBER; the same verse-set cited
#      more than once in one row is ONE citation
#   3. mirrored = a refs entry covers its verse, or - for a range - either endpoint or the whole range,
#      compared in WEB space after witness conversion
#   4. an unmirrored citation with at least one verse inside the A4 window is a worklist item; one wholly
#      outside the window is far-side: recorded, never a defect (#e12 A4)
#   5. "argued" is NOT narrowed to "argued as evidence". The member judges MIRRORING; it never judges WEIGHT.
#
# ROLE tokens are not assigned here, and that is clause 6's point, not an omission: the evidentiary/narrative
# distinction peer_11 identified is real but is a distinction of ROLE, and it belongs in the entry a person
# writes and a reviewer reads. The vocabulary lives in this module because A4 is its home, so the worklist
# builder and the spot wave validate against ONE list.
ROLE_VOCABULARY = ("WARRANT-onset", "WARRANT-close", "WARRANT-rival", "WARRANT-absence-over-range",
                   "DISCLOSURE-kq", "DISCLOSURE-mark", "DISCLOSURE-paseq", "DISCLOSURE-note",
                   "DISCLOSURE-device", "QUOTE", "ANCHOR")
ROLE_UNASSIGNED = ("UNASSIGNED - the author assigns exactly one ROLE_VOCABULARY token; the member judges "
                   "mirroring, never weight (DEF-A4-ARGUED clause 5/6)")


def _cite(verses, raw, field, source):
    """One citation record. kind is a function of the VERSE SET and not of the surface form, so "vv. 4 and 5"
    and "4-5" are both ranges with the same endpoints - which is what clause 3's endpoint test needs. Endpoints
    are the min and max in WEB space; a witness conversion in the chs 20-21 divergence zone can make the
    expansion non-contiguous, and min/max remain the claim's two ends."""
    vs = frozenset(verses)
    if not vs:
        return None
    return {"verses": vs, "kind": "range" if len(vs) > 1 else "single",
            "endpoints": (min(vs), max(vs)), "raw": raw.strip()[:80], "field": field, "source": source}


def _fmt_cit(c) -> str:
    lo, hi = c["endpoints"]
    a = "Ezek.%d.%d" % lo
    return a if c["kind"] == "single" else "%s-Ezek.%d.%d" % (a, hi[0], hi[1])


def string_citations(s: str, span_chapters: set[int], field: str) -> list[dict]:
    """Every citation ONE prose string carries, through the same four parsers prose_refs uses, in the same
    order and with the same skips."""
    out = []
    for m in RANGE.finditer(s):
        tok = m.group(0)
        c = _cite(token_pairs_web(tok.replace("oshb:", ""), tok.startswith("oshb:")),
                  tok, field, "osis_token")
        if c:
            out.append(c)
    mt_spans = [(mm.start(), mm.end()) for mm in MT_COLON.finditer(s)]
    for m in COLON.finditer(s):
        if any(a <= m.start() < b for a, b in mt_spans):
            continue                            # an 'MT n:m' qualifier - the MT arm owns it
        c = _cite(_colon_match_pairs(m), m.group(0), field, "colon")
        if c:
            out.append(c)
    for m in MT_COLON.finditer(s):
        c = _cite(_mt_colon_match_pairs(m), m.group(0), field, "mt_colon")
        if c:
            out.append(c)
    if len(span_chapters) == 1:
        (ch,) = span_chapters
        for m in VERSE_WORD.finditer(s):
            for vs, _k in parse_verse_expr_groups(m.group(1)):
                c = _cite([(ch, v) for v in sorted(vs)
                           if ch in LAST_VERSE and 1 <= v <= LAST_VERSE[ch]],
                          m.group(0), field, "verse_word")
                if c:
                    out.append(c)
    return out


def prose_citations(row, span_chapters: set[int]) -> list[dict]:
    """Every argued citation in the row's prose, deduped by VERSE SET (clause 2: the same verse-set cited more
    than once in one row is one citation). The first occurrence keeps the record and counts its repeats, so the
    field the worklist points at is the one that names the citation first."""
    seen: dict[frozenset, dict] = {}
    order: list[frozenset] = []

    def walk(o, key=None):
        if isinstance(o, dict):
            for k, v in o.items():
                if k in SKIP_KEYS:
                    continue
                walk(v, k)
        elif isinstance(o, list):
            for v in o:
                walk(v, key)
        elif isinstance(o, str):
            for c in string_citations(o, span_chapters, key or "?"):
                vs = c["verses"]
                if vs in seen:
                    seen[vs]["repeats"] += 1
                    continue
                c["repeats"] = 0
                seen[vs] = c
                order.append(vs)
    walk(row)
    return [seen[vs] for vs in order]


def citation_mirrored(cit: dict, cov: set) -> bool:
    """Clause 3. A single is mirrored when its verse is covered. A RANGE is mirrored when either endpoint or
    the whole range is covered - an endpoint suffices because a refs entry naming one end indexes the claim the
    range makes. This is the clause whose absence produced one flag per interior verse."""
    if cit["kind"] == "single":
        return next(iter(cit["verses"])) in cov
    lo, hi = cit["endpoints"]
    return lo in cov or hi in cov or cit["verses"] <= cov


def citation_mirrored_per_entry(cit: dict, row) -> bool:
    """Clause 3 read STRICTLY - ONE entry must do the covering by itself.

    Computed only to MEASURE whether the two readings differ on this corpus. The ruling's singular "a
    boundary_evidence_refs entry covers ... either endpoint" admits the strict reading; the union of entries
    admits the looser one; they differ only where two DIFFERENT entries cover the two endpoints of one range.
    The member reports every disagreement rather than letting the orchestrator pick a reading in silence."""
    for ref in row.get("boundary_evidence_refs", []):
        if citation_mirrored(cit, set(entry_pairs(ref))):
            return True
    return False


def classify_citation(cit: dict, window: set, own_span: set) -> str:
    """Clause 4 plus the ruling's three in-window classes. A citation whose in-window verses are ONLY seam
    verses is AT_SEAM even when its other verses lie far outside the window - those are the ruling's
    seam-touching ranges, and they are worklist items because a verse of theirs is in the window."""
    in_win = cit["verses"] & window
    if not in_win:
        return "FAR_SIDE"
    in_span = cit["verses"] & own_span
    return "MIXED" if (in_span and (in_win - own_span)) else ("IN_SPAN" if in_span else "AT_SEAM")


def analyze_row(row, fname="-") -> dict:
    """One row's A4 analysis at CITATION granularity. main and the selftest share this ONE path, so a fixture
    exercises exactly what a run does - the fixtures of the previous P2 could not have caught its omission
    because nothing tested the classification end to end."""
    own_span = set(expand_ref_token(str(row.get("span", "")).replace("web:", "")))
    span_chapters = {c for c, _ in own_span}
    cits = prose_citations(row, span_chapters)
    cov = covered(row)
    window, win_diag = a4_window(own_span)

    argued = prose_refs(row, span_chapters)
    union = set().union(*[c["verses"] for c in cits]) if cits else set()
    if union != argued:
        raise SystemExit("REFUSED: citation regrouping changed the ARGUED VERSE SET on %s - %d citation verses "
                         "against %d verse-arm verses; symmetric difference %r. Regrouping may change how "
                         "claims are counted and never which verses are argued."
                         % (row.get("decision_id", "?"), len(union), len(argued),
                            sorted(union ^ argued)[:8]))

    items, far, disagree = [], [], []
    for c in cits:
        union_m = citation_mirrored(c, cov)
        entry_m = citation_mirrored_per_entry(c, row)
        if union_m != entry_m:
            disagree.append({"decision_id": row.get("decision_id", "?"), "citation": _fmt_cit(c),
                             "union_reading": union_m, "strict_per_entry_reading": entry_m})
        if union_m:
            continue
        cls = classify_citation(c, window, own_span)
        rec = {"file": fname, "decision_id": row.get("decision_id", "?"),
               "citation": _fmt_cit(c), "kind": c["kind"], "class": cls,
               "verse_count": len(c["verses"]),
               # per-verse list KEPT AS A DIAGNOSTIC (O1) - it is what makes the citation auditable
               "verses_web": ["Ezek.%d.%d" % p for p in sorted(c["verses"])][:16],
               "field": c["field"], "raw": c["raw"], "source": c["source"],
               "repeats_in_row": c["repeats"], "role_token": ROLE_UNASSIGNED}
        (far if cls == "FAR_SIDE" else items).append(rec)

    # LEGACY VERSE-LEVEL AGGREGATE, kept so the citation figures stay comparable with the shipped member's
    # 444 / 131 / 817 and with the controlling agent's recount. Diagnostic only; never a flag.
    missing = sorted(argued - cov)
    legacy = {"missing_verses": len(missing),
              "in_window_verses": len([p for p in missing if p in window]),
              "in_span_verses": len([p for p in missing if p in window and p in own_span]),
              "at_seam_verses": len([p for p in missing if p in window and p not in own_span]),
              "far_side_verses": len([p for p in missing if p not in window])}
    return {"decision_id": row.get("decision_id", "?"), "items": items, "far_side": far,
            "mirror_reading_disagreements": disagree,
            "orphan_refs": orphan_refs(row, argued, own_span),
            "citations_read": len(cits), "argued_verses": len(argued),
            "window": win_diag, "legacy_verse_level": legacy}


ENTRY_SCAN = re.compile'''
edit(["O1a", "O1b", "O1d", "O1e", "O1g"], "the citation layer: extraction, dedupe, mirroring, classification",
     "ENTRY_SCAN = re.compile", CITATIONS)

# =============================================================== E4: selftest fixtures
FIXTURES = '''    # ---- #e14 O2: the two RANGE fixtures. These are the regression for the clause that was reported applied
    # and never implemented. Fixture (a) is the one that matters: per-verse comparison produced one flag for
    # every interior verse of a range whose endpoint the refs list already named.
    SPAN = "Ezek.16.20-Ezek.16.30"
    row_a = {"decision_id": "FIXTURE-A", "span": SPAN,
             "boundary_evidence_refs": ["web:Ezek.16.26"],
             "rationale": "the unit runs 16:24-16:26 and closes there"}
    ra = analyze_row(row_a, "fixture")
    cases.append(("O2(a) a range with only its SECOND endpoint in refs yields ZERO flags",
                  not ra["items"] and not ra["far_side"]))
    cases.append(("O2(a) and the range was still READ as one citation over three verses",
                  ra["citations_read"] == 1 and ra["argued_verses"] == 3))
    cases.append(("O2(a) the legacy verse-level arm would have flagged the interior - which is the defect",
                  ra["legacy_verse_level"]["in_span_verses"] == 2))
    row_a1 = dict(row_a, decision_id="FIXTURE-A1", boundary_evidence_refs=["web:Ezek.16.24"])
    cases.append(("O2(a) the FIRST endpoint mirrors the range just as well",
                  not analyze_row(row_a1, "fixture")["items"]))

    row_b = dict(row_a, decision_id="FIXTURE-B", boundary_evidence_refs=["web:Ezek.16.20"])
    rb = analyze_row(row_b, "fixture")
    cases.append(("O2(b) a range with NEITHER endpoint in refs yields exactly ONE flag",
                  len(rb["items"]) == 1))
    cases.append(("O2(b) and the flag NAMES THE RANGE rather than its interior verses",
                  bool(rb["items"]) and rb["items"][0]["citation"] == "Ezek.16.24-Ezek.16.26"
                  and rb["items"][0]["kind"] == "range" and rb["items"][0]["verse_count"] == 3))
    cases.append(("O2(b) the flagged citation carries an UNASSIGNED role token, never a guessed one",
                  bool(rb["items"]) and rb["items"][0]["role_token"].startswith("UNASSIGNED")))

    # ---- clause 2: a comma / "and" list is one citation PER MEMBER, so a mirrored member discharges alone
    row_c = {"decision_id": "FIXTURE-C", "span": SPAN,
             "boundary_evidence_refs": ["web:Ezek.16.24"],
             "rationale": "see vv. 24 and 26 for the pair"}
    rc = analyze_row(row_c, "fixture")
    cases.append(("clause 2 a list is one citation per member: the mirrored member discharges, the other flags",
                  len(rc["items"]) == 1 and rc["items"][0]["citation"] == "Ezek.16.26"
                  and rc["citations_read"] == 2))

    # ---- clause 2: the same verse-set cited twice in one row is ONE citation
    row_d = {"decision_id": "FIXTURE-D", "span": SPAN,
             "boundary_evidence_refs": ["web:Ezek.16.20"],
             "rationale": "the unit runs 16:24-16:26",
             "strongest_rejected_alternative": "a cut at 16:24-16:26 was weighed and rejected"}
    rd = analyze_row(row_d, "fixture")
    cases.append(("clause 2 the same verse-set cited twice in one row is ONE citation, with repeats recorded",
                  rd["citations_read"] == 1 and len(rd["items"]) == 1
                  and rd["items"][0]["repeats_in_row"] == 1))

    # ---- clause 4: a citation wholly outside the window is far-side and never a defect; a range that reaches
    # the seam from outside IS a worklist item, because a verse of it is in the window
    row_e = {"decision_id": "FIXTURE-E", "span": SPAN, "boundary_evidence_refs": ["web:Ezek.16.20"],
             "rationale": "compare 16:5-16:8 elsewhere"}
    re_ = analyze_row(row_e, "fixture")
    cases.append(("clause 4 a citation wholly outside the window is FAR_SIDE, never a defect",
                  not re_["items"] and len(re_["far_side"]) == 1))
    row_f = {"decision_id": "FIXTURE-F", "span": SPAN, "boundary_evidence_refs": ["web:Ezek.16.20"],
             "rationale": "the material of 16:14-16:19 leads in"}
    rf = analyze_row(row_f, "fixture")
    cases.append(("clause 4 a range reaching the onset seam from outside IS a worklist item, class AT_SEAM",
                  len(rf["items"]) == 1 and rf["items"][0]["class"] == "AT_SEAM"))

    # ---- the regrouping invariant, on the expression parser directly
    for expr in ("1-3, 5", "24 and 26", "7-9", "10-11, 2 verses", "2 at verse 13, 3 at verse 14", "4"):
        g = parse_verse_expr_groups(expr)
        u = set().union(*[set(v) for v, _ in g]) if g else set()
        cases.append(("regrouping %r preserves the argued verse set exactly" % expr,
                      u == parse_verse_expr(expr)))
    cases.append(("a dash join is ONE group and a comma join is TWO",
                  [k for _, k in parse_verse_expr_groups("1-3, 5")] == ["range", "single"]))

'''
edit(["O2a", "O2b", "O1c", "O1d"], "the O2 range fixtures plus clause 2/4 and invariant vectors",
     "    width = max(len(n) for n, _ in cases)", FIXTURES + "    width = max(len(n) for n, _ in cases)")

# =============================================================== E5: main at citation granularity
_m = text.index("def main() -> int:")
_e = text.index('if __name__ == "__main__":')
OLD_MAIN = text[_m:_e]
NEW_MAIN = '''def main() -> int:
    _assert_declared_face("WEB")
    items, far_side, orphan_warns, disagree = [], [], [], []
    legacy = {"missing_verses": 0, "in_window_verses": 0, "in_span_verses": 0,
              "at_seam_verses": 0, "far_side_verses": 0}
    n = 0
    for f in sys.argv[1:]:
        for row in rows_from(Path(f)):
            if not isinstance(row, dict) or "boundary_evidence_refs" not in row:
                continue
            n += 1
            a = analyze_row(row, Path(f).name)
            items.extend(a["items"])
            far_side.extend(a["far_side"])
            disagree.extend(a["mirror_reading_disagreements"])
            for k in legacy:
                legacy[k] += a["legacy_verse_level"][k]
            if a["orphan_refs"]:
                orphan_warns.append({"file": Path(f).name, "decision_id": a["decision_id"],
                                     "orphan_refs": a["orphan_refs"]})

    def cnt(cls, kind=None):
        return len([i for i in items if i["class"] == cls and (kind is None or i["kind"] == kind)])

    def rows_with(*classes):
        return len({i["decision_id"] for i in items if i["class"] in classes})

    counts = {
        "in_span_citations": cnt("IN_SPAN"),
        "in_span_single_citations": cnt("IN_SPAN", "single"),
        "in_span_range_citations": cnt("IN_SPAN", "range"),
        "mixed_span_and_seam_citations": cnt("MIXED"),
        "at_seam_single_citations": cnt("AT_SEAM", "single"),
        "seam_touching_range_citations": cnt("AT_SEAM", "range"),
        "rows_with_an_in_span_or_mixed_citation": rows_with("IN_SPAN", "MIXED"),
        "rows_with_any_worklist_citation": rows_with("IN_SPAN", "MIXED", "AT_SEAM"),
        "worklist_citations_total": len(items),
        "far_side_citations": len(far_side),
        "far_side_citation_verses": sum(i["verse_count"] for i in far_side),
    }
    print(json.dumps({
        "rows_checked": n,
        "granularity": "CITATION (#e14 O1). The unit of every flag and every count is the argued citation: a "
                       "single verse is one, a dash-range is one, a comma/'and' list is one per member, and a "
                       "verse-set cited twice in a row is one.",
        "definition": "DEF-A4-ARGUED as written in ruling #e14; 'argued' is NOT narrowed to 'argued as "
                      "evidence' - this member judges mirroring and never weight",
        "role_vocabulary": list(ROLE_VOCABULARY),
        "role_assignment": ROLE_UNASSIGNED,
        "counts": counts,
        "a4_window_rule": "a citation is a worklist item when at least one of its verses lies in "
                          "[first-1, last+1]; a citation wholly outside that window is far-side and never a "
                          "defect (#e12 A4)",
        "mirror_reading": {
            "applied": "UNION of all boundary_evidence_refs entries",
            "why_reported": "DEF-A4-ARGUED clause 3's singular 'entry' also admits a strict per-entry reading; "
                            "the two differ only where two different entries cover the two endpoints of one "
                            "range. Both are computed on every citation and every disagreement is listed, so "
                            "the reading is settled by measurement rather than by the orchestrator's choice.",
            "disagreement_count": len(disagree),
            "disagreements": disagree,
        },
        "legacy_verse_level_aggregate": dict(
            legacy, note="DIAGNOSTIC ONLY, never a flag. Kept so these figures stay comparable with the "
                         "shipped member's 444 in-span / 131 at-seam / 817 far-side verses and with the "
                         "controlling agent's recount. The citation counts above are the worklist basis."),
        "worklist_citations": items,
        "far_side_citations_detail": far_side,
        "orphan_ref_warn_rows": len(orphan_warns),
        "orphan_ref_warn_count": sum(len(o["orphan_refs"]) for o in orphan_warns),
        "orphan_ref_warns": orphan_warns,
        "status": "GREEN" if not items else "FLAGS",
    }, ensure_ascii=False, indent=1))
    return 1 if items else 0


'''
edit(["O1a", "O1b", "O1h", "O1g"], "main reports CITATIONS and rows, with the verse-level arm as a diagnostic",
     OLD_MAIN, NEW_MAIN)

# ---------------------------------------------------------------- apply, count-checked
applied = {}
new = text
for clauses, desc, old, rep, want in edits:
    got_n = new.count(old)
    if got_n != want:
        raise SystemExit("REFUSED: %r occurs %d times, expected %d" % (desc, got_n, want))
    new = new.replace(old, rep, want)
    for c in clauses:
        applied.setdefault(c, []).append(desc)
    print("  edit OK  [%s] %s" % (",".join(clauses), desc))
    if old in new and old.strip() not in rep:
        raise SystemExit("REFUSED: survivor of %r" % desc)

STAGE = SCRATCH / "check_refs_mirror.candidate.py"
STAGE.write_text(new, encoding="utf-8", newline="\n")
py_compile.compile(str(STAGE), doraise=True)
print("  py_compile OK")

# ---------------------------------------------------------------- atomic replace, then verify in place
tmp = SRC.with_suffix(".py.tmpP2")
shutil.copy2(STAGE, tmp)
tmp.replace(SRC)
post = hashlib.sha256(SRC.read_bytes()).hexdigest()
final = SRC.read_text(encoding="utf-8")

sel = subprocess.run([sys.executable, str(SRC), "--a4-selftest"], capture_output=True, text=True, cwd=str(TOOLS))
print(sel.stdout[-3000:] or sel.stderr[-3000:])

# ---------------------------------------------------------------- THE ORDER'S OWN CLAUSE LIST
# Each clause carries a predicate MEASURED over the artifact that now exists. A clause with a false predicate
# FAILS THE BUILD. This is the cure for E-31: the report is generated by iterating the ORDER, not by recalling
# what the patch did.
sel_ok = lambda name: ("PASS  " + name) in sel.stdout or ("PASS  " + name).replace("  ", " ") in sel.stdout


def sel_pass(fragment):
    for line in sel.stdout.splitlines():
        if fragment in line:
            return line.strip().startswith("PASS")
    return False


ORDER_CLAUSES = [
    ("O1a", "the unit of comparison, of every flag and of every count is the argued CITATION, not the verse",
     lambda: ("def prose_citations(" in final and '"worklist_citations": items' in final
              and 'granularity": "CITATION' in final)),
    ("O1b", "a single verse is one citation; a dash-range is ONE citation",
     lambda: ('"kind": "range" if len(vs) > 1 else "single"' in final
              and sel_pass("O2(b) and the flag NAMES THE RANGE"))),
    ("O1c", "a comma / 'and' list is one citation per member",
     lambda: ("def parse_verse_expr_groups(" in final
              and sel_pass("clause 2 a list is one citation per member"))),
    ("O1d", "the same verse-set cited more than once in one row is one citation",
     lambda: sel_pass("clause 2 the same verse-set cited twice in one row is ONE citation")),
    ("O1e", "mirrored when a refs entry covers its verse, or for a range either endpoint or the whole range",
     lambda: ("def citation_mirrored(" in final
              and "return lo in cov or hi in cov or cit[\"verses\"] <= cov" in final
              and sel_pass("O2(a) the FIRST endpoint mirrors the range"))),
    ("O1f", "the COVERAGE side (refs entries expanded in WEB space) is UNCHANGED",
     lambda: hashlib.sha256(
         final[final.index(COVERAGE_SIDE_START):final.index(COVERAGE_SIDE_END)].encode("utf-8")
     ).hexdigest() == COVERAGE_PIN),
    ("O1g", "keep the per-verse list as a diagnostic field",
     lambda: ('"verses_web": ["Ezek.%d.%d" % p for p in sorted(c["verses"])]' in final
              and '"legacy_verse_level_aggregate"' in final)),
    ("O1h", "report citations AND rows",
     lambda: ('"rows_with_an_in_span_or_mixed_citation"' in final
              and '"in_span_citations"' in final)),
    ("O2a", "fixture: a row arguing C:V1-C:V2 with V2 only in its refs produces ZERO flags from that range",
     lambda: sel_pass("O2(a) a range with only its SECOND endpoint in refs yields ZERO flags")),
    ("O2b", "fixture: a row arguing a range with neither endpoint mirrored produces exactly ONE flag naming it",
     lambda: (sel_pass("O2(b) a range with NEITHER endpoint in refs yields exactly ONE flag")
              and sel_pass("O2(b) and the flag NAMES THE RANGE"))),
]

report, failed = [], []
for cid, clause_text, pred in ORDER_CLAUSES:
    try:
        ok = bool(pred())
    except Exception as exc:                                  # a predicate that cannot run is NOT a pass
        ok, clause_text = False, clause_text + "  [predicate raised %s]" % exc
    report.append({"clause": cid, "ordered": clause_text, "satisfied": ok,
                   "edits_that_implement_it": applied.get(cid, []),
                   "evidence": "MEASURED over the post-edit source and the selftest run"})
    if not ok:
        failed.append(cid)

print(json.dumps({"preimage": PIN, "postimage": post, "bytes": SRC.stat().st_size,
                  "lines": len(final.splitlines()),
                  "selftest_exit": sel.returncode,
                  "order_clause_conformance": report,
                  "clauses_ordered": len(ORDER_CLAUSES), "clauses_satisfied": len(ORDER_CLAUSES) - len(failed),
                  "FAILED_CLAUSES": failed,
                  "coverage_side_unchanged_sha256": COVERAGE_PIN,
                  "backup_of_preimage": str(BACKUP)}, indent=1, ensure_ascii=False))
if failed or sel.returncode != 0:
    raise SystemExit("BUILD FAILED: clauses %r unsatisfied / selftest exit %d. The preimage is at %s."
                     % (failed, sel.returncode, BACKUP))
print("\nALL %d ORDERED CLAUSES SATISFIED, each by a measured predicate over the artifact." % len(ORDER_CLAUSES))
