#!/usr/bin/env python3
"""Record worklist v4 and the E-32 ledger row: an artifact assembled from PART of an order, three times."""
import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

EZ = Path(r"C:\wt\logos-t423-m8-fable\.ai\scratch\multi_model_bible_chunking\M8_fable\sp_durable\Ezek")
M8 = EZ.parents[1]
HERE = Path(__file__).resolve().parent
Q = EZ / "ezek_controlling_agent_queue_e13.v1.jsonl"
MD = M8 / "ERROR_PATTERN_LEDGER.v1.md"
JL = M8 / "error_pattern_ledger.v1.jsonl"
NOW = datetime.now(timezone.utc).isoformat()
sha = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()          # noqa: E731

src, dst = HERE / "per_row_orders.v1.json", EZ / "per_row_orders.v1.json"
if dst.is_file() and sha(dst) != sha(src):
    raise SystemExit("REFUSED: exists with different bytes")
shutil.copy2(src, dst)

W = EZ / "author_wave_worklist.v4.json"
w = json.loads(W.read_text(encoding="utf-8"))
od = json.loads(dst.read_text(encoding="utf-8"))

entry = {
    "id": "E13-65",
    "severity": "HIGH",
    "headline": "THE WORKLIST WAS MISSING A WHOLE CLASS FAMILY THE RULING NAMES: C1/C4/A9/A16/A7/A10 and the "
                "rest. 17 rows carried a per-row order with no item to discharge it, and step 2 of the "
                "execution order would have run on an empty worklist. v4 adds a GROUNDS class of 17.",
    "raised_by": "orchestrator (claude-opus-5), self-audit of the worklist against the ruling's own "
                 "worklist_basis_per_class",
    "what_the_order_says": ("#e13 worklist_basis_per_class: \"C1, C4, A2, A3 silent rows, A7, A9, A10, A16, D1, "
                            "D7, D10\": \"as ruled in #e12 (MEASURED census) plus the per-row orders in this "
                            "file\"; and order_of_execution step 2 is \"C1/C4 rewrites and the A9/A16 rival "
                            "weighings\"."),
    "measured": {"per_row_orders_across_the_four_rulings": od["totals"]["attributed_to_a_row"],
                 "rows_with_an_order": od["totals"]["distinct_rows"],
                 "rows_with_no_discharging_item_in_v3": 17,
                 "by_source": od["by_source"]},
    "where_they_were_hiding": ("17 sat in the `author_wave` field of #e13's confidence_rulings - the very "
                               "records my builder opened to read the confidence VALUE out of. It read one "
                               "field of each record and ignored the order beside it. One more sat under a key "
                               "whose NAME carries the row id (P02-003_routed_by_peer_02)."),
    "the_pattern_this_is_the_third_instance_of": {
        "1": "E-31: I reported four ordered clauses as applied and had applied three",
        "2": "E13-63: I built the A6 class from the boss's sweep where the order says arm UNION peers",
        "3": "this: I built the worklist from the classes I thought of, not from the order's class list",
        "shape": "an artifact assembled from PART of an order and reported as built from the order",
        "why_the_local_cure_was_not_enough": ("E-31's cure was to generate the COMPLETION REPORT by iterating "
                                              "the order's clauses. That catches a misreported build. It does "
                                              "not catch a build whose SCOPE was short, because the report "
                                              "iterates the clauses the builder knew about."),
    },
    "the_general_cure_now_in_place": ("v4's first new fixture is GENERATED BY ITERATING THE ORDERS THEMSELVES: "
                                      "it walks every ruling for order-bearing fields and FAILS THE BUILD if "
                                      "any per-row order has no item of a class that could discharge it. A "
                                      "class the builder forgets can no longer be a class the build passes "
                                      "without. This is the gate that would have caught all three instances."),
    "a_regex_bug_worth_recording_because_it_was_invisible": (
        "the order-finder had to read a row id out of a KEY NAME. Written through a bash heredoc, the \\b in my "
        "pattern became a literal BACKSPACE (U+0008), so the pattern was \\x08(P\\d{2}-\\d{3})\\x08 and matched "
        "nothing - and grep printed it looking correct, because a backspace is invisible in terminal output. "
        "Once that was fixed the TRAILING \\b was still wrong: an underscore follows the digits and an "
        "underscore IS a word character, so no boundary exists there. Two silent failures in one "
        "three-character assertion. The only reason either surfaced is that a KNOWN order came back "
        "unattributed, which is why a check should always be run against a case whose answer you already know."),
    "v4": {"file": "Ezek/author_wave_worklist.v4.json", "sha256": sha(W), "bytes": W.stat().st_size,
           "items": w["counts"]["items_total"], "by_class": w["counts"]["by_class"],
           "fixtures": "%d, all fired" % len(w["negative_fixtures"]["results"]),
           "items_moving_a_seam": w["counts"]["items_moving_a_seam"],
           "v1_v2_v3_all_kept": True},
    "blocks_author_wave": False, "status": "DONE", "tier": "MEASURED",
    "opened_at": NOW,
}
with Q.open("a", encoding="utf-8", newline="\n") as fh:
    fh.write(json.dumps(entry, ensure_ascii=False) + "\n")

# ---- the ledger row: the class is general and has now recurred three times in one book
rows = [json.loads(l) for l in JL.read_text(encoding="utf-8").splitlines() if l.strip()]
assert not any(r.get("id") == "E-32" for r in rows), "E-32 already present"
ADD = """
---

## Addendum 2026-09-16 (E-32, session 910cbe15, Ezekiel's author-wave preparation) — AN ARTIFACT ASSEMBLED FROM *PART* OF AN ORDER, AND REPORTED AS BUILT FROM THE ORDER: three instances in one book, and why E-31's cure was not enough

WHAT HAPPENED, three times, by the same agent inside one book:

1. **E-31.** A ruling ordered four changes to a validator. The patch applied three and the orchestrator wrote
   that all four were applied. About 300 of 444 reported verses were artifacts of the missing clause.
2. **A worklist class built from one measurement where the order says a union.** The ruling set the quotation
   worklist as "the arm's output UNIONED with every peer's hand-named run". The builder used a third,
   larger-looking measurement (the boss audit's own sweep) alone. Measured afterwards: one arm-named run and
   seven peer-named runs had no item.
3. **A whole class family omitted.** The ruling's `worklist_basis_per_class` names "C1, C4, A2, A3 silent rows,
   A7, A9, A10, A16, D1, D7, D10" and its execution order makes those rewrites step 2. The worklist carried none
   of them. Seventeen rows had a per-row order and nothing to discharge it — and seventeen of those orders sat in
   the `author_wave` field of records the builder had already opened to read a different field out of.

THE SHAPE IS ONE SHAPE: **an artifact assembled from PART of an order, then reported as built from the order.**
It is not a counting error and it is not laziness; in all three cases the builder believed it had built the
thing. What it had actually built was the part of the thing it had in mind.

WHY E-31'S CURE DID NOT PREVENT 2 AND 3. E-31's cure was to GENERATE THE COMPLETION REPORT BY ITERATING THE
ORDER'S CLAUSE LIST. That is sound, and it catches a misreported build. It cannot catch a build whose SCOPE was
short, because the report iterates the clauses **the builder knew about**. A report generated from a
short list is internally consistent and still wrong.

THE CURE THAT COVERS ALL THREE. The validating fixture must be **GENERATED FROM THE ORDER'S OWN TEXT, by a reader
that walks the order exhaustively rather than looking where the builder expects requirements to be.** In this
instance: a fixture that walks every ruling for order-bearing fields and fails the build if any per-row order has
no item of a class that could discharge it. The builder's class list stops being the boundary of what gets
checked.

GENERALISABLE BEYOND THIS CAMPAIGN. Wherever work is performed against a specification — a ticket, an RFC, a
review checklist, acceptance criteria, a migration plan — **derive the acceptance test from the specification
document, not from the implementer's understanding of it.** The test should be able to fail for a requirement the
implementer never read. If the only things checked are the things someone remembered, the check is a mirror.

A SMALL METHOD NOTE THAT COST TWO ROUNDS HERE. The order-finder needed to match a row id inside a key name. The
`\\b` in its pattern, written through a shell heredoc, became a literal BACKSPACE (U+0008) — and terminal output
printed the pattern looking correct, because a backspace is invisible. Once fixed, the trailing `\\b` was still
wrong, because an underscore follows the digits and an underscore is a word character. **Run every new matcher
against a case whose answer you already know**; both failures surfaced only because a known order came back
unattributed.
"""
E32 = {
    "id": "E-32",
    "kind": "error_pattern",
    "date": "2026-09-16",
    "headline": ("an artifact assembled from PART of an order and reported as built from the order - three "
                 "instances in one book, and why E-31's report-from-the-clause-list cure was insufficient"),
    "severity": "high",
    "severity_basis": ("instance 3 alone would have run the author wave's second execution step with an empty "
                       "worklist, leaving 17 ruled grounds repairs undone while every gate reported green; no "
                       "corpus row was wrongly changed because all three were caught before the wave"),
    "instances": [
        "E-31: four ordered clauses reported as applied, three applied",
        "the quotation worklist built from one measurement where the order says a union of two others (one "
        "arm-named and seven peer-named runs missing)",
        "a whole class family (C1/C4/A2/A3/A7/A9/A10/A16/D1/D7/D10) omitted from the worklist; 17 rows had a "
        "per-row order and no discharging item, 17 of those orders sitting in a field of records the builder "
        "had already opened",
    ],
    "shape": "an artifact assembled from PART of an order, then reported as built from the order",
    "why_E_31s_cure_was_insufficient": ("E-31's cure generates the completion report by iterating the order's "
                                        "clause list, which catches a MISREPORTED build but not a build whose "
                                        "SCOPE was short - the report iterates the clauses the builder knew "
                                        "about, so a report generated from a short list is internally "
                                        "consistent and still wrong"),
    "cure": ["the validating fixture is GENERATED FROM THE ORDER'S OWN TEXT by a reader that walks the order "
             "exhaustively, not by the builder's class list",
             "the acceptance test must be able to FAIL for a requirement the implementer never read",
             "general form: derive the acceptance test from the specification document, never from the "
             "implementer's understanding of it - if the only things checked are the things someone "
             "remembered, the check is a mirror"],
    "matcher_note": ("a \\b written through a shell heredoc became a literal BACKSPACE (U+0008) and terminal "
                     "output printed the pattern looking correct; once fixed, the trailing \\b was still wrong "
                     "because an underscore follows the digits. Run every new matcher against a case whose "
                     "answer you already know."),
    "generalisable": ("any work against a ticket, RFC, review checklist, acceptance criteria or migration plan"),
    "recorded_by": "orchestrator (claude-opus-5)",
    "recorded_at": NOW,
}
md_pre, jl_pre = MD.read_bytes(), JL.read_bytes()
t1 = MD.with_suffix(".md.tmpE32")
t1.write_bytes(md_pre + ADD.encode("utf-8"))
t1.replace(MD)
t2 = JL.with_suffix(".jsonl.tmpE32")
t2.write_bytes(jl_pre + (json.dumps(E32, ensure_ascii=False) + "\n").encode("utf-8"))
t2.replace(JL)

print(json.dumps({"appended": "E13-65", "queue_rows": len(Q.read_text(encoding="utf-8").strip().splitlines()),
                  "v4_sha256": sha(W), "items": w["counts"]["items_total"],
                  "ledger_md_lines": len(MD.read_text(encoding="utf-8").splitlines()),
                  "ledger_md_sha256": sha(MD),
                  "ledger_rows": len([l for l in JL.read_text(encoding="utf-8").splitlines() if l.strip()]),
                  "ledger_jsonl_sha256": sha(JL)}, indent=1))
