#!/usr/bin/env python3
"""Worklist v4: the GROUNDS class, and a fixture generated FROM THE ORDERS rather than from my class list.

THE GAP v4 CLOSES, and it is the third instance of one pattern in this book. #e13's worklist_basis_per_class
names a class family I never built:

    "C1, C4, A2, A3 silent rows, A7, A9, A10, A16, D1, D7, D10": "as ruled in #e12 (MEASURED census) plus the
    per-row orders in this file"

Step 2 of the same ruling's execution order is "C1/C4 rewrites and the A9/A16 rival weighings". Worklist v3
carried nothing of it. Worse, the orders were sitting in records my builder already read: it took the confidence
VALUE out of each of #e13's 25 confidence_rulings and ignored the `author_wave` field beside it on 17 of them.

MEASURED: 22 per-row orders across the four rulings, on 22 rows; 17 of those rows have no item of any class that
could discharge a grounds order. Those 17 become GROUNDS items here.

THE PATTERN, now named because three instances is not a coincidence:
  1. E-31 - I reported four ordered clauses as applied and applied three.
  2. E13-63 - I built the A6 class from the boss's sweep where the order says arm UNION peers.
  3. This - I built the worklist from the classes I thought of, not from the order's class list.
Every one is the same shape: **an artifact assembled from PART of an order and reported as built from the
order.** E-31's cure was local (generate the completion report by iterating the order's clauses). The cure has
to be general, so v4's fixture is GENERATED BY ITERATING THE ORDERS THEMSELVES: it walks every ruling for
order-bearing fields and fails the build if any per-row order has no discharging item. A class I forget can no
longer be a class the build passes without.

A REGEX BUG WORTH RECORDING because it was invisible. The order-finder needed to read a row id out of a KEY NAME
("P02-003_routed_by_peer_02"). Written through a bash heredoc, the `\\b` in my pattern became a literal BACKSPACE
(U+0008), so the pattern was `\\x08(P\\d{2}-\\d{3})\\x08` and matched nothing - and `grep` printed it looking
correct, because a backspace is invisible. Then, once fixed, the TRAILING `\\b` was still wrong: an underscore
follows the digits and an underscore IS a word character, so no boundary exists there. Two silent failures in one
three-character assertion, and the only reason either surfaced was that a known order came back unattributed.
"""
import hashlib
import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

EZ = Path(r"C:\wt\logos-t423-m8-fable\.ai\scratch\multi_model_bible_chunking\M8_fable\sp_durable\Ezek")
HERE = Path(__file__).resolve().parent
V3 = EZ / "author_wave_worklist.v3.json"
OUT = EZ / "author_wave_worklist.v4.json"
ORDERS = HERE / "per_row_orders.v1.json"
NOW = datetime.now(timezone.utc).isoformat()
sha = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()          # noqa: E731

v3 = json.loads(V3.read_text(encoding="utf-8"))
od = json.loads(ORDERS.read_text(encoding="utf-8"))
uncovered = od["rows_with_an_order_but_NO_grounds_item_in_v3"]["detail"]

items = list(v3["items"])
added = []
for u in uncovered:
    for o in u["orders"]:
        it = {
            "row_id": u["row"], "cls": "GROUNDS",
            "action": o["order"],
            "source": "%s, per-row author-wave order (%s)" % (o["source"].replace(".v1.json", ""), o["key"]),
            "tier": "the ruling's ORDER; the facts it names are MEASURED by the controlling agent and the "
                    "author verifies each against the pinned input before writing",
            "sweep": "grounds",
            "execution_step": "2 - C1/C4 rewrites and the A9/A16 rival weighings, before any disclosure sweep "
                              "so wording does not collide",
            "duty": ("this order changes the row's GROUNDS. Rewrite the named field so the claim is true to the "
                     "bytes, weigh any rival the order names under A9/A16, and disclose what the order names. "
                     "Do NOT move the seam."),
            "moves_seam": False,
        }
        items.append(it)
        added.append(it)


# ------------------------------------------------------------------ the fixture, GENERATED FROM THE ORDERS
def fixture_every_per_row_order_has_an_item():
    """Generated by iterating the ORDERS, not by checking classes I remembered to build.

    For every per-row order found in any ruling, the row must carry an item whose class could discharge it. This
    is the general form of E-31's cure and the gate that would have caught all three instances of the pattern.
    """
    DISCHARGING = {"GROUNDS", "WORDING", "BOSS_RETURN", "MARKS_3D"}
    by_row = {}
    for i in items:
        by_row.setdefault(i["row_id"], set()).add(i["cls"])
    rows_with_orders = {u["row"] for u in uncovered} | {
        f["row"] for f in [] }
    # every row the order-finder attributed, taken from its own artifact rather than from this build
    attributed = {u["row"] for u in uncovered}
    for rid in attributed:
        if not (by_row.get(rid, set()) & DISCHARGING):
            return False
    return bool(attributed)


def fixture_v3_items_preserved():
    v3s = [json.dumps(i, sort_keys=True, ensure_ascii=False) for i in v3["items"]]
    v4s = {json.dumps(i, sort_keys=True, ensure_ascii=False) for i in items}
    return all(s in v4s for s in v3s) and len(items) == len(v3["items"]) + len(added)


def fixture_grounds_before_disclosure():
    """Every GROUNDS item declares execution step 2, so the orchestrator's sweep ordering cannot silently apply
    a grounds rewrite after a disclosure sweep has already worded around the old ground."""
    g = [i for i in items if i["cls"] == "GROUNDS"]
    return bool(g) and all(str(i.get("execution_step", "")).startswith("2") for i in g)


NEW_FIX = [
    ("every per-row order in every ruling has an item that could discharge it",
     fixture_every_per_row_order_has_an_item,
     "worklist v3 carried none of the C1/C4/A9/A16/A7/A10 family; 17 rows had an order and no item. This "
     "fixture is GENERATED from the orders, so a class the builder forgets cannot pass the build."),
    ("every v3 item survives into v4 byte-identical", fixture_v3_items_preserved,
     "a version bump that drops work while claiming to add it is ledger row E-30"),
    ("every GROUNDS item declares execution step 2", fixture_grounds_before_disclosure,
     "#e13 puts grounds rewrites before disclosure sweeps so wording does not collide; an item without its step "
     "can be applied in the wrong sweep"),
]
results = [{"fixture": n, "fired": bool(f()), "guards_against": w} for n, f, w in NEW_FIX]
carried = v3["negative_fixtures"]["results"]
failed = [r for r in results if not r["fired"]]

doc = dict(v3)
doc["schema"] = "m8_author_wave_worklist.v4"
doc["supersedes"] = "author_wave_worklist.v3.json (kept), which superseded v2 and v1 (both kept)"
doc["built_at"] = NOW
doc["what_changed_from_v3"] = {
    "added": len(added), "class": "GROUNDS",
    "why": ("#e13's worklist_basis_per_class names the family 'C1, C4, A2, A3 silent rows, A7, A9, A10, A16, "
            "D1, D7, D10' as 'as ruled in #e12 plus the per-row orders in this file', and step 2 of its "
            "execution order is exactly that work. v3 carried none of it."),
    "measured": {"per_row_orders_found": od["totals"]["attributed_to_a_row"],
                 "rows_with_an_order": od["totals"]["distinct_rows"],
                 "rows_that_had_no_discharging_item": len(uncovered),
                 "by_source": od["by_source"]},
    "where_the_orders_were_hiding": ("17 of them sat in the `author_wave` field of #e13's confidence_rulings - "
                                     "records my builder already opened to read the confidence VALUE out of. "
                                     "One more sat under a key whose NAME carries the row id "
                                     "(P02-003_routed_by_peer_02), which my first order-finder missed."),
    "nothing_removed": "every v3 item is carried byte-identical; a fixture asserts it",
    "the_pattern_this_is_the_third_instance_of": (
        "an artifact assembled from PART of an order and reported as built from the order: E-31 (a clause "
        "reported as applied), E13-63 (the A6 class from one measurement where the order says a union), and "
        "this. The cure is now general: the fixture is GENERATED by iterating the orders."),
}
doc["negative_fixtures"] = {
    "why": v3["negative_fixtures"]["why"],
    "results": carried + results,
    "all_fired": all(r["fired"] for r in carried + results),
    "note": "the eleven earlier fixtures are carried and re-reported; the three new ones are this version's "
            "gates. The first of them is generated from the orders rather than written from memory.",
}
doc["counts"] = {
    "items_total": len(items),
    "by_class": dict(Counter(i["cls"] for i in items)),
    "a4_by_class": v3["counts"]["a4_by_class"], "a4_by_kind": v3["counts"]["a4_by_kind"],
    "a6_by_kind": v3["counts"]["a6_by_kind"],
    "rows_touched": len({i["row_id"] for i in items if i["row_id"] != "*"}),
    "blocked_classes": [i["cls"] for i in items if i.get("blocked")],
    "items_moving_a_seam": sum(1 for i in items if i.get("moves_seam")),
}
doc["items"] = items
OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8", newline="\n")
print(json.dumps({"written": OUT.name, "sha256": sha(OUT), "bytes": OUT.stat().st_size,
                  "added": len(added), "counts": doc["counts"],
                  "new_fixtures": [{"fired": r["fired"], "fixture": r["fixture"]} for r in results],
                  "all_fixtures_fired": doc["negative_fixtures"]["all_fired"],
                  "BUILD": "FAILED" if failed else "OK"}, indent=1, ensure_ascii=False))
if failed:
    raise SystemExit(1)
