#!/usr/bin/env python3
"""Materialize Sol's provisional literary seams for Matthew--Acts.

The output is candidate-only: chapter-complete spans, no doctrinal or
historical adjudication.  Each seam carries the form, language, intertext,
and red-team holds that a later controller-backed B01 run must test.
"""
from __future__ import annotations
import argparse, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / ".ai/scratch/multi_model_bible_chunking/M7_sol"

# start/end chapter, working title, form, difficulty classes, cross-reference seeds
U = {
"Matt": [
(1,1,"Genealogy and birth narrative","genealogy+narrative",["genealogy_forms","translation_variants"],["Luke.3.23-Luke.3.38"]),(2,2,"Magi, flight, and return","birth_narrative+fulfillment_formula",["geography","quotation_formulas"],["Hos.11.1-Hos.11.11"]),(3,4,"Baptism, testing, and first proclamation","call+narrative+conflict",["temptation_lexicon","Isaianic_terms"],["Deut.8.1-Deut.8.20"]),(5,7,"Mountain teaching: blessedness, Torah, prayer, and discernment","discourse+aphorism+prayer",["makarismoi","righteousness_terms","metaphor_boundaries"],["Exod.20.1-Exod.20.21"]),(8,9,"Healings, discipleship, and commission scenes","miracle_cycle+dialogue",["healing_verbs","Son_of_Man_idiom"],["Isa.53.1-Isa.53.12"]),(10,10,"The Twelve sent and warned","mission_speech",["mission_vocabulary","Semitic_idioms"],["Mic.7.1-Mic.7.7"]),(11,12,"John's question, wisdom sayings, and Sabbath controversies","dialogue+wisdom+controversy",["yoke_metaphor","Sabbath_lexicon"],["Isa.35.1-Isa.35.10"]),(13,13,"Kingdom parables","parable_cycle",["parable_genre","harvest_terms"],["Ps.78.1-Ps.78.72"]),(14,15,"John's death, feeding, and contested purity","narrative+miracle+controversy",["bread_terms","handwashing_lexicon"],["2Kgs.4.1-2Kgs.4.44"]),(16,17,"Confession, first passion announcement, and mountain transfiguration","dialogue+narrative+theophany",["ekklesia_term","Moses_Elijah_allusion"],["Exod.24.1-Exod.24.18"]),(18,18,"Community discourse: little ones, correction, and forgiveness","community_speech+parable",["ekklesia_usage","seventy_seven_number"],["Gen.4.1-Gen.4.26"]),(19,20,"Journey sayings, laborers, and servant discourse","journey_narrative+parable+speech",["divorce_terms","first_last_idiom"],["Deut.24.1-Deut.24.4"]),(21,22,"Jerusalem entry, temple actions, and confrontation parables","entry+narrative+parable+controversy",["Hosanna_transliteration","vineyard_legal_language"],["Zech.9.9-Zech.9.17"]),(23,23,"Woes against scribal performance","woe_speech",["hypocrite_term","woe_formula"],["Isa.5.8-Isa.5.30"]),(24,25,"Eschatological discourse and readiness parables","apocalyptic_speech+parable",["parousia_term","watchfulness_metaphor"],["Dan.7.1-Dan.7.28"]),(26,28,"Passion, burial, and resurrection narratives","passion_narrative+commission",["cup_covenant_terms","resurrection_vocabulary"],["Ps.22.1-Ps.22.31"])],
"Mark": [
(1,1,"Opening, baptism, testing, and first calls","prologue+narrative",["euangelion_term","voice_formula"],["Isa.40.1-Isa.40.11"]),(2,3,"Authority disputes and parabolic response","controversy+parable",["forgiveness_verbs","Son_of_Man_idiom"],["Hos.6.1-Hos.6.11"]),(4,4,"Parables and storm crossing","parable+miracle",["parable_explanation","sleeping_storm_imagery"],["Ps.107.1-Ps.107.43"]),(5,6,"Exorcism, healings, feeding, and purity","miracle_cycle+controversy",["unclean_spirit_terms","touch_lexicon"],["2Kgs.4.1-2Kgs.4.44"]),(7,8,"Purity debate, Gentile encounter, feeding, and recognition","controversy+miracle+dialogue",["korban_term","bread_fragment_wordplay"],["Isa.35.1-Isa.35.10"]),(9,9,"Transfiguration, second passion saying, and discipleship","theophany+speech",["epiphany_terms","child_status_idiom"],["Mal.3.1-Mal.4.6"]),(10,10,"Marriage, children, wealth, and servant pattern","teaching+dialogue",["hard_saying_translation","ransom_lytron"],["Gen.2.18-Gen.2.25"]),(11,12,"Entry, temple action, controversies, and widow's offering","entry+controversy+observation",["fig_tree_sequence","lepton_term"],["Zech.9.9-Zech.9.17"]),(13,13,"Apocalyptic discourse","apocalyptic_speech",["abomination_phrase","tribulation_terms"],["Dan.9.20-Dan.9.27"]),(14,16,"Anointing, passion, burial, and empty tomb","passion_narrative",["young_man_note","Aramaic_cries"],["Ps.22.1-Ps.22.31"])],
"Luke": [
(1,2,"Preface, annunciations, births, and childhood scenes","preface+narrative+song",["historiographic_preface","Magnificat_register"],["1Sam.2.1-1Sam.2.10"]),(3,4,"Genealogy, testing, and Nazareth program","genealogy+prophetic_speech",["genealogy_order","Isaiah_translation"],["Isa.61.1-Isa.61.11"]),(5,6,"Calls, healings, controversies, and plain teaching","narrative+controversy+discourse",["catch_of_fish_idiom","Sabbath_terms"],["Exod.20.8-Exod.20.11"]),(7,8,"Faith encounters, women, parable speech, and discipleship","miracle+parable+narrative",["centurion_speech","seed_metaphor"],["1Kgs.17.8-1Kgs.17.24"]),(9,9,"Mission, feeding, recognition, and transfiguration","mission+narrative+theophany",["Herod_questions","exodus_term"],["Exod.34.1-Exod.34.35"]),(10,10,"Seventy-two mission, Good Samaritan, and Mary/Martha","mission+parable+dialogue",["seventy_two_variant","neighbor_term"],["Lev.19.17-Lev.19.18"]),(11,12,"Prayer, woes, warnings, and confession","teaching+woe_speech",["daily_bread_variant","hypocrite_term"],["Isa.5.8-Isa.5.30"]),(13,14,"Kingdom images, Sabbath meal, and banquet parables","parable+meal_narrative",["mustard_tree","honor_shame_terms"],["Prov.25.6-Prov.25.7"]),(15,16,"Lost things, stewardship, and wealth sayings","parable_cycle+wisdom",["parable_endings","mammon_term"],["Ezek.34.1-Ezek.34.31"]),(17,18,"Faith, coming reign, judge, and child sayings","teaching+parable",["kingdom_within_phrase","persistent_prayer"],["Dan.7.13-Dan.7.14"]),(19,19,"Zacchaeus, minas, and entry","narrative+parable+entry",["minas_talent_distinction","messianic_psalm_echo"],["Zech.9.9-Zech.9.17"]),(20,21,"Temple controversies and widow's offering","controversy+observation",["authority_question","lepton_term"],["Ps.118.22-Ps.118.27"]),(22,23,"Last supper, trial, crucifixion, and lament","passion_narrative",["covenant_wording","criminal_term"],["Isa.53.1-Isa.53.12"]),(24,24,"Resurrection appearances and Emmaus","narrative+commission",["breaking_bread_phrase","scripture_opening_idiom"],["Gen.3.1-Gen.3.24"])],
"John": [
(1,1,"Prologue, witness, and first disciples","hymnic_prologue+narrative",["logos_term","witness_verb"],["Gen.1.1-Gen.1.5"]),(2,4,"Signs, temple action, Nicodemus, and Samaritan encounter","sign_narrative+dialogue",["gennao_ambiguity","living_water_metaphor"],["Ezek.36.24-Ezek.36.28"]),(5,6,"Healing, discourse, feeding, and bread discourse","sign+discourse",["life_age_terms","bread_of_life_metaphor"],["Exod.16.1-Exod.16.36"]),(7,8,"Festival disputes, light/water sayings, and witness controversy","festival_dialogue+controversy",["adulteress_pericope_textual_status","ego_eimi_formula"],["Isa.55.1-Isa.55.3"]),(9,10,"Blindness sign, shepherd discourse, and feast dispute","sign+metaphor+controversy",["poimen_lexicon","dedication_feast_context"],["Ezek.34.1-Ezek.34.31"]),(11,12,"Lazarus, anointing, entry, and public response","sign+narrative+entry",["resurrection_verb","Greek_transliteration"],["1Kgs.17.17-1Kgs.17.24"]),(13,14,"Footwashing and farewell opening","farewell_narrative+symbolic_action",["washing_symbolism","parakletos_term"],["Gen.18.1-Gen.18.8"]),(15,17,"Farewell discourses and prayer","farewell_speech+prayer",["meno_verb","unity_language"],["Deut.31.1-Deut.31.30"]),(18,19,"Arrest, hearings, crucifixion, and burial","passion_narrative",["basileia_term","tetelestai_form"],["Ps.22.1-Ps.22.31"]),(20,21,"Resurrection appearances and epilogue","narrative+commission",["breath_spirit_wordplay","beloved_disciple_note"],["Gen.2.7-Gen.2.7"])],
"Acts": [
(1,2,"Prologue, ascension, Pentecost, and inaugural speech","prologue+speech+theophany",["apostolos_term","glossolalia_translation"],["Joel.2.28-Joel.2.32"]),(3,5,"Temple healing, speeches, communal life, and trials","miracle+speech+community_narrative",["pais_ambiguity","koinonia_term"],["Deut.18.15-Deut.18.19"]),(6,8,"Seven, Stephen's speech, and dispersion","community_narrative+defense_speech+mission",["diakonia_term","martyros_term"],["Amos.5.25-Amos.5.27"]),(9,9,"Saul's call and initial proclamation","call+narrative",["voice/hearing_variants","conversion_call_form"],["Gal.1.11-Gal.1.24"]),(10,12,"Cornelius, Jerusalem recognition, and Herod episode","mission+narrative+deliverance",["clean_unclean_terms","angelic_deliverance"],["Lev.11.1-Lev.11.47"]),(13,14,"Antioch mission and first journey","mission+narrative+speech",["synagogue_speech","quotations_in_LXX"],["Isa.49.6-Isa.49.6"]),(15,16,"Jerusalem council and Macedonian call","council+narrative+vision",["parepidemos_terms","decree_wording"],["Amos.9.11-Amos.9.12"]),(17,18,"Thessalonica, Athens speech, and Corinth","mission+speech+narrative",["unknown_god_phrase","resurrection_vocab"],["Isa.42.5-Isa.42.9"]),(19,20,"Ephesus, riot, and farewell to elders","mission+riot+farewell_speech",["magic_books_notice","presbyteros/episkopos_terms"],["Ezek.33.1-Ezek.33.9"]),(21,22,"Jerusalem arrest and first defense","arrest+narrative+defense_speech",["vow_purification_terms","Hebrew_dialect_note"],["Acts.9.1-Acts.9.19"]),(23,24,"Council, plot, and hearings before Felix","trial_narrative+defense_speech",["resurrection_dispute","Roman_legal_titles"],["Acts.22.1-Acts.22.29"]),(25,26,"Festus, Agrippa, and appeal to Caesar","trial_narrative+royal_speech",["legal_formulae","prophetic_commission"],["Acts.9.1-Acts.9.19"]),(27,28,"Voyage, shipwreck, Malta, and Rome","travel_narrative+healing+open_ending",["nautical_terms","end_point_structure"],["Jonah.1.1-Jonah.1.17"])],
}

def chapters(book: str):
    d={}
    with (ROOT/"data/canonical/scripture/passages/passages.jsonl").open(encoding="utf-8") as f:
        for line in f:
            x=json.loads(line)
            if x.get("book") != book: continue
            c=int(x["chapter"]); lo=int(x["verse_start"]); hi=int(x["verse_end"])
            d[c]=(min(lo,d[c][0]) if c in d else lo,max(hi,d[c][1]) if c in d else hi)
    return d

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("books",nargs="*",default=list(U)); args=ap.parse_args()
    for book in args.books:
        ch=chapters(book); covered=set(); rows=[]
        for i,(a,b,title,form,diffs,seeds) in enumerate(U[book],1):
            if any(c not in ch or c in covered for c in range(a,b+1)): raise SystemExit(f"bad overlap/coverage {book} {a}-{b}")
            covered.update(range(a,b+1)); rows.append({"model_id":"M7_sol","book":book,"span":f"{book}.{a}.{ch[a][0]}-{book}.{b}.{ch[b][1]}","chunk_index_in_book":i,"working_title":title,"literature_type_guess":form,"boundary_evidence_refs":["canonical_passage_identity_only","gospels_acts_form_transition_register.v1","whole_bible_role_source_matrix.v1"],"strong_or_hebrew_tags_used":["evidence_only","lexical_review_pending"],"wj_or_red_letter_considered":False,"frontier_flag_considered":True,"confidence":"low","decision_id":f"M7_sol-{book}-{i:03d}","boundary_rationale":"Provisional chapter-complete seam at a narrated scene, speech, song, parable, sign, trial, or travel transition; pending controller-backed original-language and literary red-team review.","difficulty_classes":diffs,"cross_reference_seed_refs":seeds,"review_revision":0,"review_status":"candidate_structural_unit_pending_b01_mesh","review_holds":["original_language_translation_review","literary_form_redteam","canonical_cross_reference_premortem","ancient_context_gap","boss_authorization","external_provider_review","human_appeal_review"],"non_authorizing":True})
        if covered != set(ch): raise SystemExit(f"coverage mismatch {book}: {sorted(set(ch)-covered)}")
        out=MODEL/"book_chunks"/book/"chunks.jsonl"; out.parent.mkdir(parents=True,exist_ok=True); out.write_text("".join(json.dumps(x,separators=(",",":"))+"\n" for x in rows),encoding="utf-8",newline="\n")
        (MODEL/"book_strategy"/f"{book}.md").write_text(f"# {book} candidate structural strategy\n\n- candidate_only: true\n- non_authorizing: true\n- units: {len(rows)}\n- exact_chapter_coverage: true\n- confidence: low\n- B01 role mesh: pending\n\nLiterary/form seams are provisional; no doctrinal or historical conclusions are encoded.\n",encoding="utf-8",newline="\n")
        print(json.dumps({"book":book,"chunks":len(rows),"chapters":len(ch),"candidate_only":True},sort_keys=True))

if __name__=="__main__": raise SystemExit(main())
