#!/usr/bin/env python3
"""Create receipt-only NT B01 packets with explicit Greek-source limitations."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
from scripts.build_whole_bible_b01_controller_r8 import ControllerRun,prepare
ROOT=Path(__file__).resolve().parents[1]; MODEL=ROOT/".ai/scratch/multi_model_bible_chunking/M7_sol"
COMMON=[ROOT/p for p in ["config/agents/families/scripture-first-biblical-chunking/whole_bible_campaign_registry.v1.json","config/agents/families/scripture-first-biblical-chunking/whole_bible_candidate_workflow.v2.yaml","config/agents/families/scripture-first-biblical-chunking/whole_bible_candidate_prompt_pack.v2.yaml","config/agents/families/scripture-first-biblical-chunking/codex_desktop_campaign_adapter.v2.yaml","data/canonical/scripture/passages/passages.jsonl","data/canonical/translations/eng-web/translation_witnesses.jsonl"]]
GREEK=[ROOT/p for p in ["data/raw/original_language/greek/cntr_sr/source_manifest.yaml","data/raw/original_language/greek/cntr_sr/raw/cntr_sr-4be18e67c687.zip","data/candidate/original_language_evidence/canonical_source_views/cntr_sr/canonical_source_view_manifest.yaml","data/candidate/original_language_evidence/canonical_source_views/cntr_sr/included_files.jsonl","data/raw/original_language/greek/sblgnt/source_manifest.yaml","data/raw/original_language/greek/sblgnt/raw/sblgnt-c4d241a9c4c1c4.zip","data/raw/original_language/greek/ugnt/source_manifest.yaml","data/raw/original_language/greek/ugnt/raw/ugnt-6377ea89a718.zip","config/chunking/form_registry.yaml",".ai/control/t423_literary_marker_quality_protocol.yaml",".ai/control/t468_owner_faithful_chunking_policy.yaml",".ai/control/bible_wide_chunking_research_registry.yaml",".ai/control/contextual_reading_policy.yaml",".ai/control/autonomous_corpus_processor.yaml"]]
GREEK[5]=ROOT/"data/raw/original_language/greek/sblgnt/raw/sblgnt-c4d241a9c1c4.zip"
NT=["Matt","Mark","Luke","John","Acts","Rom","1Cor","2Cor","Gal","Eph","Phil","Col","1Thess","2Thess","1Tim","2Tim","Titus","Phlm","Heb","Jas","1Pet","2Pet","1John","2John","3John","Jude","Rev"]
ROLES=("original_language_translation_scout","literary_form_scout","canonical_relations_and_premortem_scout","second_temple_rabbinic_context_scout")
def sha(p): return "sha256:"+hashlib.sha256(p.read_bytes()).hexdigest()
def pd(p):
 rows={f.name:hashlib.sha256(json.dumps(json.loads(f.read_text()),sort_keys=True,separators=(",",":")).encode()).hexdigest() for f in sorted(p.glob("*.json")) if f.name!="boss-authorization.json"}; return "sha256:"+hashlib.sha256(json.dumps(rows,sort_keys=True,separators=(",",":")).encode()).hexdigest()
def run_book(book):
 rid=f"{book.lower()}-r8-held-1"; att="b01-controller-1"; root=MODEL/"state/r8"/book/rid; run=prepare(root=root,book=book,run_id=rid,attempt_id=att,source_paths=COMMON+GREEK,controller_instance_id=f"controller-{book.lower()}-r8")
 count=len((MODEL/"book_chunks"/book/"chunks.jsonl").read_text().splitlines()); claims={ROLES[0]:f"Koine Greek translation and lexical pressures for {book} require qualified corpus comparison; no single gloss authorizes a boundary.",ROLES[1]:f"The {book} candidate file contains {count} low-confidence discourse/form units requiring literary red-team review.",ROLES[2]:f"Canonical relation seeds for {book} remain unverified context candidates and cannot authorize graph edges or local splits.",ROLES[3]:"No qualified ancient Jewish, Second Temple, or rabbinic corpus is activated; this lane is an explicit gap."}
 for i,role in enumerate(ROLES,1):
  a=run.assign(role,provider_family="codex-gpt5-correlated-local"); report={"observations":[{"observation_id":f"{book}-NT-{i}","scope":book,"claim":claims[role],"evidence_refs":["whole_bible_role_source_matrix.v1",f"book_chunks/{book}/chunks.jsonl"],"confidence":"low"}],"uncertainties":["Greek sources are corpus-level and not independent provider votes","B01 receipt-only"],"source_refs":[f".ai/scratch/multi_model_bible_chunking/M7_sol/book_chunks/{book}/chunks.jsonl","data/raw/original_language/greek/cntr_sr/source_manifest.yaml"]}; run.record_result(a,agent_instance_id=f"codex-{book.lower()}-role-{i:02d}",provider_family="codex-gpt5-correlated-local",report=report)
 root.joinpath("redteam-note.json").write_text(json.dumps({"schema_version":"whole_bible_b01_redteam_note.v1","kind":"redteam_note","book":book,"run_id":rid,"stage_attempt_id":att,"candidate_only":True,"non_authorizing":True,"shared_model_substrate":True,"counts_as_cross_model_independent_vote":False,"findings":[{"finding_id":f"{book}-NT-RT-001","severity":"high","claim":"Corpus-level Greek source closure and shared substrate do not establish independent provider agreement."}],"dissent_preserved":True},sort_keys=True,separators=(",",":")))
 boss_exec=f"exec-{book.lower()}-r8-boss"; boss_asg=f"asg-{book.lower()}-r8-boss"; evt=f"evt-{book.lower()}-r8-boss-reviewed"; run._event(event_id=evt,event_kind="boss_reviewed",execution_id=boss_exec,assignment_id=boss_asg,result_digest=sha(root/"redteam-note.json")); packet=root/"packet"; boss={"schema_version":"whole_bible_b01_boss_authorization.v2","kind":"boss_authorization","book":book,"run_id":rid,"stage_attempt_id":att,"candidate_only":True,"non_authorizing":True,"identity":{"execution_id":boss_exec,"assignment_id":boss_asg,"agent_instance_id":f"codex-{book.lower()}-boss","role_id":"evidence_dispute_boss","provider_family":"codex-gpt5-correlated-local"},"controller_event_ids":[evt],"input_manifest_sha256":run.manifest_sha256,"packet_sha256":pd(packet),"redteam_digest":sha(root/"redteam-note.json"),"verdict":"GO_B01_RECEIPT_ONLY","rationale":"Receipt-only candidate packet; corpus-level Greek limitations and correlated substrate remain held.","rejected_alternatives":["promote boundaries","treat corpus rows as independent votes"],"dissent":["QF-CORRELATED-SUBSTRATE","QF-GREEK-CORPUS-CLOSURE"],"appeal_route":"human or external-provider review"}; (packet/"boss-authorization.json").write_text(json.dumps(boss,sort_keys=True,separators=(",",":")))
def main():
 for b in NT: run_book(b)
 print(json.dumps({"books":len(NT),"verdict":"GO_B01_RECEIPT_ONLY","B02_authorized":False})); return 0
if __name__=="__main__": raise SystemExit(main())
