#!/usr/bin/env python3
"""First-pass scan of the ACTUAL raw source documents (the real pipeline input).

Hard rule (AI_FRONT_DOOR + CLAUDE.md): before designing or changing any
ingest/chunking/graph processing, an agent MUST inspect the real raw documents.
This script makes that pass deterministic and checkable. It scans every archive
under data/raw/ for USFM content and inventories the actual marker + metadata
vocabulary, then writes `.ai/control/RAW_SOURCE_INVENTORY.md`.

`--check` regenerates in-memory and fails (exit 1) if the committed inventory is
stale relative to the real raw files (ignoring the timestamp line). CI runs this
so the inventory can never silently drift from the source.

Dependency-light and deterministic.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
import zipfile
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW_ROOT = ROOT / "data" / "raw"
OUT = ROOT / ".ai" / "control" / "RAW_SOURCE_INVENTORY.md"
GENERATED_LINE_PREFIX = "**Generated:**"

LINE_MARKER = re.compile(r"^\\([a-z0-9]+)\b", re.I)
ANY_MARKER = re.compile(r"\\\+?([a-z0-9]+)\*?", re.I)
ATTR = re.compile(r"\|([a-z0-9]+)=", re.I)
STRONG = re.compile(r'strong="([HG])')
VERSE = re.compile(r"^\\v\b")
CHAPTER = re.compile(r"^\\c\b")

# Markers a chunker/graph builder must be aware of (called out explicitly).
SPECIAL_MARKERS = {
    "wj": "words of Jesus (speaker = Jesus / red-letter)",
    "fqa": "alternate/variant reading (textual-variant seed)",
    "d": "psalm superscription / descriptive title",
    "qs": "Selah (liturgical rubric)",
    "sp": "speaker label (e.g. Job dialogue)",
    "b": "blank line / stanza break",
    "nd": "divine name",
    "add": "translator-added words",
}


def sha256_short(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:16]


def find_archives() -> list[Path]:
    if not RAW_ROOT.exists():
        return []
    return sorted(RAW_ROOT.rglob("*.zip"), key=lambda p: p.as_posix())


def scan_archive(path: Path) -> dict:
    line_markers: Counter[str] = Counter()
    inline_markers: Counter[str] = Counter()
    attrs: Counter[str] = Counter()
    strong: Counter[str] = Counter()
    verses = chapters = usfm_files = 0
    raw = path.read_bytes()
    with zipfile.ZipFile(path) as z:
        for name in sorted(z.namelist()):
            if not name.lower().endswith((".usfm", ".sfm")):
                continue
            usfm_files += 1
            text = z.read(name).decode("utf-8-sig", errors="replace")
            for line in text.splitlines():
                if VERSE.match(line):
                    verses += 1
                elif CHAPTER.match(line):
                    chapters += 1
                m = LINE_MARKER.match(line)
                if m:
                    line_markers[m.group(1).lower()] += 1
                for mm in ANY_MARKER.finditer(line):
                    inline_markers[mm.group(1).lower()] += 1
                for a in ATTR.finditer(line):
                    attrs[a.group(1).lower()] += 1
                for s in STRONG.finditer(line):
                    strong[s.group(1)] += 1
    # inline counts double-count open+close markers; halve word/char markers heuristically
    return {
        "path": path.relative_to(ROOT).as_posix(),
        "sha256_short": sha256_short(raw),
        "size_bytes": len(raw),
        "usfm_files": usfm_files,
        "verses": verses,
        "chapters": chapters,
        "line_markers": dict(line_markers),
        "inline_markers": dict(inline_markers),
        "attrs": dict(attrs),
        "strong": dict(strong),
    }


def all_markers(scan: dict) -> set[str]:
    return set(scan["line_markers"]) | set(scan["inline_markers"])


def render() -> str:
    archives = find_archives()
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    lines: list[str] = []
    lines.append("# Raw Source Inventory (generated — the actual pipeline input)")
    lines.append("")
    lines.append("<!-- GENERATED by scripts/scan_raw_sources.py. Do not hand-edit.")
    lines.append("     Re-run after any change to data/raw/. CI: scan_raw_sources.py --check. -->")
    lines.append("")
    lines.append(f"{GENERATED_LINE_PREFIX} {now}")
    lines.append("")
    lines.append("This is the **first-pass inventory of the real raw documents** that the pipeline")
    lines.append("ingests, chunks, and turns into a graph. Any agent doing ingest/chunking/graph")
    lines.append("work MUST read this (and re-scan) before changing the processing algorithms.")
    lines.append("Marker coverage is enforced by `scripts/validate_raw_coverage.py` against")
    lines.append("`config/ingest/usfm_marker_coverage.yaml`.")
    lines.append("")
    lines.append("---")
    lines.append("")
    if not archives:
        lines.append("_No raw archives found under data/raw/._")
        lines.append("")
        return "\n".join(lines) + "\n"

    for path in archives:
        scan = scan_archive(path)
        lines.append(f"## `{scan['path']}`")
        lines.append("")
        lines.append(f"- sha256 (short): `{scan['sha256_short']}`")
        lines.append(f"- size: {scan['size_bytes']} bytes")
        lines.append(f"- USFM files: {scan['usfm_files']}")
        lines.append(f"- verses: {scan['verses']:,} | chapters: {scan['chapters']:,}")
        if scan["strong"]:
            h = scan["strong"].get("H", 0)
            g = scan["strong"].get("G", 0)
            lines.append(f"- Strong's lexeme tags: {h + g:,} (Hebrew {h:,} / Greek {g:,})")
        if scan["attrs"]:
            attr_str = ", ".join(f"{k}={v:,}" for k, v in sorted(scan["attrs"].items()))
            lines.append(f"- marker attributes present: {attr_str}")
        lines.append("")
        lines.append("**Line-leading (structural) markers:**")
        lines.append("")
        lines.append("| marker | count |")
        lines.append("|--------|------:|")
        for m, c in sorted(scan["line_markers"].items()):
            lines.append(f"| `{m}` | {c:,} |")
        lines.append("")
        lines.append("**Inline / character markers:**")
        lines.append("")
        lines.append("| marker | count |")
        lines.append("|--------|------:|")
        for m, c in sorted(scan["inline_markers"].items()):
            lines.append(f"| `{m}` | {c:,} |")
        lines.append("")
        present_special = {m: SPECIAL_MARKERS[m] for m in sorted(all_markers(scan)) if m in SPECIAL_MARKERS}
        if present_special:
            lines.append("**Special markers requiring chunker/graph awareness:**")
            lines.append("")
            for m, desc in present_special.items():
                lines.append(f"- `\\{m}` — {desc}")
            lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines) + "\n"


def _strip_ts(text: str) -> str:
    return "\n".join(l for l in text.splitlines() if not l.startswith(GENERATED_LINE_PREFIX))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Exit 1 if inventory is stale.")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUT.exists():
            print("RAW_SOURCE_INVENTORY.md missing; run: python scripts/scan_raw_sources.py", file=sys.stderr)
            return 1
        if _strip_ts(OUT.read_text(encoding="utf-8")) != _strip_ts(content):
            print("RAW_SOURCE_INVENTORY.md is STALE vs data/raw/ — run: python scripts/scan_raw_sources.py", file=sys.stderr)
            return 1
        print("RAW_SOURCE_INVENTORY.md is current.")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
